### ISSUE TITLE
"microsoftTeams is not defined" error prevents consent dialog from opening

### ISSUE THREAD

**Issue by Victoria-Sardelli** [OfficeDev/Microsoft-Teams-Samples#1014]
Hello,

My teammate and I were trying to run the tab-channel-group-sso-quickstart sample, but we ran into an issue where the consent dialog would not open. 
We ran Teams in the browser and saw an error printed to the console, saying that microsoftTeams is not defined.

We changed line 94 in Tab.js from "microsoftTeams.authentication.authenticate" to just "authentication.authenticate", and it solved the issue for us.

Just wondering if this might also be affecting others, and if any change is required?

Thank you for reading this post!

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
#1040 has been raised to fix this issue.
