### ISSUE TITLE
Update SSO code to leverage BotFramework Cache

### ISSUE THREAD

**Issue by ericsche** [OfficeDev/Microsoft-Teams-Samples#1015]
We should change the code here to leverage the Bot Framework Token Cache, it will improve performance and avoid some issues in corner cases.

The auth card type should be silentAuth and not auth

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/35633680/e219dfcb-cfcf-419a-aaa5-b394463c8863)

https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/app-sso/csharp/App%20SSO%20Sample/Bots/TeamsMessagingExtensionsSearchAuthConfigBot.cs

**Comment by SaiPratap-MSFT** [comment]
@ericsche -  Thanks for raising this, We will check this with concerned team  and will get the code updated
