### ISSUE TITLE
ME Sample SSO node JS typo fix

### ISSUE THREAD

**Issue by ericsche** [OfficeDev/Microsoft-Teams-Samples#1016]
There is a case typo for the connectionName variable 
connectionName is with a lower case "c" everywhere except here. This can cause an issue if you publish the code on linux which is case sensitive.

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/35633680/95e5dbd6-8151-4939-ab36-ebfd6f5dc5da)
The file impacted is here :
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/msgext-search-sso-config/nodejs/bots/teamsMessagingExtensionsSearchAuthConfigBot.js

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and make necessary changes to the sample.

**Comment by ChetanSharma-msft** [comment]
Hello @ericsche - PR is merged now.
We are closing this issue for now, please feel free to reopen it, if required.
