### ISSUE TITLE
[Sample bug] msgext-search python sample not work

### ISSUE THREAD

**Issue by frankqianms** [OfficeDev/Microsoft-Teams-Samples#1017]
When I tried the [msgext-search python sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search/python), I got a runtime error as `RuntimeError: PyPI no longer supports 'pip search' (or XML-RPC search). Please use https://pypi.org/search (via a browser) instead. See https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods for more information.` 

It occurs when users try to enter queries in the search box. 

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/109947924/72f05b6a-8163-4d7f-82c5-6eb16f8aff90)

**Comment by ChetanSharma-msft** [comment]
Hello @frankqianms - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by SaiPratap-MSFT** [comment]
@frankqianms - Could you please provide the python version you are using.So that it would be helpfull

**Comment by SaiPratap-MSFT** [comment]
@frankqianms -  [msgext-search/python](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search/python) sample recently  got updated.We have tested this sample , it is working fine now, not generating any error. .Attaching screenshots for your reference. 
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/146196379/22b95127-c6b0-4d3e-a835-18ea1f6490d1)
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/146196379/2c12178c-59e5-4459-8588-0e24e6e554f0)
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/146196379/e4565f21-9070-49a9-8709-9f33a63dfcca)
