### ISSUE TITLE
Webhooks not firing

### ISSUE THREAD

**Issue by douglasware** [OfficeDev/Microsoft-Teams-Samples#1025]
I assume this is an issue with Teams because none of my webhooks (including stable ones with no changes) are receiving any traffic when @'d , but is there any way to tell?
Teams simply does nothing and the web services do not receive any traffic.

Is there a status page? Is this not considered an incident?

**Comment by Meghana-MSFT** [comment]
@douglasware - We ran this sample https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/outgoing-webhook/nodejs and see that the webhook is responding @mentioned. 

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/3004c21d-14ba-4562-8612-b436c8b52414)

Could you please let us know if you are seeing any errors in console. Please share the network trace at microsoftteamsdev@microsoft.com if you are still facing this issue. 

https://learn.microsoft.com/en-us/azure/azure-web-pubsub/howto-troubleshoot-network-trace#collect-a-network-trace-in-the-browser-browser-based-apps-only.
