### ISSUE TITLE
Webhooksample.exe file missing

### ISSUE THREAD

**Issue by JerryJoel97** [OfficeDev/Microsoft-Teams-Samples#1029]
Trying to setup test outgoing webhook via below tutorial.
https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-outgoing-webhooks?tabs=dev&tutorial-step=4 

Go to AuthProvider.cs file. Update contoso to M365x712764 and add HMAC.
After the above step, when trying to run the project, getting attached error, tried rebuilding the rebuilding solution, still the same issue.

![Error](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/150072936/55a2ade4-a7fb-445c-bc14-90f05d95d51f)

**Comment by SaiPratap-MSFT** [comment]
@JerryJoel97  - Thanks for reporting your issue. We will test this and update you soon.

**Comment by SaiPratap-MSFT** [comment]
@JerryJoel97 -  We are able to run the sample, It did'nt through any error. Here we have used ngrok and we have updated the AuthProvider file with token(HMAC.) .
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/146196379/09e746c6-a125-402a-8503-98fc2e0e295d)

**Comment by ChetanSharma-msft** [comment]
Hello @JerryJoel97 - Please put your application folder directly in C or D drive and check it once.
Looks like it is the issue with the long path.
