### ISSUE TITLE
Code: 7505 Message: Request authorization tenant mismatch.

### ISSUE THREAD

**Issue by rakkaalhazimi** [OfficeDev/Microsoft-Teams-Samples#1036]
## Background
I am using `Microsoft-Teams-Samples/Samples/bot-calling-meeting/csharp/` project. When I try to create a call with the bot, it throws this error, says that there is a mismatch in tenant id. Anyone know why? it is related to which account should I use? or anything else I miss?

![Screenshot 2023-11-13 094050](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/58966937/b2e4e5d1-0c74-46ce-bf4e-97fd65a9fced)
![Screenshot 2023-11-13 094117](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/58966937/27c982ca-afb1-4cda-9333-e04c8185c08d)

## What I've done
- Created Azure Bot
- Use dev tunnel for local test
- Configured cloud configuration (appId, dns, etc.)
- I use Azure App from my personal account and login teams with dev program account.

## Machine/Software Information
- Windows 11 Home Single Language
- Visual Studio 2022
- .NET Framework 4.7.2

**Comment by sayali-MSFT** [comment]
Hello @rakkaalhazimi - Thanks for raising your query.
Could you please create only one app registration and configure the appsettings values accordingly:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/59052547/1dc809ef-e2b5-48fe-a513-3f1b82a11622)
 
Also, please try to test it in same tenant only and check if it's working for you,
Code sample link: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-calling-meeting/csharp/Source/CallingBotSample/appsettings.json
 
has context menu

**Comment by rakkaalhazimi** [comment]
Thank you for the response, @sayali-MSFT . **Using account in the same tenant id solve my problem**. Previously, I use **account in different tenant** because I have no office 365 license, after using same tenant account with free trial office 365, the bot can create call successfully.

**Comment by ChetanSharma-msft** [comment]
Hello @rakkaalhazimi - Please share your valuable feedback for us: [Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)
<https://teams.microsoft.com/l/message/19:1380d0074c954998bdd311d02bc9ac3f@thread.skype/1698765585115?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&amp;groupId=e6142543-e676-4276-8555-6232b0e3a89f&amp;parentMessageId=1698717825641&amp;teamName=Teams Developer Questions&amp;channelName=Bots&amp;createdTime=1698765585115&amp;allowXTenantAccess=false>
