### ISSUE TITLE
Messaging Endpoint Form Payload Issue

### ISSUE THREAD

**Issue by Wajeed-msft** [OfficeDev/Microsoft-Teams-Samples#1046]
### Discussed in https://github.com/OfficeDev/Microsoft-Teams-Samples/discussions/1030

<div type='discussions-op-text'>

<sup>Originally posted by **Bytezart** November  8, 2023</sup>
I'm running into problems with the Azure Bot Service's messaging posts to the sampe TeamsMessagingExtensionSearch project. It appears as though I have the correct AppID's, Passwords and AppTypes set correctly. Specifically, the HTTP post the messaging endpoint doesn't appear to have any form data and is not being flagged as having a HasFormContentType by the runtime.

In the debugger screen shot below I'm sending a message through a Teams Channel for the Azure Bot Service.
  
![Capture](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/15107885/bb231b79-348d-4f64-92f6-60a38dd89d7b)
</div>

**Comment by SaiPratap-MSFT** [comment]
Hi [Bytezart](https://github.com/Bytezart)- This issue is being tracked [here](https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/1031). Please follow that thread for further updates.

**Comment by ChetanSharma-msft** [comment]
Closing it. Please track it here: https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/1031
