### ISSUE TITLE
Sample app-checking-location for Nodejs using deprecated location module

### ISSUE THREAD

**Issue by Nerconer** [OfficeDev/Microsoft-Teams-Samples#1071]
Last update was 2 years ago and is not working when using new MS Teams version.

Code here:
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/d954bffb7a2d425bb2fbcfc0ab1da41a5b111e3b/samples/app-checkin-location/nodejs/views/CheckIn.ejs#L20C3-L20C3

**Comment by Prasad-MSFT** [comment]
@Nerconer - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
The PR is merged. We are closing this issue for now. Please feel free to reopen if required. 

Thanks!
