### ISSUE TITLE
meetings-token-app NodeJS sample is not working with toolkit because manifest folder name is wrong

### ISSUE THREAD

**Issue by Vaibhav-MSFT** [OfficeDev/Microsoft-Teams-Samples#1072]
meetings-token-app NodeJS sample is not working with toolkit because manifest folder name is wrong

https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/meetings-token-app/nodejs/teamsapp.local.yml#L60C28-L60C28

Rather than: manifestPath: ./appPackage/manifest.json

It should be manifestPath: ./appManifest/manifest.json

**Comment by Prasad-MSFT** [comment]
We will redirect this to concerned team to get it fixed. Thanks!
