### ISSUE TITLE
Offer Type for Teams App store submission

### ISSUE THREAD

**Issue by MarkCookBlackLine** [OfficeDev/Microsoft-Teams-Samples#1077]
We are trying to go through the Microsoft Partner Center steps in preparation of submission of our BlackLine Microsoft Teams App to Microsoft for testing and listing. We are running into issues where the options available in the Partner Center are not matching the documentation provided. What Offer Type should we select if Teams App is not present?

According to the documentation, I should see the following when trying to add a New Offer:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/154271255/c20fabef-aea5-4e47-bc59-aaa879943e28)

But what I am actually seeing is (no option for Teams App):
![image (1)](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/154271255/5e90ed9c-4e06-4462-b144-ee2640834148)

**Comment by Meghana-MSFT** [comment]
We will check this and get back to you.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by mrnwosu** [comment]
Was this ever solved??

**Comment by Meghana-MSFT** [comment]
Could you please reach out to Partner Cetner Support: [Get help and contact support in Partner Center - Partner Center | Microsoft Learn](https://learn.microsoft.com/en-us/partner-center/report-problems-with-partner-center#contact-support)
