### ISSUE TITLE
ActivityFeedBroadcast sample does not work

### ISSUE THREAD

**Issue by vovanb** [OfficeDev/Microsoft-Teams-Samples#1100]
Hi 
Provisioned all required info for [ActivityFeedBroadcast](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-activity-feed-broadcast/csharp/ActivityFeedBroadcast) sample, but unfortunately no activities sent to my user.
Note , to make sample working I also needed to modify index.html, otherwise userid was always null and received error on client "the library has not yet been initialized"
```
$(document).ready(function () {

   microsoftTeams.app.initialize().then(() => {
       $('#task-submitted').hide();

       microsoftTeams.app.getContext().then((context) => {
       userId = context.user.id;
       userName = context.user.userPrincipalName;

          
       });       

   });

   if (context.page.subPageId != "" && context.page.subPageId != undefined) {
       let taskInfo = {
           title: "Message details",
           size: {
               height: 400,
               width: 400,
           },
           url: window.location.origin + "/MessageDetails?taskId=" + context.page.subPageId,
       };

       microsoftTeams.dialog.open(taskInfo);
   };

}); 

```

the activity notification does not appear in Teams user , no exception on server and no error in AdapterWithErrorHandler

**Comment by ChetanSharma-msft** [comment]
Hello @vovanb - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
Hello @vovanb - Sorry for delay in response.
Team is looking into this issue and will let you know the updates.

**Comment by vovanb** [comment]
Hello,
note I modified app to use GetGraphClientforApp instead of user' access token. Got notification sent to one user , but not to another. Could we make troubleshooting session?

**Comment by ChetanSharma-msft** [comment]
Hello @vovanb - We are looking into it and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
Hello @vovanb - Sorry for delay in response.
This issue is related to platform, so we have escalated this issue and let you know the updates if any.

**Comment by vovanb** [comment]
@ChetanSharma-msft  
do you have any progress?

**Comment by ChetanSharma-msft** [comment]
Hello @vovanb - Sorry for delay in response.
Engineering team is looking into this issue and trying to repro.
Once we have any update from engineering team, we will let you know.

**Comment by vovanb** [comment]
3 weeks ago passed, do you have any ETA?

**Comment by Prasad-MSFT** [comment]
Team has updated the code with RSC permissions and now the Send notification functionality is working fine. Please find the updated working code in below link.
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-activity-feed-broadcast/nodejs

Ref: https://github.com/MicrosoftDocs/msteams-docs/issues/9434#issuecomment-2029482291

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
