### ISSUE TITLE
Sideloading Disabled

### ISSUE THREAD

**Issue by BoostN** [OfficeDev/Microsoft-Teams-Samples#1101]
I'm using the Teams Toolkit vscode extension and I'm getting the error "Sideloading Disabled". I have used my company tenant (I'm the admin, confirmed app's can be manually uploaded, confirmed and ensured the access policy is open as well). I even stood up a E5 Developer Sandbox which tells you it's configured by default to be open, and when I sign in with that account, I have the same issue.

To Reproduce

Sign up for a new E5 Dev Sandbox.
Connect to that sandbox with the teams toolkit.
Once you sign it, the Sideloading Disabled message appears
Expected behavior

Screenshots
![sideloadfailed](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/6150217/ccdf284b-eb4b-4e33-8215-6551a9a0a369)

VS Code Extension Information (please complete the following information):

CLI Information (please complete the following information):
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by Prasad-MSFT** [comment]
Hi @BoostN - Based on the information provided, it seems that the sideloading permission is not enabled for your app in Teams. Could you please make sure that you have the necessary permissions to enable sideloading?
If you are a tenant admin, you can enable sideloading for your organization in the Teams admin center. If you are not a tenant admin, you will need to contact your tenant admin to enable sideloading.

To enable sideloading using the admin center, follow these steps:

- Sign in to the [Microsoft 365 admin center](https://admin.microsoft.com/Adminportal/Home?source=applauncher#/homepage#/) with your admin credentials.
- Select the Teams icon from the left pane.
- Sign in to the Microsoft Teams admin center with your admin credentials.
- Select the Teams apps option from the left pane, and then click on Setup policies.
- Select the Global (Org-wide default) option.
- Set the Upload custom apps toggle to On.
- Click Save to save the changes.

Please note that it can take up to 24 hours for sideloading to become active. In the meantime, you can use the "upload for your tenant" option to test your app.

**Comment by BoostN** [comment]
> Hi @BoostN - Based on the information provided, it seems that the sideloading permission is not enabled for your app in Teams. Could you please make sure that you have the necessary permissions to enable sideloading? If you are a tenant admin, you can enable sideloading for your organization in the Teams admin center. If you are not a tenant admin, you will need to contact your tenant admin to enable sideloading.
> 
> To enable sideloading using the admin center, follow these steps:
> 
> * Sign in to the [Microsoft 365 admin center](https://admin.microsoft.com/Adminportal/Home?source=applauncher#/homepage#/) with your admin credentials.
> * Select the Teams icon from the left pane.
> * Sign in to the Microsoft Teams admin center with your admin credentials.
> * Select the Teams apps option from the left pane, and then click on Setup policies.
> * Select the Global (Org-wide default) option.
> * Set the Upload custom apps toggle to On.
> * Click Save to save the changes.
> 
> Please note that it can take up to 24 hours for sideloading to become active. In the meantime, you can use the "upload for your tenant" option to test your app.

Hello,

After 24 hours it appears to work now.. I feel like something was cached in Teams Toolkit (or VS Code). Even the developer sandbox would not work. We can close this.
