### ISSUE TITLE
Microsoft Teams Custom App Anonymous user can't show content Stage View

### ISSUE THREAD

**Issue by theogumilang** [OfficeDev/Microsoft-Teams-Samples#1103]
So I want to create a meeting extension App, this app will be able accessed by internal users and anonymous users so we try to deploy this app in our environment https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-anonymous-users/csharp, We are able to deploy it and we can access the app in our internal users. But for our Anonymous users, it will show a message something went wrong whenever we use the stage view. 

We noticed there is an update in Microsoft Teams, is this a known bug or issue, we really need this feature.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29269601/76c3ca61-602e-420b-9ea9-b06edb319e46)

We already set to for anonymous users can interact with the apps

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29269601/3b2868ff-d922-4ccc-b59c-1c89510c3a9e)

And in our manifes.json we already set for support anonymousguestusers too enter image description here
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29269601/791c77ea-bcca-4cf1-8c3f-48940887ae0d)

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by theogumilang** [comment]
@Meghana-MSFT Hi actually I'm using a browser, and previously we were using a Microsoft Teams mobile too but still can't show the content. is this feature only available on Dekstop App?

**Comment by theogumilang** [comment]
Hi @Meghana-MSFT , this is the v2 version I still not able to shows the content.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29269601/8dbd518f-77f3-4bf0-98c8-ee60f726187c)

**Comment by theogumilang** [comment]
> Hi @Meghana-MSFT , this is the v2 version I still not able to shows the content. ![image](https://private-user-images.githubusercontent.com/29269601/294519081-8dbd518f-77f3-4bf0-98c8-ee60f726187c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NjQ3NTAsIm5iZiI6MTcwNDQ2NDQ1MCwicGF0aCI6Ii8yOTI2OTYwMS8yOTQ1MTkwODEtOGRiZDUxOGYtNzdmMy00YmYwLTk4YzgtZWU2MGY3MjYxODdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE0MjA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMGU2YjUyZWYyNWJjMjkyMzk1ODFkZThmOTljMDY3OTBlYzRhMTU5MTM1MmVhMDg1NmYzZGFlYTcwYWIxMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uBUc2m7C__3kmgQ2FpkN6PPIGEp8uAHExKmwgvUoINs)

And this is when I tried the apps login as Anonymous or external users 
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29269601/f422476b-5ba0-4048-ae78-16074d12b573)

**Comment by Meghana-MSFT** [comment]
thank you for the additional information, we will check this and update you.

**Comment by Meghana-MSFT** [comment]
We checked this at our end and it is working fine. Guest user can see the below screen and there is no error pop up. 
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/109c1dc5-5736-481e-8558-ebc39ad3a46c)

**Comment by theogumilang** [comment]
Hi @Meghana-MSFT, Thanks for your confirmation let me try check again about our configuration. But I do have a question what makes the teams meeting app work for anonymous is it only in the manifest and teams admin setting or is there any specific code that enables that features, because we view the code on github and we only see this context.user.licenseType and it just for condition to see if user is anonymous or not.

**Comment by Meghana-MSFT** [comment]
Yes, its the property in manifest.
