### ISSUE TITLE
MS Teams User still receives the notification after deleting the Bot Application from MS Teams Admin Center.

### ISSUE THREAD

**Issue by sapnaavya** [OfficeDev/Microsoft-Teams-Samples#1104]
When teams admin deletes the bot app in the teams admin center, users are still receiving the MS teams notifications from the bot. Since bot is deleted from the teams admin center, they should not receive the notification or would the users need to uninstall/block the bot from their MS Teams instance to stop recieving the notification?

**Comment by Meghana-MSFT** [comment]
When a Teams admin deletes a bot app from the Teams admin center, it removes the app from the organization's app catalog and prevents users from discovering, adding, and interacting with the bot. However, deleting the bot from the Teams admin center does not automatically remove the bot from individual users' Teams instances.
To stop users from receiving notifications from the deleted bot, they need to uninstall or block the bot from their own Teams client. 
By uninstalling or blocking the bot, users will no longer receive notifications or have any interaction with the bot in their Teams client.
