### ISSUE TITLE
Sample meetings-live-code-interview nodejs version cannot run with Teams Toolkit

### ISSUE THREAD

**Issue by JerryYangKai** [OfficeDev/Microsoft-Teams-Samples#1105]
Repro step:

1. download the app, 
2. Using Teams ToolKit, press F5, 
3. In the pop-up browser, click 'install the app'.

Screen shot:
in the meeting, cannot add the app, the config page is failed
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/53805504/bb42966d-e4c7-4af4-b279-450dd09fb29b)

Detailed error:
The config page return status code 502. 
I found this page is redirected by dev tunnel. The origin page localhost:3978/config works well.  But the dev tunnel forward URL is break.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/53805504/6b16ee3a-df7e-444b-b6a3-616e57487da6)
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/53805504/b6154c51-4dd2-4e00-8811-a509eab9a54c)
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/53805504/09d3f6ec-b96c-4b85-ab98-4736e2364a14)

**Comment by Prasad-MSFT** [comment]
@JerryYangKai - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
Hi @JerryYangKai - We are also able to repro this issue. We are checking this with concerned team and will take appropriate actions accordingly.

Thanks!

**Comment by JerryYangKai** [comment]
I have tested the latest version, error occurred when press F5, the 'start frontend' task.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/53805504/a8541398-833a-4a8b-b0f4-137e7563870d)
Please help check it.

**Comment by Mohammed-MSFT** [comment]
Hi **@JerryYangKai** 

**Hope you're doing good !!**

I guess, there might be Nodejs version Issue
For your information I added more details, kindly check it once.

- Node version **18.17.1**
- Teams Toolkit version **5.4.0**

**FrontEnd**
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/109147706/8b2e09e9-47ca-4427-91fe-ea70860a078d)

**Backend**
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/109147706/251c5509-54bb-4e56-b104-62ca7859dc2e)

**Live Share SDK Fluid-Frameowrk** 
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/109147706/751be75b-36bd-4402-b7d6-5757b6169da4)

**App Running Screenshots**
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/109147706/17ee163d-3304-4925-b233-4ef6f115597d)

**Configurable tab with save button enabled**
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/109147706/464817c1-18dc-4f95-997e-5540d45e10aa)

**In Meetings Stage View**
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/109147706/501e024e-2d06-4883-8270-4b5469385ca8)


**Thanks !!**

**Comment by JerryYangKai** [comment]
@Mohammed-MSFT  Thanks for your quick reply!
I have upgraded the node to 18.17.1, then I met another problem when start frontend
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/53805504/44b70935-9f84-4377-bfe7-affacd89a492)
I have tried to change the react-script package version, but it not works too,

**Comment by JerryYangKai** [comment]
@Mohammed-MSFT Thanks for your quick reply!
Change node version fix the issue.
Closed.
