### ISSUE TITLE
OAuth sign-in ok with ngrok, not ok when deployed to webapp

### ISSUE THREAD

**Issue by ferokko** [OfficeDev/Microsoft-Teams-Samples#1108]
Hi, 

I followed the tutorial to add auth within the teams bot: (https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-teams-authentication)

I am experiencing a strange behavior in that, after all the proper settings, the example runs well with ngrok. Once I deploy the solution to the webapp and fill the env variables accordingly I got this error 

Sorry, it looks like something went wrong. Exception Caught: Operation returned an invalid status code ‘NotFound’ at Microsoft.Bot.Connector.OAuthClient.GetSignInResourceWithHttpMessagesAsync....

I debugged locally with ngrok and remotely the webapp and I see the following:

- with ngrok this call returns 200 :
System.Net.Http.HttpClient.Default.LogicalHandler: Information: Start processing HTTP request GET https://api.botframework.com/api/botsignin/GetSignInResource?state=XXX
OAuth card is displayed properly and sign in is completed

- with remote debugger (from the webapp) I can see that the very same call (even the same state, is that normal?) returns 404, the card is not displayed and it throws an error as above

I am facing it both for single and multitenant and I am using regional bot (europe)

As anyone experienced that?

Thanks in advance

**Comment by ChetanSharma-msft** [comment]
Hello @ferokko - Thanks for raising your query.
We have deployed the C# sample already.

Could you please try to download the deployed zip and test it once and let us know if you are still facing the issue?
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-teams-authentication/csharp#try-it-yourself---experience-the-app-in-your-microsoft-teams-client
