### ISSUE TITLE
[Teams Toolkit - Certificate] Readme steps are not correct for graph-meeting notification and graph-change-notification-team-channel.

### ISSUE THREAD

**Issue by ChetanSharma-msft** [OfficeDev/Microsoft-Teams-Samples#1121]
Running the sample using toolkit: Steps are missing to create and update the certificate:

Also, what all are the below values and how to update those in .env file are not explained in readme:
Base64EncodedCertificate= "<<Base64EncodedCertificate>>"
EncryptionCertificateId= "meeting-notification-certId"
PRIVATE_KEY_PATH=<<PrivateKeyFileName>>
OPENSSL_CONFIG="C:/Program Files/OpenSSL-Win64/bin/openssl.exe"

**Comment by Harikrishnan-MSFT** [comment]
Hi @ChetanSharma-msft 
I have updated the Readme and attached the PR link below.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/117716554/c6490529-ffbf-4e15-baa9-42cd58d5bb0e)

https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/1121

**Comment by ChetanSharma-msft** [comment]
Commit link: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1113/commits/35e65bfa6a39b1103845aaceeeb1b07e5d1c601d

**Comment by ChetanSharma-msft** [comment]
Merged the PR.
We are closing this issue for now, please feel free to reopen it, if required.
