### ISSUE TITLE
Sample code is not working for anonymous user "In-meeting notification"

### ISSUE THREAD

**Issue by ChetanSharma-msft** [OfficeDev/Microsoft-Teams-Samples#1124]
Sample code is not working for anonymous users: https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/in-meeting-notification-for-meeting?tabs=desktop#code-sample

https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-notification/nodejs

**Comment by ChetanSharma-msft** [comment]
@Pawank-MSFT - Please help to fix this sample code.

**Comment by Prasad-MSFT** [comment]
This issue is fixed. (Both in Teams Desktop/Web client). So, we are closing this issue.
![image](https://github.com/user-attachments/assets/895c1b36-69e0-4cf2-abfa-f312d7a7b0a8)

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
