### ISSUE TITLE
New Sample App Submission - Guidance Requested

### ISSUE THREAD

**Issue by Victoria-Sardelli** [OfficeDev/Microsoft-Teams-Samples#1143]
Hello,
 
I’d like to submit a new Teams sample app demonstrating the use of deep links to pass values to tab apps. Could you please guide me through the submission process?
 
### Description
The sample tab app shows how to retrieve data that was passed through a deep link. It also demonstrates the creation of two types of deep links: one for opening the app in Teams, and another for opening the app directly in the browser using its public URL. This dual-support enables information to be passed to the app both inside and outside of Teams.
 
### Background
Deep links facilitate passing data to an app when it loads, enabling operations like internal page navigation and database searches. Using deep links, you can quickly lead users to specific content in your application or perform other app logic.
However, Teams requires a unique format for deep links. If an app needs to support both Teams and standalone access, then two different URL formats are needed. This sample app is designed to help other developers understand and implement deep linking as a way to pass values to their Teams tab apps.

#### Creating a deep link for the tab app
![creating a deep link for tab app](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/8617176/eee9c3c8-a908-4b5a-b050-84aa2f6b7ef4)

#### Creating a deep link for the standalone web app
![creating a deep link for standalone app](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/8617176/5aeb29ad-550d-4cbe-9158-cb7f6fd77106)

#### After clicking a deep link for the tab app (passed value is retrieved and displayed)
![using a deep link for tab app](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/8617176/4d4500ce-f441-442d-909e-87b576ac34f7)

Thank you very much for your help!

**Comment by ChetanSharma-msft** [comment]
Hello @Victoria-Sardelli - Thanks for raising your query.
Could you please confirm whether you want to publish/submit your app to Teams app store?

If yes, you can refer this documentation: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/publish

If you are just looking to deploy/publish your application, you can refer this: https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/publish

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision?pivots=visual-studio-code-v5

**Comment by Victoria-Sardelli** [comment]
Hi @ChetanSharma-msft - Thank you for your response!
I was hoping to submit my code sample as a contribution to this repository. Is there a process for this?

Thanks for your help!

**Comment by ChetanSharma-msft** [comment]
@Victoria-Sardelli - Thanks for your interest in contribution.
We already have one sample related to deep link, so you can refer that sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-deeplink

If you feel that you need to add your suggestions which does not exists, you can raise the PR with your changes and later our team will review the code accordingly.

**Comment by Victoria-Sardelli** [comment]
Hi @ChetanSharma-msft - Thank you very much for your guidance! I will prepare the code and raise a PR soon.

**Comment by Victoria-Sardelli** [comment]
Hi @ChetanSharma-msft - I just created a PR: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1150
Thank you to you and your team in advance for reviewing it. Would love to know what you think!

**Comment by Pawank-MSFT** [comment]
@Victoria we have verified sample and it is working fine, we will TTK migrated the sample after publishing.

**Comment by Pawank-MSFT** [comment]
@Victoria-Sardelli  PR is merged.

**Comment by Victoria-Sardelli** [comment]
Hi @Pawank-MSFT, thank you so much for your swift reply and approval of my PR. I truly appreciate it!

**Comment by Victoria-Sardelli** [comment]
Hi @ChetanSharma-msft , sure thing! I just submitted it.
