### ISSUE TITLE
Update bot templates to stop sending a message on error, when the activity is not a message directed to it

### ISSUE THREAD

**Issue by aosolis** [OfficeDev/Microsoft-Teams-Samples#1145]
Please see corresponding issue in the TeamsFX repo:
https://github.com/OfficeDev/TeamsFx/issues/10865

**Comment by ChetanSharma-msft** [comment]
Hello @aosolis - Thanks for raising the issue.
We will look into it and let you know the updates.

**Comment by Wajeed-msft** [comment]
For Teams Sample repo, this change is already done for all the samples as part of [this PR](https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/661/files). 

@ChetanSharma-msft - please confirm do one round of checks for all the Bot and ME sample.

**Comment by ChetanSharma-msft** [comment]
Hello @Wajeed-msft, @aosolis - We have done the changes for all the samples.

We are closing this issue for now, please feel free to reopen it, if required.
