### ISSUE TITLE
Sample app-checkin-location for Nodejs not working with New Microsoft Teams

### ISSUE THREAD

**Issue by Nerconer** [OfficeDev/Microsoft-Teams-Samples#1147]
Hello,

On December I opened the following ticket https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/1071 because the example was using a deprecated module and **it could be the reason why it is not working on New Microsoft Teams.**

It is still using the same module, it basically just upgraded the version.
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/bc50b6458143da96ee7d1c243589809cd66e4a33/samples/app-checkin-location/nodejs/views/CheckIn.ejs#L22
<img width="700" alt="image" src="https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7198106/d24bdd42-5630-4a22-a993-25ff75687602">

With the current example, **sharing location in New Microsoft Teams it is not working** and it won't open the map:
<img width="300" alt="image" src="https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7198106/7d13cfa5-6bfb-4d96-a5bb-ac73402f744b">

In Classical Microsoft Teams it works fine.

It is planned to migrate to New Microsoft Teams after March 31st, 2024 so after that, the app we are using in production will be broken.

<img width="800" alt="image" src="https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7198106/c8a05a47-7d3b-47d8-b807-fd272d65267d">

Thank you for your work.

**Comment by Prasad-MSFT** [comment]
@Nerconer - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
We are able to repro this issue and are checking this internally to fix the sample. Once this is fixed, we will notify you in this thread.

Thanks!

**Comment by Nerconer** [comment]
Hello.

Do you have any updates?

**Comment by Pawank-MSFT** [comment]
Issue is fixed and we have raised the PR, once is merged will let you know
https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1131

**Comment by Nerconer** [comment]
Hi @Pawank-MSFT, thank you for you work.
A couple of things that I've noticed is that for `samples/app-checkin-location/nodejs/views/CheckIn.ejs` file, `showMap()` and `showButtonToEnableMap()` functions, its implementations are missing.

**Comment by Pawank-MSFT** [comment]
Hi @Nerconer, thanks for suggestion, I've removed Un-used code in the same PR.

**Comment by Nerconer** [comment]
Hi @Pawank-MSFT thanks for the update. I've been trying to execute the code but it gets stuck in the following screen:
<img width="300" alt="image" src="https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7198106/e3c4efb9-1405-4135-b3f2-f34d9d101db1">
What I saw is that `result.state` returns `prompt` value instead of `granted`.
If I go to App permission I can see that I have enabled Location permission:
<img width="1000" alt="image" src="https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7198106/d9cfc6f2-f6ef-47e1-971c-c932897db94b">
Not sure if Teams should ask me again about this permission when clicking the card or what should I do next.

Thanks!

**Comment by Nerconer** [comment]
Quick update: I've been trying the app on several OS/browsers and this is what I've found:

- Windows & Chrome: working ✅
- Windows & Desktop Teams V2 app: working ✅
- Windows & Edge: not working ❌
- MacOS & Chrome: not working ❌
- MacOS & Desktop Teams V2 app: not working ❌
- MacOS & Ipad: working ✅

For desktop MacOS users it seems that there is no functional combination.

A thing I've noticed is that we are losing the capability of manually setting our location since no map is showing now. 

**It there any way to recover the map functionality again on Teams V2?**

**Comment by Pawank-MSFT** [comment]
@Nerconer Currently media api is not supported in T2.1 desktop, Could you please check browser.

**Comment by Nerconer** [comment]
@Pawank-MSFT I've been able to make it work on MacOS & Chrome. In this scenario If the card makes a request to an ngrok endpoint it fails (it is like a Teams V2 client bug) but if not, it works fine.

However, **how can we open a map now so users can manually set their location?**

**Comment by ChetanSharma-msft** [comment]
Hello @Nerconer - Location API is currently not supported in New Teams Client, so we recommend you to use HTML location for now.
If you are already using it, please refer the limitations here:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/59052547/817af1f9-1c9e-4760-9974-7c95755abddc)

https://www.w3schools.com/html/html5_geolocation.asp

**Comment by Nerconer** [comment]
Hello @ChetanSharma-msft - Thanks for the clarification. Is it planned to support Location API in New Teams Client in the future? If so, do you know when?

Thanks in advance

**Comment by ChetanSharma-msft** [comment]
Hello @Nerconer - Yes, we will support API's in new teams' client but currently we do not have any Exact ETA to share with you.

**Comment by Nerconer** [comment]
Thank you @ChetanSharma-msft

**Comment by ChetanSharma-msft** [comment]
Hello @Nerconer - Please raise your feature request here: [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

Also, please let us know whether we can close this issue?
