### ISSUE TITLE
String data rendered into table in webchat but its not rendering properly in MS team

### ISSUE THREAD

**Issue by NagarroShobharaja** [OfficeDev/Microsoft-Teams-Samples#1149]
## Describe the bug
I'm getting table data in string from OpenAI it is rendered into table in webchat fine but its not rendering properly in MS team. Please refer the screenshot.

## To Reproduce
1. create a bot
2. integrate it with azure OpenAI
3. Ask the question "give me random student data in tabular form"

## Expected behavior
want the same table rendering in both Webchat and MS Teams

## Screenshots
Webchat
<img width="732" alt="image" src="https://github.com/microsoft/BotBuilder-Samples/assets/144764642/3fb352d0-f765-439c-8f61-e7eea781e328">

MS Teams
<img width="637" alt="image" src="https://github.com/microsoft/BotBuilder-Samples/assets/144764642/f83a1337-64df-4658-a11f-f8f6708b6f15">

**Comment by Vaibhav-MSFT** [comment]
Hello @NagarroShobharaja ,
Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by ChetanSharma-msft** [comment]
Hello @NagarroShobharaja - Could you please share all the steps and code you have referred to setup and test the app?
Are you trying it in Azure Bot web chat?
