### ISSUE TITLE
MS Teams Calling bot not working

### ISSUE THREAD

**Issue by Javeria-Arif** [OfficeDev/Microsoft-Teams-Samples#1160]
Hi,

I have been following this guide to create a calling bot:

[https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-bot-calling-meeting-csharp/](https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-bot-calling-meeting-csharp/)

 
I have followed each step. I have added the bot as a custom app in Teams and i am able to send a message/ perform a call action. But the problem here is that the code is not returning any response. There is no response for even a simple welcome request. 

The code is not throwing any error. Therefore I am unable to understand, why the bot is not working as expected. 
After I send a message/ call the "calling bot" from my teams account, the request is landing on the controller, without any error. But I dont see a response on the bot side on Teams.

Can anyone help me with this?

**Comment by ChetanSharma-msft** [comment]
Hello @Javeria-Arif - Thanks for raising your query.
Could you please check if all the configurations are done properly.

Also, please check if you have added **policy** proper:
# Import-Module MicrosoftTeams
# Call Connect-MicrosoftTeams using no parameters to open a window allowing for MFA accounts to authenticate
Connect-MicrosoftTeams
New-CsApplicationAccessPolicy -Identity “<<policy-identity/policy-name>>” -AppIds "<<microsoft-app-id>>" -Description "<<policy-description>>"
Grant-CsApplicationAccessPolicy -PolicyName “<<policy-identity/policy-name>>” -Identity "<<object-id-of-the-user-to-whom-policy-need-to-be-granted>>"

**Comment by ChetanSharma-msft** [comment]
This is a duplicate issue, so please track it here:
 https://techcommunity.microsoft.com/t5/teams-developer/ms-teams-calling-bot-not-working/m-p/4063162#M9609

**Comment by Javeria-Arif** [comment]
@ChetanSharma-msft  Yes i have double-checked all the configurations. For authorizing the bot, I used these commands:

Connect-MicrosoftTeams
New-CsApplicationAccessPolicy -Identity “<<policy-identity/policy-name>>” -AppIds "<>" -Description "<>"
Grant-CsApplicationAccessPolicy -PolicyName “<<policy-identity/policy-name>>” -Identity "<>"
