### ISSUE TITLE
CSharp bot-file-upload TeamsFileUploadBot.FileUploadCompletedAsync always sends an error message

### ISSUE THREAD

**Issue by tracyboehrer** [OfficeDev/Microsoft-Teams-Samples#1176]
```
            // var reply = MessageFactory.Text($"<b>File uploaded.</b> Your file <b>{fileConsentCardResponse.UploadInfo.Name}</b> is ready to download");
            // Added defects to check automation flow

            var reply = MessageFactory.Text($"<b>File upload failed.</b>");
            reply.TextFormat = "xml";
            reply.Attachments = new List<Attachment> { asAttachment };

            await turnContext.SendActivityAsync(reply, cancellationToken);
```

**Comment by Vaibhav-MSFT** [comment]
Hello @tracyboehrer ,
Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by tracyboehrer** [comment]
@Vaibhav-MSFT No update required.  I just found it testing something on the BF SDK side.  The sample works fine except displays "File upload failed" all the time.

**Comment by ChetanSharma-msft** [comment]
Hello @tracyboehrer - Shall we close this issue now?

**Comment by tracyboehrer** [comment]
@ChetanSharma-msft Up to you.  However, always sending "File upload failed" when it worked isn't correct.

**Comment by Vaibhav-MSFT** [comment]
Hello @tracyboehrer ,
We have tested the nodejs sample for file upload and it's working fine, while the csharp sample after migrating to Teams toolkit we are facing some problems and currently looking into it.

**Comment by Vaibhav-MSFT** [comment]
Hello @tracyboehrer ,
The error has been fixed and the CSharp code is running fine, whereas the new sample with teams toolkit migration is still facing some errors.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
