### ISSUE TITLE
Teams token not getting generated on Mobile app but works fine on Web and Desktop

### ISSUE THREAD

**Issue by Kumar-Aakash** [OfficeDev/Microsoft-Teams-Samples#119]
My custom app is in Angular and everything was working fine till a few weeks back. I was able to log in and generate tokens on both Web and Mobile app versions for the custom app but surprisely now, it has stopped working now. I cannot see where the issue is now. I have tested on Android ( Version 11 )

"@microsoft/teams-js": "1.10.0"

Here is my code snippet.

```
import * as microsoftTeams from '@microsoft/teams-js';

microsoftTeams.initialize(() => {
      this.microsoftAppAuth();
 });

microsoftAppAuth() {
    microsoftTeams.registerOnThemeChangeHandler((theme) => {
      setTheme(theme);
    });

    function setTheme(theme) {
      if (theme) {
        document.body.className =
          'theme-' + (theme === 'default' ? 'light' : theme);
        localStorage.setItem('theme', document.body.className);
      }
    }

    const authTokenRequest = {
      successCallback: (result) => {
        this.authService.setToken(result);
        microsoftTeams.appInitialization.notifySuccess(); // important in case of "showLoadingIndicator": true in manifest file
        localStorage.setItem('msteam', '1');
      },

      failureCallback: (error) => {
        console.log('Inside Teams Login Failure: ' + error);
      },
    };
    microsoftTeams.getContext((context) => {
       if (context) {
        if (context.theme) {
          setTheme(context.theme);
        }
        if (context.locale !== undefined && context.locale !== '') {
          this.translateService.use(context.locale.match(/es|es-ES/) ? 'es' : 'en');
        }
      }
      microsoftTeams.authentication.getAuthToken(authTokenRequest);
    });
  }
```

Like I mentioned in the title, the above code works fine in the Teams web version the only issue I am facing is on Mobile App.

**Comment by Wajeed-msft** [comment]
@Kumar-Aakash - did you add Mobile App Id in [Authorized client applications](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#1-create-your-aad-application)? 

![image](https://user-images.githubusercontent.com/31851992/125812452-42ad7400-d40a-4b53-8669-c4f5a57b0ee8.png)

**Comment by Kumar-Aakash** [comment]
@Wajeed-msft Yes client id is added properly. Like I mentioned before, it was working a few weeks back and suddenly stopped working. I checked all code and nothing changed regarding this flow and all Azure configs are proper.

**Comment by Wajeed-msft** [comment]
@Kumar-Aakash - Thanks for confirmation. I'll try to repro getContext issue based on your comment. Meanwhile could you please also share App version details of your Teams Mobile app?

**Comment by Kumar-Aakash** [comment]
@Wajeed-msft Yes, I have more details for you. We have two angular apps both have the same code for Teams authentication. 

One application with **Angular version 9**, works fine in the mobile app. While another application for which this issue was raised is using **Angular version 11** and for which it doesn't work only in mobile. Both apps work fine in the Web teams.


The manifest version in both apps - **1.9**

Not sure why it behaves this strangely?

**Comment by Wajeed-msft** [comment]
@Kumar-Aakash - do you have minimal repro steps which I can try at my end? May be just a simple page which shows repro for getContext() failure would help.

**Comment by Kumar-Aakash** [comment]
@Wajeed-msft I have fixed the issue by troubleshooting the app in Mobile dev tools by connecting my mobile to my laptop. The issue was Teams-js library version. I used the latest one and I also upgraded Angular 11 to Angular 12 and it started working. Strange fix but mobile is loading in Angular 12 version.
