### ISSUE TITLE
Scan QR Code is not working in both the devices IOS/Android in bot-join-team-using-qr-code Sample  

### ISSUE THREAD

**Issue by Vikram-MSFT** [OfficeDev/Microsoft-Teams-Samples#1190]
Sample Link :
[bot-join-team-using-qr-code](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-join-team-using-qr-code)

![image (1)](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/152395416/13b495d0-745c-43a9-90f8-49bfc7bdffd2)
![image (2)](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/152395416/c3d118c2-1c95-4743-b0ef-84c09cbf2fc0)

It is showing Error Code  : 1000 after scan.

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
We are pleased to inform you that the bug has been fixed! We have verified the fix in the following versions:

Android : Version 1416/1.0.0.2024193102

Please verify on your end and confirm if everything is working as expected.
