### ISSUE TITLE
msgext-search doesn't work on new Teams

### ISSUE THREAD

**Issue by jjjadey** [OfficeDev/Microsoft-Teams-Samples#1209]
I create code from [this sample](https://github.com/OfficeDev/TeamsFx-Samples/tree/v2.4.0/query-org-user-with-message-extension-sso). **I found that after I selected a preview item, a selected item doesn't work on new Teams (v2)**. 
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/47839144/8f8a4a14-3389-4d9b-a80f-480a54aedcee)

Old Teams
![old-teams](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/47839144/5c1cb473-c71a-4737-8508-873ab7475830)

New Teams
![new-teams](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/47839144/9924b386-bee2-4ccf-8721-541b28da154c)

I compared the response from /invoke and it's the same both old and new Teams
```
{
    "composeExtension": {
        "attachments": [
            {
                "content": {
                    "title": "ABC",
                    "text": "hello world",
                    "images": [
                        {
                            "url": "https://as-prod.asyncgw.teams.microsoft.com/v1/objects/0-ea-d5-71aa848813d1b34d16f3a20a9bd8f9e6/views/img_preview"
                        }
                    ]
                },
                "contentType": "application/vnd.microsoft.card.thumbnail"
            }
        ],
        "type": "result",
        "attachmentLayout": "list"
    },
    "responseType": "composeExtension"
}
```

**Comment by Prasad-MSFT** [comment]
Hi @jjjadey - thanks for raising your issue. We tried with [this sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search/csharp) and observed that it works fine both in Teams Classic and New Teams. Could you please confirm if you are facing the same issue with the above mentioned sample or not?

**Comment by jjjadey** [comment]
@Prasad-MSFT Thank you very much for your response. I found another sample works fine too [msgext-search-quickstart](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search-quickstart/js)

**Comment by Prasad-MSFT** [comment]
**Update:**

We have raised a bug for the same. We will inform you once we get any further update from engineering team. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @jjjadey, are you still encountering this issue?
