### ISSUE TITLE
The update_activity python documentation contains errors and no samples for update_activity

### ISSUE THREAD

**Issue by DeanHnter** [OfficeDev/Microsoft-Teams-Samples#1226]
The current documentation on update_activity for python contains errors and so isnt directly usable without modification, further the referenced example of update_activity is focused on updating a card activity but doesent actually give a example of updating a regular message factory. This would be useful as currently im struggling to find an answer to "error unknown" as a resulting response and it would help to reduce the confusion if the samples were actually functional and demonstrated the API's usage correctly.

```
# Send initial message
message = await turn_context.send_activity("<Your Message>")
activityId = message.id # Fetch activity id.

# MessageFactory.Text(): Specifies the type of text data in a message attachment.
new_activity = MessageFactory.text("The new text for the activity")
new_activity.id = activity_id

# A method that can participate in update activity events for the current turn.
update_result = await context.update_activity(new_activity)
```

`An error occurred while updating the activity: (ServiceError) Unknown`

context seems like it should be referencing turn_context which would be consistent with other examples however as mentioned this sample does not work for me as update_activity always results in a error: unknown. Further the activity_id seems to reference the variable defined previously activityId, so in short this is a confusing example and I cant get the code to function even if i imply that the error is caused by these mistakes i get an ambiguous error unknown message.

**Comment by ChetanSharma-msft** [comment]
Hello @DeanHnter - Thanks for raising your query.
Could you please share the doc link that you are following including the sample, if you are referring?
Also, please let us know what exact version you are using for Python?

**Comment by DeanHnter** [comment]
> Hello @DeanHnter - Thanks for raising your query. Could you please share the doc link that you are following including the sample, if you are referring? Also, please let us know what exact version you are using for Python?

Hi thanks for looking into it. Here is the link to the original document and the python version is 3.11

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/update-and-delete-bot-messages?tabs=dotnet

**Comment by krishnab333** [comment]
facing the same issue in update activity. any updates ?

**Comment by DeanHnter** [comment]
> facing the same issue in update activity. any updates ?

Looks like the referenced ticket isn't addressing the same issue (superficially) here so not sure if we will see a fix soon Expecting that moving to c# implementation would be easier than waiting on a fix at this point.

**Comment by Vaibhav-MSFT** [comment]
@DeanHnter , we are actively working on this and will let you know the updates.

**Comment by Vaibhav-MSFT** [comment]
Hello @DeanHnter ,
We got an update from the sample team that using below code we will be able to update regular message and also the adaptive card.
# Send initial message
message = await turn_context.send_activity("<Your Message>")
activityId = message.id # Fetch activity id.

# MessageFactory.Text(): Specifies the type of text data in a message attachment.
new_activity = MessageFactory.text("The new text for the activity")
new_activity.id = activity_id

# A method that can participate in update activity events for the current turn.
update_result = await context.update_activity(new_activity)

**Comment by DeanHnter** [comment]
> Hello @DeanHnter ,
> We got an update from the sample team that using below code we will be able to update regular message and also the adaptive card.
> 
> message = await turn_context.send_activity("<Your Message>")
> activityId = message.id # Fetch activity id.
> 
> new_activity = MessageFactory.text("The new text for the activity")
> new_activity.id = activity_id
> 
> update_result = await context.update_activity(new_activity)

Hi thank you for the feedback. Unfortunately the problem hasn't been addressed in any direction.

1. I update the packages and fixed the code provided, and I still received an unknown error response as outlined in my original issue.
2. The sample provided as outlined in my original response still won't work and will never work. It contains obvious errors that even the worst AI or even IDE could point out yet apparently the sample team cannot even detect. It's very clear either activity_id should actually be the variable activityId or there is another variable that isn't clearly outlined at play in this example.

I cannot recommend anyone actually use this library until the basic functionality actually works and samples that are coherent are produced, it makes no sense that this is the response.

**Comment by Vaibhav-MSFT** [comment]
@DeanHnter , 
We will again look into this on priority basis and let you know the updates asap.

**Comment by sethteo** [comment]
@Vaibhav-MSFT  any updates on this? facing the same issue

**Comment by Nivedipa-MSFT** [comment]
@sethteo - Apologies for the delay, we will check this and update you soon.

**Comment by DeanHnter** [comment]
Any updates?

**Comment by DeanHnter** [comment]
I am closing this issue. It seems resolved either by upgrading to a newer version of python or by upgrading to the latest (4.16.1) version of bot-builder. Either way for me it now works, the documentation however is still not updated and still contains the incorrect variable names as previously outlined. I no longer care to keep this issue/discussion open as its clear microsoft employees arent capable. I would still recommend migrating to another solution for anyone encountering this issue.
