### ISSUE TITLE
bot-teams-authentication sign-in prompt does not render in Microsoft Teams

### ISSUE THREAD

**Issue by emahama** [OfficeDev/Microsoft-Teams-Samples#1229]
I'm trying to repro the bot-teams-authentication sample running on my local machine using ngrok. The sample runs fine using Bot Emulator, but the sign-in dialog does not display in Microsoft Teams.
 
Emulator
======
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/95234948/c5c813c2-08d1-46dd-8e07-613a64499cd9)

Teams 
====
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/95234948/63685d6f-bf6d-4935-aa03-4439139ee239)

I have updated the manifest with my bot id and my valid domain is below.

 "permissions": ["identity", "messageTeamMembers"],
 "validDomains": [ "token.botframework.com", "*.use.devtunnels.ms", "online.microsoftlogin.com", "*.ngrok-free.app" ],
 "webApplicationInfo": {
   "id": "a71ec1da-213b-4282-bc93-732d3cxxxxx",
   "resource": "api://botid-f2bc1632-be51-4f44-8135-f2212xxxxx"
 }

**Comment by Meghana-MSFT** [comment]
@emahama - We see that you are using a different ID in id and resource
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/909ab571-7e4d-4582-bc98-1731ef715025)

Could you please check once?

**Comment by Meghana-MSFT** [comment]
We will check this at our end and get back to you.

**Comment by Aspyryan** [comment]
Same here btw

**Comment by emahama** [comment]
Okay I will try again .

**Comment by emahama** [comment]
I followed this link you share and now it works. Thank you
