### ISSUE TITLE
bot-teams-authentication csharp sample not working with Teams client but working in Teams web

### ISSUE THREAD

**Issue by Aspyryan** [OfficeDev/Microsoft-Teams-Samples#1237]
Hi, I have built a chatbot for my company and all of a sudden it stopped working. I am now trying to figure out what is wrong, so I went back to some samples to check if it's my fault. I am running the bot-teams-authentication sample on the teams client specified below.
The bot responds but is not willing to enter the `OnTeamsSigninVerifyStateAsync` line in the code, thus never receiving a token succesfully. When testing this in the web teams, everything works as expected. What could I do now to debug further?

Teams version: 24074.2321.2810.3500
Last update: 16/04/2024
Client version: 49/24031414716

Web client version: 1415/24022924517

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/52763578/619bc34a-50bd-4ead-bb91-0e7cb5d3f82d)
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/52763578/9483937d-86e1-4618-956b-d9ab7b42f129)

**Comment by Aspyryan** [comment]
Web client version updated to `1415/24031414718` and is now also not working anymore

**Comment by Dinesh-MSFT** [comment]
Hi @Aspyryan - Thanks for raising the query.
We will look into it and let you know the updates.

**Comment by Aspyryan** [comment]
Hi @Dinesh-MSFT, any progress on this?

**Comment by Aspyryan** [comment]
Can you help me find what the sample issue is and tell me what I should change? It's a business application so quite critical! @ChetanSharma-msft

**Comment by ChetanSharma-msft** [comment]
Hello @Prithvi-MSFT, @Pawank-MSFT - Kindly check and share the updates on this issue.

**Comment by Mohammed-MSFT** [comment]
Hi @Aspyryan 

**Thanks for raising your query !!**

As per your query, I have tested the sample bot team authentication, which is working fine on both desktop and web.

**Desktop Client Version**
<img width="461" alt="clientVer" src="https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/109147706/c95ed594-6cff-44f5-bb62-6557b4714f29">


<img width="959" alt="Desktop" src="https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/109147706/e094eebb-0b60-4e13-b13b-79fcf2cbe762">

and I couldn't see any error on this method.
<img width="662" alt="image" src="https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/109147706/223a4e73-7c08-434f-be59-58b124a1464f">


**Web View**
<img width="956" alt="Web" src="https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/109147706/23054a28-c2e7-4788-ba3a-0d100068be56">

Kindly recheck your configuration once.

Sample Link :  https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-teams-authentication/csharp

**Thanks !!**
