### ISSUE TITLE
Can't get into the Connectors Portal

### ISSUE THREAD

**Issue by SnirShechter** [OfficeDev/Microsoft-Teams-Samples#124]
It immediately redirects me to an error page, and the "send feedback" button there (which I barely managed to click) has an error too...

![image](https://user-images.githubusercontent.com/26040325/127482738-cfbafc1c-b9e8-4af1-ac2b-d343ed19356c.png)

```
Something went wrong.
Mailbox address missing in URL
RequestId: ad9c2c60-cdc5-cca4-bcf9-95b4f10b2991
Server: AS8PR09MB5159
Date: 2021-07-29 14:04:37 +0300
```

I've developed a connector for my company's product and submitted it to the App Store. I did not get a response for over two weeks, could this also be related?

**Comment by Wajeed-msft** [comment]
@SnirShechter - could you please try this link https://aka.ms/connectorsdashboard?
