### ISSUE TITLE
bot-teams-authentication for user assigned managed identity bot

### ISSUE THREAD

**Issue by emahama** [OfficeDev/Microsoft-Teams-Samples#1245]
I am trying to reproduce the example in bot-teams-authentication example. However, I want to use azure bot with user assigned managed identity bot. 

The challenge I am facing is adding OAuth Connection Settings to the bot. From the snapshot below, it is observed that Client secret is a mandatory field. However, azure bot with user managed identity does not use secret. 

I created an application principal in Entra ID and I used it to populate the OAuth2Connection but I am trying to move away of secrets. That is why I decided to use the user assigned managed identity. Is there a way to add OAuth Connection setting without having to created principal in Entra ID that uses secret?

Can you provide some guidance on adding OAuth connection for user assigned managed identity bot? Thank you. 

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/95234948/00736798-d69a-4f3a-b794-1e02d8cfe503)

**Comment by Prasad-MSFT** [comment]
Hi @emahama - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
@emahama - We are checking this with engineering team whether or not there is way to add OAuth Connection setting without having to create principal in Entra ID that uses secret, and we will inform you once we hear from them.

Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @emahama, according to latest update from engineering team, OAuth doesn't support MSI
