### ISSUE TITLE
Sample 'Sequential Flow with Adaptive Cards' (C#) not working in Teams Channel but in Group Chat

### ISSUE THREAD

**Issue by Jan1503** [OfficeDev/Microsoft-Teams-Samples#1246]
Hi there!

The provided sample [bot-sequential-flow-adaptive-cards](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-sequential-flow-adaptive-cards/csharp) does not work correctly when added to a Teams Channel. It works when added to a group chat.

In a channel, the messages are sometimes not delivered to my web-app (Azure Windows App-Service). I've also added another bot with the "bot-request-approval" sample to a channel (after modifying its manifest) and it also does not work.

Sometimes it sends the first message, sometimes it doesn't. It also looks like the "refresh" (Refresh-Model for Adaptive Cards) for different users is not called in a Teams Channel.
In a group chat all is working as expected.

I'm sorry that I don't have a better explaination or any logs. Please tell me what you need to investigate this issue.

Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @Jan1503 - We tested this sample from our side and also observed the same behaviour.
This doesn't work in teams channel scope. However, it works in group chat scope. Seems like card is not getting refreshed in team's channel scope.
 
**Team's channel:**
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/04063402-b89c-4b1e-9a71-838bb33d9068)

**Group chat:**
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/c2fcbf58-7689-48ab-81b9-c7018d2b9e21)

**Comment by Jan1503** [comment]
I just tested this in classic Teams and initially got better results but some refreshs are also missing.

I think the code is ok and it's a Teams (v2) issue.

Even a completely new bot created with the Teams toolkit shows the same behaviour.
The refresh-model seems to break if used in a Teams channel.

**Comment by Jan1503** [comment]
Another small update:
I opened Teams v2 in webclient with User B and submit an approval request from User A using Teams desktop client (classic or v2 doesn't matter).

User B does not receive the updated card in v2 webclient.
As soon as I switch webclient to classic, adaptive card get's updated correctly.

If I then switch back to v2, same old adaptive card is shown. Very weird.

So its working in classic Teams but not in v2.

**Comment by Jan1503** [comment]
Found this with no answer:
[adaptive card is not getting updated in new team client](https://techcommunity.microsoft.com/t5/teams-developer/adaptive-card-is-not-getting-updated-in-new-team-client/m-p/3966875)

**Comment by Prasad-MSFT** [comment]
Hi @Jan1503 - We have raised a bug for the same. We will inform you once we get any further update from engineering team. 

Thanks!

**Comment by Prasad-MSFT** [comment]
@Jan1503, this bug seems to be fixed. We tested with Microsoft Teams version 24346.1300.3302.2562 (The client version is 49/24121716400) and this is no longer reproable.
