### ISSUE TITLE
/api/notify endpoint not working in graph-proactive-installation

### ISSUE THREAD

**Issue by joarobles** [OfficeDev/Microsoft-Teams-Samples#125]
Calling **GET** `/api/notify` would show "Proactive messages have been sent." but `conversationReferences` holds only one value when the team has 16 members.

Sending the message by a text "Send messages" tagging the bot would send all 16 messages.

**Comment by Wajeed-msft** [comment]
@joarobles - `/api/notify` sends notification to only existing references present in conversationReferences array. You can update the code sample to install the app and send notification in `/api/notify` as well.
