### ISSUE TITLE
 Unable to Grant Permissions to Asset Management 365 Application in Microsoft Teams Permission Section

### ISSUE THREAD

**Issue by DeepeshCubic** [OfficeDev/Microsoft-Teams-Samples#1259]
I'm encountering a critical issue where I'm unable to grant permissions to the Asset Management 365 application within the permission section of Microsoft Teams. Additionally, I've noticed that the Asset Management 365 application is not visible in the permission section on Teams, further complicating the configuration process.

1.Access the permission settings of Microsoft Teams.
2.Navigate to the section for managing application permissions.
3.Search for the Asset Management 365 application in the list of available applications.
4.Observe that the Asset Management 365 application is not visible in the permission section.

{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.schema.json",
  "manifestVersion": "1.9",
  "packageName": "Asset Management 365",
  "id": "#######################",
  "developer": {
    "name": "HR365",
    "websiteUrl": "https://www.hr365.us",
    "privacyUrl": "https://www.hr365.us/privacy/",
    "termsOfUseUrl": "https://www.hr365.us/end-user-license-agreement-eula/",
    "mpnId": "4552499"
  },
  "name": {
    "short": "Asset Management 365",
    "full": ""
  },
  "devicePermissions":[
    "media"
  ],
  "description": {
    "short": "Asset Management 365",
    "full": "Asset Management 365"
  },
  "version": "24.0510.1848.0000",
  "icons": {
    "outline": "################outline.png",
    "color": "##################color.png"
  },
  "accentColor": "#FFFFFF",
  "configurableTabs": [
    {
      "configurationUrl": "https://{teamSiteDomain}{teamSitePath}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest={teamSitePath}/_layouts/15/teamshostedapp.aspx%3FopenPropertyPane=true%26teams%26componentId=###################forceLocale={locale}",
      "canUpdateConfiguration": true,
      "scopes": [
        "team"
      ]
    }
  ],
  "staticTabs": [
    {
      "entityId": "com.clsppdev.edp.sphttp",
      "name": "AMM",
      "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=##################################forceLocale={locale}",
      "scopes": [
        "personal"
      ]
    }
  ],
  "validDomains": [
    "*.login.microsoftonline.com",
    "*.sharepoint.com",
    "*.sharepoint-df.com",
    "spoppe-a.akamaihd.net",
    "spoprod-a.akamaihd.net",
    "resourceseng.blob.core.windows.net",
    "msft.spoppe.com"
  ],
  "webApplicationInfo": {
    "resource": "https://{teamSiteDomain}",
    "id": "#####################"
  }
}

**Comment by Prasad-MSFT** [comment]
Hi @DeepeshCubic - Is this a custom app? We searched this app in Teams app store but could not find it.
Could you please provide more details on your issue? Which permissions are you trying to grant here?
Are you talking about this permission tab?
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/f9b3fcef-fc51-4618-8506-ba57ac48c3bf)

**Comment by DeepeshCubic** [comment]
![Screenshot_2](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/162090980/fb78f64d-0b33-4d9f-a4af-39a17dc89f54)
I want these toggle permission in my application but my application is not rendering in this permissions section.

**Comment by Prasad-MSFT** [comment]
@DeepeshCubic - From the manifest json shared i can see your app's manifest.json has been updated by adding devicePermissions and specifying which propertie that you use in your application as per this [document](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop%2Cteamsjs-v2%2Cmobile1#specify-permissions). 
Please verify if you have configured all the settings and permissions as per this document (https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/media-capabilities?tabs=mobile)? 

Also, are you using New Teams? The Media API isn't supported in the [new Teams client](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates). 
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/media-capabilities?tabs=mobile#media-capability-apis

**Comment by DeepeshCubic** [comment]
Yes, i'm using New Teams but in one Tenant it is working fine and in other its not , will tell me the solution and what should i used for new Teams

**Comment by Prasad-MSFT** [comment]
Since the application works fine in one tenant but not in another, verify if there are any differences in the configuration or permissions settings between the two tenants that could be causing the issue.
