### ISSUE TITLE
teams calling-meeting bot not working, failed to determine https port for redirect

### ISSUE THREAD

**Issue by pravarkulbh** [OfficeDev/Microsoft-Teams-Samples#1279]
Hi, I am following this document- https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-bot-calling-meeting-csharp/ - have followed everything step by step, but the bot doesn't seem to respond and the error is not clear.

I am using devtunnel as mentioned in the document and here is a screenshot attached for what I think can be the error:
![devtunnel_redirect_error](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/60579436/458be905-94f2-4bf4-a445-c3365a5b7e07)

My bot is up and running according to the tab opening at localhost:3978:
![web3978](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/60579436/9cd7a4d3-c625-44ce-a74c-f103d492122d)
But my console is showing this:
![vserror](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/60579436/dd4c85c6-f7b6-4a4d-9e2f-cf2c810b5e96)
I don't know whether this is an error, but this is the only thing showing up on the output window.

Also attaching how my teams window looks like when I send the message: 
![teams](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/60579436/a3b2a957-a67d-4361-bb7b-211c3922c09b)

Edited: The devtunnel is connected, as mentioned in the link above, but its rerouting a different localhost port, can it be the issue?
![devtunnel](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/60579436/3cdd1b1c-e510-4737-9685-3c8556e567dc)

Any help would really be appreciated.

Thanks.

**Comment by Prasad-MSFT** [comment]
@pravarkulbh - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
@pravarkulbh - As you mentioned, `the devtunnel is connected, as mentioned in the link above, but its rerouting a different localhost port`. That seems to be the issue. Please make sure your app is running in the same port as your devtunnel
