### ISSUE TITLE
People picker control in Adaptive Cards: How to retrieve user properties with Entra ID 

### ISSUE THREAD

**Issue by runr02** [OfficeDev/Microsoft-Teams-Samples#1282]
I'm following the project samples/bot-people-picker-adaptive-card/csharp however it's not clear how to retrieve user properties after submission of people picker. How do we retrieve the user email, for example, using the entra id to send emails to the selected users? Do we use microsoft graph, if so what kind of connection auth is required, if any.

**Comment by Nivedipa-MSFT** [comment]
@runr02 - Could you please confirm is your issue resolved or are you still facing any further issue here?

**Comment by runr02** [comment]
Yes

**Comment by Nivedipa-MSFT** [comment]
@runr02 - Thanks for your confirmation. Could you please share your valuable feedback via
[Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)
link?
