### ISSUE TITLE
People Picker Adaptive Card: Authentication and Api Usage 

### ISSUE THREAD

**Issue by runr02** [OfficeDev/Microsoft-Teams-Samples#1286]
I'm following the project samples/bot-people-picker-adaptive-card-csharp. The people picker adaptive card is using: graph.microsoft.com/users. I would like to know if I can use another graph api (i.e., organization graph provider), to grab users. Are there any methods to authenticate via the adaptive card? Running into cross environment issues during testing (i.e., graph.microsoft.com/users returns teams prod entra id, but we need it to return qa entra id).

**Comment by Meghana-MSFT** [comment]
@runr02 - Thank you for reporting this, we will check this and get back to you.

**Comment by runr02** [comment]
Resolve by using the appropriate tenant.
