### ISSUE TITLE
Bot/Message Extension App created using Teams Toolkit in private/shared channels

### ISSUE THREAD

**Issue by rohannaik29** [OfficeDev/Microsoft-Teams-Samples#1287]
I have created a Teams Bot/Message Extension App using Teams Toolkit using VS Code. It is working properly in standard channels. I want to install it in shared/private channel.

I have added below into the manifest file. Still not able to install in the shared/private channel

```
"supportedChannelTypes": [
     "sharedChannels", 
      "privateChannels" 
    ]
```

**Comment by Meghana-MSFT** [comment]
Hi @rohannaik29 - Please note that the support for apps in private and shared channels is not yet released to external developers. Engineering team is working on updating the documentation to mention the same.

**Comment by demian-licht-hs** [comment]
@Meghana-MSFT is there any update on this? Any tracker we can follow? This is a core functionality we're working to integrate in our systems.

**Comment by Meghana-MSFT** [comment]
Unfortunately, we do not have any tracker/ETA to share regarding above ask. You can get latest Teams platform updates by subscribing to the [RSS feed What's new - Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new)
