### ISSUE TITLE
Bot-file-upload Java sends empty file

### ISSUE THREAD

**Issue by ishaan-sprinklr** [OfficeDev/Microsoft-Teams-Samples#1296]
I cloned the repo and ran the sample with `mvn install` and `java -jar ./target/name.jar`, after setting `application.properties`.
But the file sent is always an empty file, `0 B`, I tried debugging myself but no leads.

**Comment by Prasad-MSFT** [comment]
@ishaan-sprinklr - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
The issue is fixed, and latest changes has been merged. https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-file-upload/java

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
