### ISSUE TITLE
Send proactive message without saving Conversation reference

### ISSUE THREAD

**Issue by tracyboehrer** [OfficeDev/Microsoft-Teams-Samples#1298]
Sample request for: https://github.com/microsoft/botbuilder-python/issues/1934

**Comment by Nivedipa-MSFT** [comment]
@tracyboehrer - Thanks for reporting your issue. We will check this and update you soon.

**Comment by Shashank22082002** [comment]
Can we create/generate turn context object somehow from using ids of post/message?

**Comment by ChetanSharma-msft** [comment]
> Can we create/generate turn context object somehow from using ids of post/message?

If you want to send proactive messages later, you need to use BotAdaptor only:
// Sends a proactive message from the bot to a conversation.
            await ((BotAdapter)_adapter).ContinueConversationAsync(_appId, newReference, BotCallback, default(CancellationToken));
            
Please refer this documentation:
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#samples
