### ISSUE TITLE
Two chat windows are getting created for MS Teams Bot when installing the bot for the first time.

### ISSUE THREAD

**Issue by sapnaavya** [OfficeDev/Microsoft-Teams-Samples#1304]
When user clicks on add button on the app to install the bot under Built for your org tab, it creates two chat windows in the recent section in MS Teams for that Bot. In those recent chats, one chat window stays in the draft mode, and disappears after some time or when we click on that draft chat.  Is this expected behavior?

**Comment by sapnaavya** [comment]
we are seeing this issue only for our bot. When user tries to install the bot, we send thank you message and authenticate the user by using SSO. We followed the steps to enable SSO on this page: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-overview and when user signs in successfully, we send other messages. However, in this process, sometime, we have seen our bot is creating two chats window and one chat remain in draft mode and it goes away in some time or unless we click on it.

**Comment by Meghana-MSFT** [comment]
We checked this at our end, and we are not able to repro this issue. Could you please share the deployed manifest with us so that we can check if we have a local repro. Please share manifest at microsoftteamsdev@microsoft.com.
