### ISSUE TITLE
Calling Bot Sample

### ISSUE THREAD

**Issue by AshokButra** [OfficeDev/Microsoft-Teams-Samples#1305]
Working on calling bot sample where i faced an issue with Record timing. Here i want to record the meeting or any call where bot joined should record whole call upto call ends then later on i want to run record functionalities for downloading record. As Inbuilt code is set with certain time limit i wanted to move this to null, Like recording should be done upto call/meeting ends.

please follow up the below code 

(https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-calling-meeting/csharp/Source
/CallingBotSample)

**Comment by Nivedipa-MSFT** [comment]
@AshokButra - Thanks for reporting your issue. We are checking this internally, we will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@AshokButra - Could you please provide more information about your issue to investigate further?
