### ISSUE TITLE
meetings-transcription sample can't be worked

### ISSUE THREAD

**Issue by masamori0083** [OfficeDev/Microsoft-Teams-Samples#1324]
Hello Team,

I followed this [steps ](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-transcription/nodejs)to deploy the app using ngrok but it did not work as expected. I only get this page.

I have a question: I couldn't find the {{Microsoft-App-Id}} in the manifest in Step 6. Also, what values should I enter for ${{TEAMS_APP_ID}} and ${{AAD_APP_CLIENT_ID}}? So far, I have used the Application Id created in Step 1.

The environment is:

Node.js 20.12.2
ngrok

Thank you.

![Screenshot 2024-07-09 at 22 33 40](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/60207264/b38074cb-aa12-47ed-8b29-2e17c27f9f1a)
![Screenshot 2024-07-09 at 22 33 58](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/60207264/91bd9ae0-5eb8-4d29-988f-e63596f573b2)
![Screenshot 2024-07-09 at 22 34 16](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/60207264/e96932aa-2fb8-4467-abd0-c0d19a69240b)

**Comment by masamori0083** [comment]
Hi teams sorry, I was able to solve the problem I mentioned earlier.
It seems that a bot cannot be deployed to a meeting that has already ended.
Is this behavior correct?

Currently, I can assign the bot to a meeting, and it is not working at all.
I can't even view the logs, so I'm not sure what's wrong.
I would appreciate it if you could help me understand what's going wrong.
![Screenshot 2024-07-10 at 12 16 37](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/60207264/15f40f06-b363-49c6-999e-7c8c46b350ea)

**Comment by Nivedipa-MSFT** [comment]
@masamori0083 - Thanks for reporting your issue. We will test meetings-transcription sample and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@masamori0083 - Could you please verify your TEAMS_APP_ID, AAD_APP_CLIENT_ID and test again?

**Comment by masamori0083** [comment]
@Nivedipa-MSFT 
Hi, just while ago, I verified those env value, and then the app can work now.
Thanks your contribution!

**Comment by Nivedipa-MSFT** [comment]
@masamori0083 - Glad to hear that your issue is resolved. Could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback ](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)link?

**Comment by Nivedipa-MSFT** [comment]
@masamori0083 - We are closing this issue for now. Please feel free to reopen if required.
