### ISSUE TITLE
How to Implement OAuth for a Bot-Based Message Extension App in Microsoft Teams for Graph API?

### ISSUE THREAD

**Issue by purvasanap2001** [OfficeDev/Microsoft-Teams-Samples#1333]
I have created a bot-based message extension app using the Teams Toolkit and need to call the Microsoft Graph API, which requires OAuth implementation. So far, I have created the app in the Teams Developer Portal, registered the app in Azure App registration, and registered the bot in the Bot Framework Developer Portal (dev.botframework.com). However, I am unclear about the OAuth flow and the specific configurations required.

Can someone provide a detailed guide on how the OAuth flow works for a bot-based message extension in Microsoft Teams, the specific configurations needed in the Azure app registration, how to configure permissions and consent for accessing the Microsoft Graph API, and any additional settings required in the Teams Developer Portal or Bot Framework Developer Portal?

Any guidance, code examples, or references to detailed documentation would be highly beneficial.

**Comment by Dinesh-MSFT** [comment]
Hi @purvasanap2001 - Thanks for raising the query.
We will look into it and let you know the updates.
