### ISSUE TITLE
Call status terminated , Error 500#3002 Internal server error

### ISSUE THREAD

**Issue by abhi161** [OfficeDev/Microsoft-Teams-Samples#1339]
I'm having a weird issue where my bot was working perfectly fine, and then suddenly started throwing an error. I haven't changed any settings or code, so I'm completely baffled.

Call status updated to Terminated - Server Internal Error. DiagCode: 500#3002.@"
Its getting established then terminated
Is this a bug, or is there something else going on? Any help would be greatly appreciated!

**Comment by sayali-MSFT** [comment]
Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by abhi161** [comment]
Thank you for prompt response to give more context PFA logs below-

>2024-07-23T10:28:11.5271091Z Info: NotificationQueue.cs:278 StartLoopAsync
ScenarioId: 1710d8a0-f2b3-471c-8c64-adcbd9e1cf34
AppId: ed5db92e-18fc-4f1a-bbdc-453af8ad0c74
AppName: PsiBot.Service
Notification queue communications/calls/2a004980-7314-43b5-b2d9-eb6329a99e6f is stopped.
$>2024-07-23T10:28:11.0162513Z Info: CallHandler.cs:163 CallOnUpdated
ScenarioId: 1710d8a0-f2b3-471c-8c64-adcbd9e1cf34
CallId: 2a004980-7314-43b5-b2d9-eb6329a99e6f
TenantId: 242e6438-4f4b-4645-9dfa-68c4590821c6
AppId: ed5db92e-18fc-4f1a-bbdc-453af8ad0c74
AppName: PsiBot.Service
Call status updated to Terminated - Server Internal Error. DiagCode: 500#3002.@
$>2024-07-23T10:28:11.0053690Z Info: CallHandler.cs:163 CallOnUpdated
ScenarioId: 1710d8a0-f2b3-471c-8c64-adcbd9e1cf34
CallId: 2a004980-7314-43b5-b2d9-eb6329a99e6f
TenantId: 242e6438-4f4b-4645-9dfa-68c4590821c6
AppId: ed5db92e-18fc-4f1a-bbdc-453af8ad0c74
AppName: PsiBot.Service
Call status updated to Establishing -
$>2024-07-23T10:28:10.8402137Z Info: BotService.cs:166 JoinCallAsync
ScenarioId: 1710d8a0-f2b3-471c-8c64-adcbd9e1cf34
CallId: 2a004980-7314-43b5-b2d9-eb6329a99e6f
TenantId: 242e6438-4f4b-4645-9dfa-68c4590821c6
AppId: ed5db92e-18fc-4f1a-bbdc-453af8ad0c74
AppName: PsiBot.Service
Call creation complete: 2a004980-7314-43b5-b2d9-eb6329a99e6f
$>2024-07-23T10:28:10.8402137Z Info: NotificationDispatcher.cs:229 Subscribe
AppId: ed5db92e-18fc-4f1a-bbdc-453af8ad0c74
AppName: PsiBot.Service

**Comment by sayali-MSFT** [comment]
Thank you for the immediate response, We will check this with our internal team and let you know the update.

**Comment by abhi161** [comment]
working fine now thanks for support
