### ISSUE TITLE
CallingBotSample System.InvalidOperationException

### ISSUE THREAD

**Issue by ClauVeve** [OfficeDev/Microsoft-Teams-Samples#136]
Hello,
I've tried running the Calling Bot Sample, but every time I start debugging I get the following error: System.InvalidOperationException: 'Failed to convert configuration value at 'Bot:BotBaseUrl' to type 'System.Uri'.'
Inner Exception UriFormatException: Invalid URI: The hostname could not be parsed.

**Comment by Wajeed-msft** [comment]
@ClauVeve - could you please confirm if you have added valid URL for BotBaseUrl? 
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-calling-meeting/csharp/appsettings.json

![image](https://user-images.githubusercontent.com/31851992/129761802-c63a5163-4a60-4ce5-a66c-48525ee8f342.png)

**Comment by ChetanSharma-msft** [comment]
Hello @ClauVeve - Hope you are doing well!!
Could you please confirm if your issue has resolved or still looking for any help?
