### ISSUE TITLE
Assistance Needed: Fetching Phone Numbers via Microsoft Graph API for Teams Marketplace App

### ISSUE THREAD

**Issue by santhosh-oapps** [OfficeDev/Microsoft-Teams-Samples#1370]
Hi,

I am developing an app for the Microsoft Teams marketplace and need to retrieve the phone numbers purchased by users who install our app. After searching, I couldn't find a specific Graph API endpoint that provides this information.

I did come across a PowerShell command that retrieves phone numbers, but it looks like I cannot use them on behalf of the user who installs my app. 

Could someone assist with this? Any guidance would be greatly appreciated. Please let me know, if this query needs to be moved to a different place. 

Thank you!

**Comment by sayali-MSFT** [comment]
@santhosh-oapps -
Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@santhosh-oapps -Retrieving phone numbers associated with Microsoft Teams via the Microsoft Graph API can be a bit complex, especially when it comes to integrating such functionality into your app in the Microsoft Teams marketplace.

Microsoft Graph API provides a wide range of capabilities for accessing and managing Microsoft 365 data.  there isn't a specific endpoint for retrieving phone numbers directly associated with Teams users. Microsoft Graph API focuses on broader user management and communication features.

While you might not find a direct endpoint for phone numbers, you can retrieve user details using the Microsoft Graph API. For example, you can use the /users endpoint to get user profiles, though phone numbers may not be directly included.

`GET https://graph.microsoft.com/v1.0/users/{id}`

Note: This may not include phone numbers if they're managed separately in Teams or other services.
