### ISSUE TITLE
Is the webapplicationinfo key in the App Manifest required for NAA?

### ISSUE THREAD

**Issue by carlgrzywacz** [OfficeDev/Microsoft-Teams-Samples#1383]
I noticed the Sample project does not include the [WebApplicationInfo ](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#webapplicationinfo)key in the Teams App Manifest.  Is this no longer required when using NAA for Teams Apps?

**Comment by Wajeed-msft** [comment]
@Harikrishnan-MSFT - could you please help here?

**Comment by Harikrishnan-MSFT** [comment]
@carlgrzywacz      [WebApplicationInfo](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#webapplicationinfo) key is not required when using NAA for Teams apps

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
