### ISSUE TITLE
does sample support in Gallatin cloud?

### ISSUE THREAD

**Issue by swiftPeter** [OfficeDev/Microsoft-Teams-Samples#1389]
For the samples/tab-ui-templates/ts, I tried to upload in Gallatin cloud, it shows as blank page.

Capture the HAR, I got the error code:

![image](https://github.com/user-attachments/assets/3f20beca-a66d-44e6-bdc2-cbcab0197748)

{
    "error": "invalid_resource",
    "error_description": "AADSTS500011: The resource principal named
https://outlook.office.com/
was not found in the tenant named Test_Test_apgcTeams. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 2b050f10-e13b-4d31-9cf2-e4a116ce0c00 Correlation ID: 79052faa-1247-40d3-980f-776b21cd5a7e Timestamp: 2024-09-11 08:14:36Z",
    "error_codes": [
        500011
    ],
    "timestamp": "2024-09-11 08:14:36Z",
    "trace_id": "2b050f10-e13b-4d31-9cf2-e4a116ce0c00",
    "correlation_id": "79052faa-1247-40d3-980f-776b21cd5a7e",
    "error_uri": "
[https://login.partner.microsoftonline.cn/error?code=500011"](https://login.partner.microsoftonline.cn/error?code=500011%22)
}

there is no issue when I deploy the sample to Global cloud, my question is "does sample support in Gallatin cloud"?

**Comment by Prasad-MSFT** [comment]
Hi @swiftPeter, Cross-cloud communication via SDK is not allowed due to security reasons, therefore Teams Gallatin domain is not added to the validOrigins. If an app wants to work in Gallatin, it needs to explicitly specify the Gallatin domain when initializing the SDK in the Gallatin deployment of their apps (using the validMessageOrigins parameter): https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app?view=msteams-client-js-latest#@microsoft-teams-js-app-initialize

That would look something like this:
```
import { app } from '@microsoft/teams-js';
app.initialize(["https://teams.microsoftonline.cn"]);
```

**Comment by Prasad-MSFT** [comment]
Sure @swiftPeter, we will add this info in the sample. Apologies, but currently there is no plan regarding this. We recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).


Also, could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link?

**Comment by Prasad-MSFT** [comment]
Doc update request: https://github.com/MicrosoftDocs/msteams-docs/issues/11505

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
