### ISSUE TITLE
Alternative for DelegateAuthenticationProvider class in C# .NET Tab sample

### ISSUE THREAD

**Issue by pankajmunde12** [OfficeDev/Microsoft-Teams-Samples#1390]
Hi Team,
I was testing tab-request-approval sample on my machine (https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-request-approval).
While creating a similar application I got the message that DelegateAuthenticationProvider  class is deprecated and no longer supported. So could you please provide some alternative solution for this class.
At many places it's suggested to use OnBehalfOfCredential, but it would be helpful to know how to use it in this specific sample.

Thanks and Regards,
Pankaj Munde

**Comment by sayali-MSFT** [comment]
@pankajmunde12 - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@pankajmunde12- By replacing DelegateAuthenticationProvider with OnBehalfOfCredential, you can handle authentication in a modern and supported way.
Please have look into this document-
1. https://learn.microsoft.com/en-us/javascript/api/%40azure/identity/onbehalfofcredential?view=azure-node-latest
2. https://learn.microsoft.com/en-us/dotnet/api/azure.identity.onbehalfofcredential?view=azure-dotnet

**Comment by pankajmunde12** [comment]
> @pankajmunde12- By replacing DelegateAuthenticationProvider with OnBehalfOfCredential, you can handle authentication in a modern and supported way. Please have look into this document-
> 
> 1. https://learn.microsoft.com/en-us/javascript/api/%40azure/identity/onbehalfofcredential?view=azure-node-latest
> 2. https://learn.microsoft.com/en-us/dotnet/api/azure.identity.onbehalfofcredential?view=azure-dotnet

Thanks @sayali-MSFT!
This is helpful! I will check and try to implement the same.

**Comment by pankajmunde12** [comment]
Thanks @sayali-MSFT!
This info is helpful and answers my query.
This issue can now be closed.
