### ISSUE TITLE
Deep link generated by a tab not working (C#)

### ISSUE THREAD

**Issue by pankajmunde12** [OfficeDev/Microsoft-Teams-Samples#1399]
Hi Team,
I am testing tab-request-approval sample (C#). When a tab sends an activity notification, the recipient user gets the message in activity section of the MS Teams. When the user clicks on the notification, following message is being displayed: This app cannot be found.
Please see the below screenshot for more details. Could you please check this and see if there is any error in generating the deep-link?

Kind regards,
Pankaj Munde

![tab-request-approval-error](https://github.com/user-attachments/assets/d90e327d-7446-49d2-97b2-3579d6d0741e)

**Comment by Prasad-MSFT** [comment]
Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
Hi @pankajmunde12, the app should be installed for user's manager also to get task approval notification. Could you please verify that?

**Comment by pankajmunde12** [comment]
Hi @Prasad-MSFT 
Thanks for your suggestion.
But I figured out that it was a problem with deep-link creation logic.
I have created a pull request for it. Could you please check it once?
https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1402

Thanks,
Pankaj
