### ISSUE TITLE
Using latest Graph API nuget package in tab-request-approval C# sample

### ISSUE THREAD

**Issue by pankajmunde12** [OfficeDev/Microsoft-Teams-Samples#1407]
Hi Team,
I see the sample C# app, tab-request-approval uses the preview (beta) version of the Microsoft.Graph nuget package. 
1. Is there any specific reason why the app still uses the beta version?
2. Could you please provide the guidelines on using the latest Graph API nuget package? I have created one PR (https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1406) for the latest Graph API nuget package version, but not sure if any additional coding or usage guidelines I need to follow.

Thanks and Regards,
Pankaj

**Comment by Prasad-MSFT** [comment]
Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
The PR has been merged. We are closing this issue for now. Please feel free to reopen if required. Thanks!
