### ISSUE TITLE
Build tabs with Adaptive Cards - Can't build bot

### ISSUE THREAD

**Issue by t-lji** [OfficeDev/Microsoft-Teams-Samples#145]
In readme.md, I can't find where the BaseUrl and ConnectionName are. May the tutorial is outdated. Please help me, thanks.

Update the .env configuration for the bot to use the MicrosoftAppId (Microsoft App Id) and MicrosoftAppPassword (App Password) from the Bot Framework registration. Also update BaseUrl according to your code runtime environment and ConnectionName with Bot Channel Registration connection name.

**Comment by AbhijeetThakur-msft** [comment]
Hello, 
The **BaseUrl** mentioned in the readme is your application url. 
For ex, If you are using tunnelling service like ngrok then it will be https://6df9-223-181-129-XX.ngrok.io.

The **ConnectionName** referred is the name that we provide while **Adding OAuth connection setting** in the Bot channel registration. 
Please follow this link [Add authentication to your bot](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample) to see how we can add the setting.

We will also update accordingly in the readme files as well.

**Comment by t-lji** [comment]
Thanks for your quickly apply. I will try it soon.
