### ISSUE TITLE
Stage view cannot be pinned as a tab

### ISSUE THREAD

**Issue by i066088** [OfficeDev/Microsoft-Teams-Samples#146]
I have followed the steps in the following document to run a teams app.
[https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-stage-view/nodejs
](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-stage-view/nodejs
)
When I click the **View via Card button**, 
![image](https://user-images.githubusercontent.com/40688635/132457812-899df99b-d5b6-4a22-b148-d431129aa336.png)

the stage view is displayed as below:
![image](https://user-images.githubusercontent.com/40688635/132457867-b0ea3f63-40ac-4966-9987-c9debb10a398.png)

But I cannot find there is a way to pin this view as a tab.
And the screenshot of stage view is different with your readme:
[https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-stage-view/nodejs#readme
](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-stage-view/nodejs#readme
)
![image](https://user-images.githubusercontent.com/40688635/132458361-d527b2ec-8d8f-4476-baf1-b35ed0c2616c.png)

Could you please have a look? thanks a lot.

**Comment by i066088** [comment]
@washaik@microsoft.com
could u help? thanks

**Comment by Wajeed-msft** [comment]
@AbhijeetThakur-msft - could you please check this?

**Comment by AbhijeetThakur-msft** [comment]
Hi @i066088, we are checking this at our end. Also we'll work to make the screenshots consistent. Thanks!

**Comment by AbhijeetThakur-msft** [comment]
Hi @i066088, we have raised the issue with our team as we were also not getting the pin icon. Will update the content based on the findings we get. Thanls!

**Comment by tinsheep** [comment]
@Wajeed-msft @AbhijeetThakur-msft  How was this resolved? I'm still not able to pin the Stage View - thanks!
