### ISSUE TITLE
Send proactive DM using javascript

### ISSUE THREAD

**Issue by yashgandhi-32** [OfficeDev/Microsoft-Teams-Samples#1460]
I am trying to send a proactive direct message (DM) in Microsoft Teams using the following ConversationParameters reference:
```


{
  isGroup: false,
  bot: {
    id: data.bot.id,
    name: data.bot.name,
  },
  channelData: {
    tenant: {
      id: tenantId,
    },
  },
  members: [
    {
      id: conversationId,
    },
  ],
} as ConversationParameters;
```
And then calling continueConversationAsync like this:

```
await this.cloudAdapterService.continueConversationAsync(
  appId,
  ref,
  async (context) => {
    await context.sendActivity({ attachments: [data.attachment] });
  },
);
```
However, this approach is failing. Can you guide me on how to properly send a proactive DM to a user without having an existing context, given that I have the userAadObjectId and userId (29:...) stored?

**Comment by yashgandhi-32** [comment]
@Nivedipa-MSFT Thanks
this `id: userId,` and `id: conversationId,` are same , that starts from `29:xxxx` ?

**Comment by yashgandhi-32** [comment]
@Nivedipa-MSFT ?? still waiting its been a week on this query could you help me resolve it

**Comment by Nivedipa-MSFT** [comment]
@yashgandhi-32 - To send a proactive message to a user when the app is added in personal scope or to all users in a team when the app is added in channel, follow these steps:
[Get the Microsoft Entra user ID, user ID, team ID, or channel ID](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fplatform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages%3Ftabs%3Ddotnet%23get-the-user-aad-id-user-id-team-id-or-channel-id&data=05%7C02%7Cv-nivedipasu%40microsoft.com%7C661976167ec44309186e08dd0fb0cec0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638683974478677473%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=wPXrBZ3JjNJACBGbVYLTbIUyfnt%2FpkSaeZ1lxZo9c6M%3D&reserved=0), if necessary.
[Create the conversation](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fplatform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages%3Ftabs%3Ddotnet%23create-the-conversation&data=05%7C02%7Cv-nivedipasu%40microsoft.com%7C661976167ec44309186e08dd0fb0cec0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638683974478693851%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=IdRP301rVt7aqRV0mlklSlvKWYDpxcRwMWfRV9PjiRE%3D&reserved=0), if necessary.
[Get the conversation ID](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fplatform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages%3Ftabs%3Ddotnet%23get-the-conversation-id&data=05%7C02%7Cv-nivedipasu%40microsoft.com%7C661976167ec44309186e08dd0fb0cec0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638683974478708003%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=RVCMGyXU0mvusV917EZ8DUyWuoHVDYT79KRVeXt%2FMKs%3D&reserved=0).
[Send the message](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fplatform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages%3Ftabs%3Ddotnet%23send-the-message&data=05%7C02%7Cv-nivedipasu%40microsoft.com%7C661976167ec44309186e08dd0fb0cec0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638683974478721896%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=Bxgn59mwG3RGN6UvKS12v5uogSTqnx6goO0o6y5%2Bwf8%3D&reserved=0).

Please refer to the following sample, which demonstrates how to send a welcome message upon the installation of a bot: [Microsoft-Teams-Samples/samples/bot-conversation/csharp at main · OfficeDev/Microsoft-Teams-Samples](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2FMicrosoft-Teams-Samples%2Ftree%2Fmain%2Fsamples%2Fbot-conversation%2Fcsharp&data=05%7C02%7Cv-nivedipasu%40microsoft.com%7C661976167ec44309186e08dd0fb0cec0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638683974478735457%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=O6eeDQW18vZDoP6ekSTrH1vaMtY5S53wah%2Bm3v2YeRU%3D&reserved=0)

Ref Doc: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet

Please let us know if you are facing any further query here?

**Comment by yashgandhi-32** [comment]
@Nivedipa-MSFT ?? Pls update

**Comment by Nivedipa-MSFT** [comment]
@yashgandhi-32 - Apologies for the delay. We are checking this internally, we will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@yashgandhi-32 - If the above information was helpful to you, could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback ](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)link?

**Comment by yashgandhi-32** [comment]
Thanks @Nivedipa-MSFT i will it
