### ISSUE TITLE
Teams developer portal bot configured only for Teams is available for outlook

### ISSUE THREAD

**Issue by NandhiniArcher** [OfficeDev/Microsoft-Teams-Samples#1467]
In the Developer Portal, I configured my bot's channel settings to enable only Microsoft Teams and did not select Microsoft 365 extensions. However, when I upload my app package to Partner Center, it indicates that my app will be available not only in Teams but also in Office (web and Windows) and Outlook (web and Windows).

Is there something I might be missing in the configuration? My app/bot is intended to be available exclusively for Microsoft Teams.
![image](https://github.com/user-attachments/assets/d11fdbf6-7730-41b8-9d62-cadaa7f38c23)

Partner center screenshot:
<img width="354" alt="TeamsAPP Package" src="https://github.com/user-attachments/assets/828de75c-451b-4011-9896-55d29cbcb5b5">

**Comment by Meghana-MSFT** [comment]
@NandhiniArcher - Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@NandhiniArcher - Please note that v.1.13 or later versions auto-extends support of Teams apps to run in other Microsoft 365 host applications, including Outlook and Office.

https://github.com/OfficeDev/microsoft-teams-app-schema/releases#:~:text=Support%20for%20apps%20running%20across%20Microsoft%20365

**Comment by NandhiniArcher** [comment]
> @NandhiniArcher - Please note that v.1.13 or later versions auto-extends support of Teams apps to run in other Microsoft 365 host applications, including Outlook and Office.
> 
> https://github.com/OfficeDev/microsoft-teams-app-schema/releases#:~:text=Support%20for%20apps%20running%20across%20Microsoft%20365

@Meghana-MSFT 
Thank you for the clarification regarding version 1.13 and the auto-extension of Teams apps to Outlook and Office. I have a follow-up question:

When my app is listed on the Teams store, will it indicate compatibility with Outlook and Office, or will it only display compatibility with Teams?

**Comment by Meghana-MSFT** [comment]
It will display compatibility with Outlook and Office as well.

**Comment by NandhiniArcher** [comment]
> It will display compatibility with Outlook and Office as well.

But it will be functional only on teams? Despite showing compatibility with Outlook and office as well?

**Comment by Meghana-MSFT** [comment]
If your Teams app is using the app manifest version 1.13 or later, ensure that your app meets the criteria to [extend your app to run across Microsoft 365 or Outlook](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab).

**Comment by NandhiniArcher** [comment]
> If your Teams app is using the app manifest version 1.13 or later, ensure that your app meets the criteria to [extend your app to run across Microsoft 365 or Outlook](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab).

@Meghana-MSFT Thank you for your quick response. 
We have not made any changes to extend our app to work across Microsoft 365 or Outlook. Currently, the app is functional only in Microsoft Teams. Will this impact the publishing process in Partner Center?

**Comment by Meghana-MSFT** [comment]
Could you please visit the [publishers support page ](https://partner.microsoft.com/en-us/support/v2)to search for your issue. If the guidance isn't helpful, please create a [Partner Center support ticket](https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/support#how-to-open-a-support-ticket%22https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/support#how-to-open-a-support-ticket%22).

**Comment by NandhiniArcher** [comment]
> Could you please visit the [publishers support page ](https://partner.microsoft.com/en-us/support/v2)to search for your issue. If the guidance isn't helpful, please create a [Partner Center support ticket](https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/support#how-to-open-a-support-ticket%22https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/support#how-to-open-a-support-ticket%22).

Thank you for responding to my previous query. I appreciate your assistance.

As a follow-up, I would like to ask:
How can I identify the minimum and recommended Microsoft Teams versions that ensure full support for all features and functionalities of a Teams app using manifest versions 1.17?

Your clarification on this matter would be greatly helpful.

**Comment by Meghana-MSFT** [comment]
It is suggested to use the latest version. You can refer to the app [manifest reference documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema). 

For detailed information on the changes made in each version, you can check the [app manifest change log](https://github.com/OfficeDev/microsoft-teams-app-schema/releases).

**Comment by NandhiniArcher** [comment]
> It is suggested to use the latest version. You can refer to the app [manifest reference documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema).
> 
> For detailed information on the changes made in each version, you can check the [app manifest change log](https://github.com/OfficeDev/microsoft-teams-app-schema/releases).

I appreciate your response and the reference to the app manifest documentation. However, I noticed that the documentation primarily discusses the compatibility between the TeamsJS version and the app manifest version.

I am specifically looking to understand how to determine the Microsoft Teams desktop or web application software version compatibility with app manifest version.

Could you please clarify:

Is there a reference or documentation that maps Microsoft Teams software versions to their compatibility with app manifest versions?
This information will help us to ensure our app functions seamlessly with the supported Teams client versions.

**Comment by Meghana-MSFT** [comment]
@NandhiniArcher - Unfortunately there is no such documentation that maps Microsoft Teams software versions to their compatibility with app manifest versions. And there is no dependency of app manifest version on the Microsoft Teams. It is suggested to use the latest version of Microsoft Teams desktop or web application.

**Comment by Meghana-MSFT** [comment]
@NandhiniArcher - I will inform team to look into it.
