### ISSUE TITLE
Where is the AI powered Company Communicator sample?

### ISSUE THREAD

**Issue by JonoSuave** [OfficeDev/Microsoft-Teams-Samples#1471]
At the 3:20 mark of the Microsoft Community Learning call you'll notice that an AI Extensibility Solution Sample called, "AI powered Company Communicator": https://youtu.be/w82nsTuU-dA?si=5ujzc6Y9tSyHaczP

This doesn't appear to be in the Teams AI Samples: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main?tab=readme-ov-file#ai-samples

Where can I find that sample?

**Comment by Meghana-MSFT** [comment]
@JonoSuave - Thank you for reporting this, we will check this and get back to you.

**Comment by Prasad-MSFT** [comment]
Hi @JonoSuave, thanks for raising your issue. We are checking this internally with concerned team and will get back to you once we have any update. Thanks!

**Comment by ChetanSharma-msft** [comment]
Hello @JonoSuave - Sorry for delay in response.
We did not come around to developing that sample due to roadmap and priority changes.

**Comment by JonoSuave** [comment]
Appreciate the update

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
