### ISSUE TITLE
bot proactive message debug error: Missing environment variables

### ISSUE THREAD

**Issue by ayachensiyuan** [OfficeDev/Microsoft-Teams-Samples#1472]
Due to [PR](https://github.com/OfficeDev/Microsoft-Teams-Samples/commit/3463c895f3936791793da54dc6370adc7b33efc1#diff-6bffeaae38cdd81bc9fcd85932a498e96df91d5cdd40276a5e594ddaf2766bd7L1) change manifest file "app name variable" from "CONFIG__MANIFEST__APPNAME__SHORT" to "CONFIG__APPNAME__SHORT", now follow readme to debug will get  Error: Missing environment variables 'CONFIG__APPNAME__SHORT' for file: XXX.
if this name change is necessary, env and related file still need to update also.

<img width="1594" alt="image" src="https://github.com/user-attachments/assets/6fd0688b-ca49-418c-9019-b882873be9f2">

repo step:
 - install teams toolkit vsc extension
 - clone sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-proactive-messaging-teamsfx
 - local debug follow readme
 <img width="1442" alt="image" src="https://github.com/user-attachments/assets/85639033-7231-4feb-87fb-4db9697e6323">

**Comment by Nivedipa-MSFT** [comment]
@ayachensiyuan - Thank you for your inquiry about your Teams app development issue! We will test this and update you soon.

**Comment by ayachensiyuan** [comment]
@Nivedipa-MSFT @Mohammed-MSFT Local debug is work, but provision in to azure still have missing environment variables issue. 
repo step: "teamsapp provision --env dev"
![image](https://github.com/user-attachments/assets/f60e715b-a3e2-4846-a7dd-a36faaf8f683)

**Comment by Mohammed-MSFT** [comment]
Hi @ayachensiyuan 
Thank you for your inquiry about azure provision issue, I have tested and fixed the issue, and the Azure provisioning was successfully executed. Will create the PR and update the sample as soon as possible.
FYI
<img width="951" alt="image" src="https://github.com/user-attachments/assets/7e045410-8b13-4cc9-a015-9049e97b8b03" />

**Comment by ayachensiyuan** [comment]
Today's test result shows that your PR change is work, thanks @Mohammed-MSFT

**Comment by Nivedipa-MSFT** [comment]
@ayachensiyuan - Glad to hear that the issue has been resolved! 

Could you please share your valuable feedback via the [Microsoft Teams Developer Community Response Feedback link?](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) Your input helps us improve our support.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
