### ISSUE TITLE
Meeting Side Panel - Node Js sample is not in working condition

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/Microsoft-Teams-Samples#149]
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/4d7a046cbb6535f9f00f475e02612547a82d14f3/samples/meetings-sidepanel/nodejs
Side Panel above sample is not in working condition. Could not able to start using npm start
Issue like Cannot find module '../bots/teamsConversationBot'

**Comment by AbhijeetThakur-msft** [comment]
Hi @SubbaReddi, we will check this at our end and revert.

**Comment by AbhijeetThakur-msft** [comment]
Hi @SubbaReddi, we checked it and made the required changes, we will update the code base accordingly.
