### ISSUE TITLE
Documentation to create `bot channels registration` is outdated/incorrect

### ISSUE THREAD

**Issue by Josverl** [OfficeDev/Microsoft-Teams-Samples#152]
The documentaion in [Tab sample 13 - Node JS - azure-bot-channels-registration](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-adaptive-cards/nodejs/Wiki/azure-bot-channels-registration.md) refers to `bot channels registration` which has been [deprecated](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=csharp#create-the-resource), and replaced with a new prodecure/workflow.

According to a [quick search](https://github.com/search?q=%22%23%23+Create+the+bot+channels+registration%22+repo%3AOfficeDev%2FMicrosoft-Teams-Samples&type=Code&ref=advsearch&l=&l=) there are 6 samples that use this same documentation , that should all be updated.

**Comment by AbhijeetThakur-msft** [comment]
Hi @Josverl, we will look at this from our end and update the links for all the samples.

**Comment by Josverl** [comment]
I'd label this as a bug rather than enhancement, but that's just semantics

**Comment by ChetanSharma-msft** [comment]
Hello @Josverl - These changes are merged as a part of this PR: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/629

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
