### ISSUE TITLE
Yeoman Generator link for item 4 in the Tabs samples is broken

### ISSUE THREAD

**Issue by Ofer-Gal** [OfficeDev/Microsoft-Teams-Samples#154]
I wanted to see the Tabs sample for 
4 | Channel and group tabs | Sample app showing custom group and channel Tab with ASP. NET Core

but the link showed 404

**Comment by Wajeed-msft** [comment]
Thanks for pointing out. I have fixed it. Documentation URL got changed to this: https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-yeoman
