### ISSUE TITLE
Error	MSB3491	Could not write lines to file "obj\Debug\netcoreapp3.1\staticwebassets\ProactiveAppInstallation.StaticWebAssets.Manifest.cache". Path: obj\Debug\netcoreapp3.1\staticwebassets\ProactiveAppInstallation.StaticWebAssets.Manifest.cache exceeds the OS max path limit. The fully qualified file name must be less than 260 characters.	ProactiveAppInstallation	C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets

### ISSUE THREAD

**Issue by rageshzerone** [OfficeDev/Microsoft-Teams-Samples#184]
Hi,

I already downloaded the source code and trying to run the C# application in _Microsoft-Teams-Samples-main\samples\graph-proactive-installation\csharp_ folder. I am using VS 2019 and .net core 3.1. When i trying to build the code it shows a message like below.

**Error	MSB3491	Could not write lines to file "obj\Debug\netcoreapp3.1\staticwebassets\ProactiveAppInstallation.StaticWebAssets.Manifest.cache". Path: obj\Debug\netcoreapp3.1\staticwebassets\ProactiveAppInstallation.StaticWebAssets.Manifest.cache exceeds the OS max path limit. The fully qualified file name must be less than 260 characters.	ProactiveAppInstallation	C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.target**s

**Comment by Wajeed-msft** [comment]
@rageshzerone - could you please try placing the repo into the root of your drive and try again? 
Docs: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd

**Comment by Wajeed-msft** [comment]
@rageshzerone - please reopen if you are still facing this issue.
