### ISSUE TITLE
SidePanel tab is not working in-meeting

### ISSUE THREAD

**Issue by Wajeed-msft** [OfficeDev/Microsoft-Teams-Samples#192]
### Discussed in https://github.com/OfficeDev/Microsoft-Teams-Samples/discussions/175

<div type='discussions-op-text'>

<sup>Originally posted by **june-dit** October 14, 2021</sup>
Manifest has the following settings for the sidePanel tab, but the application icon is not showing on the in-meeting toolbar, so there is no way to show the sidePanel, could you help me to figure out is there anything missing in the configuration or code to make the sidePanel work in-meeting? Thanks.

```
  "configurableTabs": [
    {
      "configurationUrl": "https://{{PUBLIC_HOSTNAME}}/sidePanelTab/config.html?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}",
      "canUpdateConfiguration": true,
      "scopes": [
        "groupchat"
      ],
      "meetingSurfaces": [
        "sidePanel"
      ],
      "context": [
        "meetingSidePanel"
      ]
    }
  ],
```</div>

**Comment by Nivedipa-MSFT** [comment]
@june-dit - Could you please share the Teams SDK version which you are using?

**Comment by Nivedipa-MSFT** [comment]
@june-dit - Use version 1.7.0 or higher of Teams SDK, as versions prior to it do not support the side panel.
Please go through below link fore more details.
https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings#meeting-sidepanel

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
