### ISSUE TITLE
installing app via App Studio pre-defined template fails 

### ISSUE THREAD

**Issue by antontru** [OfficeDev/Microsoft-Teams-Samples#20]
Steps: Go to Teams > App Studio > UI Tools tab > Sample app  > Install to Teams.

Result: Error occurred, details: 

> Error while reading manifest.json: Invalid value(s) specified for validDomains[1]: "officedev.github.io/microsoft-teams-app-sample/#"

**Comment by Wajeed-msft** [comment]
@akatrukhin, @asnow003 - Could you please help to check this?

**Comment by akatrukhin** [comment]
Sorry @antontru, everything looks as expected. Just tested and can't catch the same issue.
Would you able to open help me and understand why it's happening:
1)  Could you test this link in your browser and check if it's respond  https://officedev.github.io/microsoft-teams-app-sample/#/ ?
2) @asnow003 Is it could be relative to manifest schema version or Teams version? 
3) @antontru could you try to install [app sample package](https://aka.ms/teamsuisampleapp) directly by your own?
 In the Teams client, go to **Apps**.

Select **Upload a custom app** and upload the app package, which is the generated `zip` file in the `package` folder.

   <img type="content" src="https://docs.microsoft.com/en-us/microsoftteams/platform/assets/images/build-your-first-app/upload-custom-app-closeup.png" alt-text="Illustration showing where in Teams you can upload a custom app." />

**Comment by yakall** [comment]
Hi @akatrukhin 
Have similar issue with this app package.
1. built from the source - when trying install package in Teams client, error message is [...]Error while reading manifest.json: "validDomains[0]" is required 
2. using ready to install package from [https://aka.ms/teamsuisampleapp](url) error message is [...]Error while extracting package: Please ensure there are no folders in your app package and that your app package contains only the manifest.json and the two required icon files at its root level. For an easier experience creating your app package, install App Studio from the Teams Store.[..]

**Comment by belasor** [comment]
Hey guys, 

the problem is really easy to fix.
The domain which is in the manifest is wrong, if you change this:
`"validDomains": ["officedev.github.io/microsoft-teams-app-sample/#"],`
to this it will work:
`"validDomains": ["officedev.github.io"],`

Explanation:
I think teams is only accepting the top level domain and nothing else.
