### ISSUE TITLE
README errors in tab-sso/csharp/

### ISSUE THREAD

**Issue by gabbsmo** [OfficeDev/Microsoft-Teams-Samples#207]
1. Reply uri should be /Auth/End, not /End
2. The configurable tab's url is /Home/Configure, not /Home/ConfigTab

**Comment by Nivedipa-MSFT** [comment]
@gabbsmo - We are looking into this issue. We will update you.

**Comment by v-chetsh** [comment]
This request is related to updating the docs so redirecting it.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
