### ISSUE TITLE
Microsoft-Teams-Samples/samples/tab-ui-templates app issue

### ISSUE THREAD

**Issue by WyldLynx** [OfficeDev/Microsoft-Teams-Samples#21]
Once this app is install and running locally the index displays about page, any other page selection returns the same about page.

i.e http://localhost:3000/board#/ only shows about.

![image](https://user-images.githubusercontent.com/13086074/105421454-da724c80-5c8d-11eb-8f0d-b57eaeedd960.png)

![image](https://user-images.githubusercontent.com/13086074/105421753-579dc180-5c8e-11eb-8e82-c2889dbde6ac.png)

**Comment by Wajeed-msft** [comment]
@asnow003 , @akatrukhin, Could you please help to check this?

**Comment by carlosulibarrenanuin** [comment]
I have the same problem! I clone de repo and follow the instructions on the Readme.md but all the pages redirect to the About page.

**Comment by akatrukhin** [comment]
@WyldLynx, @carlosulibarrenanuin, Thank you for response.
Fixed links in documentation. App is using hash router, please follow examples below:

   - **Required Teams app pages**:
     - About: [http://localhost:3000](http://localhost:3000)
     - Privacy: [http://localhost:3000/#/privacy](http://localhost:3000/#/privacy)
     - Terms of use: [http://localhost:3000/#/termsofuse](http://localhost:3000/#/termsofuse)
   - **Sample app tabs**:
     - [http://localhost:3000/#/welcome](http://localhost:3000/#/welcome)
     - [http://localhost:3000/#/dashboard](http://localhost:3000/#/dashboard)
     - [http://localhost:3000/#/list](http://localhost:3000/#/list)
     - [http://localhost:3000/#/board](http://localhost:3000/#/board)

**Comment by WyldLynx** [comment]
Thanks for your help @akatrukhin - is there a reason for the # routing or just how it was built?

**Comment by akatrukhin** [comment]
No specific reason. You could use regular as well.
There was a hosting issue, but currently it’s not relative.
