### ISSUE TITLE
The readme for the ReceiveMessagesWithRSC sample should mention that the Azure Bot resource must have the MsTeams channel enabled.

### ISSUE THREAD

**Issue by kostasvl** [OfficeDev/Microsoft-Teams-Samples#213]
Hi. I followed the [readme for the ReceiveMessagesWithRSC sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-receive-channel-messages-withRSC/csharp), and got to step 2: "Create a Bot Registration In Azure portal". I clicked that link to double check whether this is an AZ AD App Registration, or an Azure Bot resource. It was the latter. I've created those before, so I quickly created another. I didn't think at the time to configure the MsTeams channel for it...

As a result, I got a "Something went wrong" error later, in Teams, which I eventually tracked down through the logs to an equally vague "AddAppBotToChatRosterFailed". It was a random reply [here](https://github.com/MicrosoftDocs/msteams-docs/issues/3178#issuecomment-857497201) that led me to the solution.

Since even the [Azure Bot documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp#create-the-resource) doesn't have an explicit reminder like "After creation, make sure to configure the right bot channels for your needs", I figured such a reminder definitely has a place in the readme of the ReceiveMessagesWithRSC sample. Can you please add it?

I had a look randomly through some of the other samples, and they don't seem to need an Azure Bot resource - just an AZ AD registration. I suppose there will be a few I missed, in which case they could do with adding the same reminder, IMO.

Of course, we wouldn't need this reminder if the actual error could be surfaced in the Teams client... Something like: "MsTeams not configured as a bot channel for this app, please check <...>". That [github issue](https://github.com/MicrosoftDocs/msteams-docs/issues/3178#issuecomment-857497201) I linked to above is also about this, I think.

Thanks

**Comment by v-chetsh** [comment]
@kostasvl - We will check on it and redirect it to doc team accordingly.

**Comment by Prasad-MSFT** [comment]
In the navigation pane, select Channels to configure Microsoft in Azure Bot.
![image](https://user-images.githubusercontent.com/62237649/145348010-0d016bfa-a8d8-4151-8989-24e803ebdf7c.png)

Redirecting to doc team for documentation enhancement.

**Comment by kostasvl** [comment]
Thanks @Prasad-MSFT.

It turns out there's another important requirement, which is also not necessarily intuitive, and it is not directly mentioned in either the sample's readme, or the Azure bot documentation the readme links to (as far as I can tell): For the bot to work with Teams, it must be configured as Multitenant! (see [here](https://github.com/microsoft/botbuilder-js/issues/1447) for example)

Then, for completeness, you may as well also add this reminder in the readme. It's the final necessary step, I think: "Go to the Configuration page and configure the messaging endpoint. It needs to be "{ngrok https url}/api/messages".

At least I hadn't forgotten that last thing :D.

**Comment by v-chetsh** [comment]
@kostasvl - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by v-chetsh** [comment]
@kostasvl - We have updated all the samples for README to enable the Teams channel in Azure Bot.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
