### ISSUE TITLE
Application with identifier '<App ID>' was not found in the directory 'Bot Framework'

### ISSUE THREAD

**Issue by DaveFSP** [OfficeDev/Microsoft-Teams-Samples#214]
I am having an issue with building this. I have followed the steps but i am getting the following error 

> Error: Get Token request returned http error: 400 and server response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '2c33dd0e-3d4c-4d30-b243-4bd9dd9d1d47' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

I am not sure where its getting the directory 'BOT Framework'.

My env. looks like this 
`MicrosoftAppId="2c33dd0e-3d4c-4d30-b243-4bd9dd9d1d47"
MicrosoftAppPassword=""
ConnectionName="botToken"
BaseUrl="v1"`

With the MicrosoftAppPassword it is the clientsecret found in the KeyVault.
ConnectionName is the OAuth name in my bot configuration
![image](https://user-images.githubusercontent.com/84777220/145552890-473d537c-357f-4e8e-94fe-e720e4613a28.png)
The client id and secret here being the app reg set up for the bot

my manifest,json which has been zipped up and put into my teams looks like this:
`{
  "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
  "manifestVersion": "devPreview",
  "version": "1.0.0",
  "id": "4d9e95ab-ebe3-4976-82e9-3526d5c54906",
  "packageName": "com.microsoft.tabadaptivecard",
  "developer": {
    "name": "Microsoft",
    "websiteUrl": "https://www.microsoft.com",
    "privacyUrl": "https://www.microsoft.com/privacy",
    "termsOfUseUrl": "https://www.microsoft.com/termsofuse"
  },
  "name": {
    "short": "TabWithAdaptiveCard",
    "full": "Tab With Adaptive Card"
  },
  "description": {
    "short": "View Tab With Adaptive Card",
    "full": "This sample demos the tab with adaptive cards"
  },
  "icons": {
    "outline": "outline.png",
    "color": "color.png"
  },
  "accentColor": "#60A18E",
  "staticTabs": [
    {
      "entityId": "homeTab",
      "name": "Home",
      "contentBotId": "2c33dd0e-3d4c-4d30-b243-4bd9dd9d1d47",
      "scopes": [ "personal" ]
    }
  ],
  "permissions": [ "identity", "messageTeamMembers" ],
  "validDomains": [
    "e016-87-115-110-176.ngrok.io",
    "token.botframework.com"
  ]
}`

The contentBotId is the AppId of the bot 

Have i missed anything else?

**Comment by HunaidHanfee-MSFT** [comment]
Please double check the configuration? This mostly happen when we make mistake while configuring it.

Please follow this doc to understand more - https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample#azure-ad-v2

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Did you get a chance to check and confirm? Could you please let us know the updates?

**Comment by DaveFSP** [comment]
Apologies for the delay. It was a silly mistake in configuration. I had missed out one of the scopes I needed. Thank you for pointing me in the right direction

**Comment by SK-ASIF-ALI** [comment]
How did you resolve..please tell i'm also having same issue @DaveFSP

**Comment by Tagliari43** [comment]
alguem pode me ajudar com meu app se chama SOSPlanet app
