### ISSUE TITLE
Meeting app Panel deep link

### ISSUE THREAD

**Issue by Wajeed-msft** [OfficeDev/Microsoft-Teams-Samples#219]
### Discussed in https://github.com/OfficeDev/Microsoft-Teams-Samples/discussions/218

<div type='discussions-op-text'>

<sup>Originally posted by **antoniogatti** December 15, 2021</sup>
Hi everyone,

Is there an option to create a deep link to an app added to a meeting?
Microsoft Documentation around deep link doen not provide any information on deep link in a meeting:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links

Thanks in advance for any advise.
Antonio</div>

**Comment by sayali-MSFT** [comment]
@antoniogatti - We are looking into this I will get back to you soon.

**Comment by v-chetsh** [comment]
@antoniogatti - We are checking it internally and let you know if we get any updates.

**Comment by sayali-MSFT** [comment]
Hi @antoniogatti  Please try deeplinking to app added to a meeting  with the below syntax:
https://teams.microsoft.com/l/entity/<meetingId>/<entityId>?context={"chatId": "<meetingId>","contextType":"chat"}
example--https://teams.microsoft.com/l/entity/19%3ameeting_NDRmNzUzNjItYTYwNC00OWNhLWI4OTYtODUyNDI2NWY4MmE1%40XXXXXXXXXX.v2/Post-it?context={"chatId": "19%3ameeting_NDRmNzUzNjItYTYwNC00OWNhLWI4OTYtODUyNDI2NWY4MmE1%40XXXXXXXXXX.v2","contextType":"chat"}

Will raise a bug to Document Team for the necessary changes to be made in the document.

**Comment by v-chetsh** [comment]
@antoniogatti - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by v-chetsh** [comment]
@antoniogatti - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by v-chetsh** [comment]
@antoniogatti - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
