### ISSUE TITLE
Sample is not in working condition

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/Microsoft-Teams-Samples#221]
Hi Team,
Following sample is not in working condition: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-config-page-auth/csharp

Code is referring .js files from library folder. But there is no library folder in the project.

**Comment by Prasad-MSFT** [comment]
@SubbaReddi - We are checking the sample. Will update it wherever necessary
