### ISSUE TITLE
Again! Error while integrating Stage View 

### ISSUE THREAD

**Issue by i066088** [OfficeDev/Microsoft-Teams-Samples#236]
Version: You have Microsoft Teams Version 1.5.00.1870 (64-bit). It was last updated on 1/20/2022.

Facing Something went wrong. Please try again. when trying to integrate Stage View in an adaptive card and following tab-stage-view sample for reference. I have implemented a personal tab and using it in stage view.
![2022-01-21 22_49_18-Tab Stage View _ Microsoft Teams](https://user-images.githubusercontent.com/40688635/150547418-69d24b4b-9635-4c0d-b474-dd2068b9568c.png)

manifest.json

"staticTabs": [
   {
     "contentUrl": "<ngrok-url>/tab-auth/simple",
     "entityId": "simpleAuth",
     "name": "Test Authentication Tab",
     "scopes": [
       "personal"
     ],
     "context": [
       "personalTab",
       "channelTab"
     ],
   }
 ]
adaptiveCardJson

"body": [
  ...,
  {
    type: 'ActionSet',
    actions: [
      {
        type: "Action.Submit",
        title: "Auth Tab",
        data: {
          msteams: {
            type: "invoke",
            value: {
              type: "tab/tabInfoAction",
              tabInfo: {
                contentUrl: "<ngrok-url>/tab-auth/simple",
                websiteUrl: "<ngrok-url>/tab-auth/simple",
                name: "Test Authentication Tab",
                entityId: "simpleAuth"
              }
            }
          }
        }
      }
    ]
  },
]
Error Screenshot
![2022-01-21 22_50_52-Tab Stage View _ Microsoft Teams](https://user-images.githubusercontent.com/40688635/150547636-ae3d7e8e-980a-4b8c-b9a3-876283049399.png)

**Comment by Prasad-MSFT** [comment]
@i066088 - We are already tracking this issue here [#196](https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/196) . We have informed engineering team about re-occurrence of the issue and will inform once we get any update. If you want ,you can close this instance and follow that thread for updates.

**Comment by i066088** [comment]
@Prasad-MSFT  thanks a lot for the update. I see #196 is closed. So I created a new one. If #196 is re-open, I will close this one.

**Comment by v-chetsh** [comment]
@i066088 -  Could you please check it in Microsoft Teams Version 1.4.00.34416 (64-bit).
Please let us know if you are facing issue in this version.

We will also check the issue in Teams version 1.5.00.1870 (64-bit) because currently this version is not visible to us.

**Comment by i066088** [comment]
@v-chetsh I would like to. But I do not know how to download the Microsoft Teams Version 1.4.00.34416 (64-bit).
I find my team client is always updated silently. 
Could you give any hints where I can find the Microsoft Teams Version 1.4.00.34416 (64-bit)?
thanks a lot.

**Comment by Prasad-MSFT** [comment]
https://microsoft-teams.en.uptodown.com/windows/versions
That's one place that has an archive of older versions. You can check from here

**Comment by i066088** [comment]
@Prasad-MSFT  Thanks for the link. I open the link But I cannot find the Microsoft Teams Version 1.4.00.34416 (64-bit).

**Comment by v-chetsh** [comment]
@i066088 - Could you please try updating your Teams with latest version and check it once.

**Comment by i066088** [comment]
@v-chetsh thanks a lot. It works on Microsoft Teams Version 1.5.00.2164 (64-bit). It was last updated on 2/4/2022.

**Comment by i066088** [comment]
@v-chetsh 
From this link https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/tabs-link-unfurling
I see the following description:
"
When the user enters a URL on the Teams desktop client, the bot is invoked and returns an [Adaptive Card](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions) with the option to open the URL in a stage. After a stage is launched and the tabInfo is provided, you can add the ability to pin the stage as a tab.
"

Could you give some hints about how I can add the ability to pin the stage as a tab?
thanks in advance.

**Comment by v-chetsh** [comment]
@i066088 - Could you please refer below samples and try it once:
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-stage-view

**Comment by v-chetsh** [comment]
@i066088 - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by Prasad-MSFT** [comment]
We are closing the issue for now. Please feel free to reopen if required. Thanks!
