### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by piotrlech** [OfficeDev/Microsoft-Teams-Samples#238]
With respect to the description of Microsoft-Teams-Samples/samples/bot-archive-groupchat-messages/csharp/:

> What is meant by the YOUR-MICROSOFT-APP-ID? Step 5 says Modify the manifest.json in the /AppManifest folder and replace the <<YOUR-MICROSOFT-APP-ID>> with the id from step 2, while step 2 is : In a terminal, navigate to samples/bot-archive-groupchat-messages/csharp. 

> Also it is not clear where to put the ngrok link

**Comment by Nivedipa-MSFT** [comment]
@piotrlech - We are checking it and we will redirect to documentation team for update

**Comment by piotrlech** [comment]
In the archive-groupchat example we have to replace the Microsoft App Id in 5 different locations such as bot server config and the appPackege - could you specify where we put the Bot-hadle application ID and where the AAD application ID, please?

**Comment by v-chetsh** [comment]
@piotrlech - Sure, we will check and update it accordingly at all the places.

**Comment by v-chetsh** [comment]
@piotrlech - Contents are updated now. Please check it once & let us know.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
