### ISSUE TITLE
Bot not able to get meeting details

### ISSUE THREAD

**Issue by Githamza** [OfficeDev/Microsoft-Teams-Samples#244]
I'm building a channel tab + bot .

since a moment , when I add my custom app then after setting it and run the first time I get this error message on back end

```
code:'NotEnoughPermissions'
message:'Bot not allowed to get meeting details'
```
In Azure Portal I have added meeting permissions 

email 
offline_access 
OnlineMeetings.Read
OnlineMeetings.ReadWrite 
openid
profile 
User.Read 

But still get error. I have googled it but haven't found any similar issue

**Comment by Nivedipa-MSFT** [comment]
@Githamza - Could you please verify if you have required pre-requisites and APIs configured as mentioned in below doc: https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#meeting-details-api

**Comment by v-chetsh** [comment]
@Githamza - Could you please check in below sample:
https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#code-sample

Reference docs:
https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#code-sample

Also make sure that you have added/installed the tab in a particular meeting.

**Comment by Nivedipa-MSFT** [comment]
@Githamza - Could you please confirm is your issue resolved or still facing the issue?

**Comment by Githamza** [comment]
> @Githamza - Could you please verify if you have required pre-requisites and APIs configured as mentioned in below doc: https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/api-references?tabs=dotnet#meeting-details-api

Thanks, after adding online metting permissions in the manifest , that worked

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
