### ISSUE TITLE
Proper way to handle access_token expiration

### ISSUE THREAD

**Issue by VysockyStan** [OfficeDev/Microsoft-Teams-Samples#245]
Hi, I implemented Tabs SSO with teams SDK.
I successfuly fetch the access_token (no need to exchange it for more graph token) and use it to comunicate with backend.

But the token's TTL is about 2 hours and I need to get the new one. But without refresh token I hardly imaging how to do that.

Could you please give me a possible solution

Thank you.

**Comment by sayali-MSFT** [comment]
@VysockyStan -We are looking into this I will get back to you soon.

**Comment by Prasad-MSFT** [comment]
@VysockyStan - Please refer below doc which explains how to handle access tokens.
https://docs.microsoft.com/en-us/machine-learning-server/operationalize/how-to-manage-access-tokens

Also refer: https://developers.facebook.com/blog/post/2011/05/13/how-to--handle-expired-access-tokens/

**Comment by VysockyStan** [comment]
Thanks for the links.

So as I understand using teams sdk is not enough and I also need to use msal 2 lib to reathenticate. 
Do I?

Thank you

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
