### ISSUE TITLE
Tab Conversation sample got an invalid manifestVersion value

### ISSUE THREAD

**Issue by davrous** [OfficeDev/Microsoft-Teams-Samples#246]
The manifestVersion value shouldn't be "1.10" in this sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-conversations/csharp/TabConversation but "1.11" otherwise, you can't load the app in Teams with the following error:

![image](https://user-images.githubusercontent.com/933018/152243982-b7bf681b-c121-4320-850d-f4cb38b72581.png)

Thanks!

**Comment by v-chetsh** [comment]
@davrous - We will check on it and update it accordingly.

**Comment by Nivedipa-MSFT** [comment]
@davrous - We have uploaded the manifest zip with manifestVersion value "1.10"  of sample https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-conversations/csharp/TabConversation.
Its working fine at our end.

![image](https://user-images.githubusercontent.com/92150070/152292930-2f5b4dde-8f80-46f5-bc7d-b4dcfdb4f46a.png)

In your error screenshot it displayes that your Teams is in R0 ring. Could you please try to change it to Public Ring and check again.
![image](https://user-images.githubusercontent.com/92150070/152293446-b9246899-6b7d-4b82-ac71-79639841f43c.png)

**Comment by Nivedipa-MSFT** [comment]
@davrous - We are able to repro your issue when importing the app via "Import an existing app" through "App Studio".
**App Studio will soon be deprecated. You can now Configure, distribute, and manage your Teams apps with the new [Developer Portal](https://dev.teams.microsoft.com/)**

**Comment by davrous** [comment]
Yep, I've seen that! Thanks for the follow-up. As App Studio will be soon deprecated, let's close this issue! :)
