### ISSUE TITLE
CS1576 Error building HelloWorld on Mac VS 8.10.16

### ISSUE THREAD

**Issue by mattgillam** [OfficeDev/Microsoft-Teams-Samples#247]
`VALID_PATH_HERE/csharp/Microsoft.Teams.Samples.HelloWorld.Web/obj/Debug/netcoreapp3.1/Razor/Views/Shared/_Layout.cshtml.g.cs(7,7): Error CS1576: The line number specified for #line directive is missing or invalid (CS1576) (Microsoft.Teams.Samples.HelloWorld.Web)`

that's on line 49, same error on lines 58 and 80.

Thank you.

**Comment by mattgillam** [comment]
Builds fine on Windows.

Lots of us use Macs though.

**Comment by Meghana-MSFT** [comment]
Please try removing the `<LangVersion>` from the project file. 
Please go through the following thread for more information - https://stackoverflow.com/questions/68768704/visual-studio-2019-version-16-11-0-error-cs1576-the-line-number-specified-for

**Comment by mattgillam** [comment]
> Please try removing the `<LangVersion>` from the project file.
> Please go through the following thread for more information - https://stackoverflow.com/questions/68768704/visual-studio-2019-version-16-11-0-error-cs1576-the-line-number-specified-for

Thank you Meghana. I removed the LangVersion tag from the .csproj - I now get an error at PostBuild - I charged 'powershell.exe' to 'push -Command' , I see the error below in build output.

The assertion that Manifest/Applications does not exist is correct. Should it?

Manifest contains only manifest.json and the 2 contuso logo PNGs.

```
Target PostBuild:
    pwsh -Command Compress-Archive -Path /"/Users/matt/dev/microsoft/samples/app-hello-world/csharp/Microsoft.Teams.Samples.HelloWorld.Web/Manifest/*/" -DestinationPath /"/Users/matt/dev/microsoft/samples/app-hello-world/csharp/Microsoft.Teams.Samples.HelloWorld.Web/bin/Debug/netcoreapp3.1/helloworldapp.zip" -Force
    Compress-Archive: The path '//Users/matt/dev/microsoft/samples/app-hello-world/csharp/Microsoft.Teams.Samples.HelloWorld.Web/Manifest/Applications' either does not exist or is not a valid file system path.
    /Users/matt/dev/microsoft/samples/app-hello-world/csharp/Microsoft.Teams.Samples.HelloWorld.Web/Microsoft.Teams.Samples.HelloWorld.Web.csproj(27,7): error MSB3073: The command "pwsh -Command Compress-Archive -Path /"/Users/matt/dev/microsoft/samples/app-hello-world/csharp/Microsoft.Teams.Samples.HelloWorld.Web/Manifest/*/" -DestinationPath /"/Users/matt/dev/microsoft/samples/app-hello-world/csharp/Microsoft.Teams.Samples.HelloWorld.Web/bin/Debug/netcoreapp3.1/helloworldapp.zip" -Force" exited with code 1.
Done building target "PostBuild" in project "Microsoft.Teams.Samples.HelloWorld.Web.csproj" -- FAILED.

```

**Comment by Meghana-MSFT** [comment]
Apologies for the delay. We checked this in Mac. We are able to repro this locally. We are checking this internally.

**Comment by mattgillam** [comment]
@Meghana-MSFT thanks for the update. I just switched the powershell command out for zip, works for me. I'll close the issue.
