### ISSUE TITLE
Step by Step deployment guide

### ISSUE THREAD

**Issue by siddiquiaslam** [OfficeDev/Microsoft-Teams-Samples#248]
Hi

Is there step by step deployment guide something like https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide ?

Thanks.

**Comment by sayali-MSFT** [comment]
@siddiquiaslam - Could you please elaborate your requirement ?

**Comment by sayali-MSFT** [comment]
@siddiquiaslam - Please have a look at this doc- https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/deploy
Hope it's helpful for you.
Let us know if you have any query.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
