### ISSUE TITLE
bot-type-ahead-search-adaptive-cards/csharp - bot throws the 501 error

### ISSUE THREAD

**Issue by KamilPacanek** [OfficeDev/Microsoft-Teams-Samples#256]
## Found in
[bot-type-ahead-search-adaptive-cards/csharp](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-type-ahead-search-adaptive-cards/csharp)

## Description
I request the `dynamicsearch` bot command and the adaptive card with dynamic typeahead is returned. When I type anything into the box, bot responds with error messages.
![image](https://user-images.githubusercontent.com/20944885/154982865-4a8d6717-d494-4bcf-b356-e5df42e9ae64.png)

By inspecting the web request, the following error response is returned from the `invoke` request.
```
{"errorCode":1008,"message":"<BotError>Bot returned unsuccessful status code NotImplemented"}
```

on ngrok:

![image](https://user-images.githubusercontent.com/20944885/154983041-5d8941b4-e1d9-416c-a6a1-85c708331c08.png)

## Analysis
After debugging session, I've found out that the status property doesn't exist in the `*.nuget.org/query` response, resulting in `NullReferenceException` in the `(int)packageResult["status"]` in the file [ActivityBot.cs](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/fd1c273b5cddd2dd656731fa899cd923a274544e/samples/bot-type-ahead-search-adaptive-cards/csharp/TypeaheadSearch/Bots/ActivityBot.cs#L93).

When I commented that line out, I am getting correct responses.

## Proposed resolution
Remove the status check or do a null check (maybe `status` is returned only in case of error).

**Comment by Prasad-MSFT** [comment]
We are trying to repro the issue at our end.

**Comment by Prasad-MSFT** [comment]
@KamilPacanek - We are able to repro the issue at our end. We will redirect this to concerned team to fix/update.
Thanks!

**Comment by KamilPacanek** [comment]
> @KamilPacanek - We are able to repro the issue at our end. We will redirect this to concerned team to fix/update. Thanks!

Thanks!

**Comment by v-chetsh** [comment]
@KamilPacanek - This issue has fixed now.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by KamilPacanek** [comment]
Thanks!
