### ISSUE TITLE
type-ahead "search" is not working inside bot

### ISSUE THREAD

**Issue by tmunir40** [OfficeDev/Microsoft-Teams-Samples#258]
Cloned MS sample repo for Static and Dynamic type-ahead to be used in Input.ChoiceSet, on alphabet entered, it only take to the items that starts with that alphabet, but searching is not available.

Following is the sample code for static search

`{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "type": "AdaptiveCard",
  "body": [
    {
      "text": "Please search for the IDE from static list.",
      "wrap": true,
      "type": "TextBlock"
    },
    {
      "columns": [
        {
          "width": "auto",
          "items": [
            {
              "text": "IDE: ",
              "wrap": true,
              "height": "stretch",
              "type": "TextBlock"
            }
          ],
          "type": "Column"
        }
      ],
      "type": "ColumnSet"
    },
    {
      "columns": [
        {
          "width": "stretch",
          "items": [
            {
              "choices": [
                {
                  "title": "Visual studio",
                  "value": "visual_studio"
                },
                {
                  "title": "IntelliJ IDEA ",
                  "value": "intelliJ_IDEA "
                },
                {
                  "title": "Aptana Studio 3",
                  "value": "aptana_studio_3"
                },
                {
                  "title": "PyCharm",
                  "value": "pycharm"
                },
                {
                  "title": "PhpStorm",
                  "value": "phpstorm"
                },
                {
                  "title": "WebStorm",
                  "value": "webstorm"
                },
                {
                  "title": "NetBeans",
                  "value": "netbeans"
                },
                {
                  "title": "Eclipse",
                  "value": "eclipse"
                },
                {
                  "title": "RubyMine ",
                  "value": "rubymine "
                },
                {
                  "title": "Visual studio code",
                  "value": "visual_studio_code"
                }
              ],
              "style": "filtered",
              "placeholder": "Search for a IDE",
              "id": "choiceSelect",
              "type": "Input.ChoiceSet"
            }
          ],
          "type": "Column"
        }
      ],
      "type": "ColumnSet"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "id": "submit",
      "title": "Submit"
    }
  ]
}
`

![image](https://user-images.githubusercontent.com/57490272/155331744-5408d3d3-048d-44a5-8f2b-5d75fbc0b0e5.png)

**Comment by sayali-MSFT** [comment]
@tmunir40 -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@tmunir40 -We are unable to repro the issue. It's working fine for us. Could you please check it once?
![image](https://user-images.githubusercontent.com/93527375/155533319-a9846266-76f1-46ef-8289-9373dcb591a0.png)

**Comment by sayali-MSFT** [comment]
@tmunir40 - Do you get chance to check?

**Comment by tmunir40** [comment]
@sayali-MSFT the behavior is still the same, even I've tried it on "https://adaptivecards.io/". I'm unable to give input in the field. The only behavior I'm seeing is any key I pressed, it takes out the item starting with that key, but it's not accepting text input.
![image](https://user-images.githubusercontent.com/57490272/156977627-3becb66b-52e3-45d0-85fa-3544e30c9d8a.png)

**Comment by sayali-MSFT** [comment]
@tmunir40 -I am tried with this sample only, did not change anything.
Sample Link:-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-type-ahead-search-adaptive-cards/csharp

**Comment by tmunir40** [comment]
@sayali-MSFT -For me, typing inside a Input field is not working, had tried on different browsers and Desktop teams app, but the behavior is same, heard the same issue on different platforms as well.

**Comment by sayali-MSFT** [comment]
@tmunir40 -I am checking this with different browser. but did not able to repro the scenario. Could please share the repro steps so we can tried it from our end?
https://user-images.githubusercontent.com/93527375/156992448-c3ba3ade-9391-482f-88a4-9ea93b505152.mp4

**Comment by sayali-MSFT** [comment]
@tmunir40 -Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by ChetanSharma-msft** [comment]
Hello @tmunir40 - Hope you are doing well!!
Could you please confirm if your issue has resolved or still looking for any help?

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
