### ISSUE TITLE
User has no Claims?

### ISSUE THREAD

**Issue by mattgillam** [OfficeDev/Microsoft-Teams-Samples#259]
Hello

I am testing this app. https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-personal-sso-quickstart/csharp_dotnetcore

It works as described in Teams but access to the user profile is done in the View. 

I am attempting to adapt this code so I can use the API (back end) to access data that requires authentication, so I need to be able to identify the User in the Action.

Using a breakpoint on the Action I can inspect the User object - but it has no accessible Claims?

Why is that?

Thanks

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/379568/155717104-2962a094-7e91-4543-94cc-9e096a0386d2.png">

**Comment by v-chetsh** [comment]
We will check on it and get back to you.

**Comment by Prasad-MSFT** [comment]
Please refer below sample references User Claims are being used.
https://github.com/OfficeDev/microsoft-teams-apps-quickresponses/blob/master/Source/Microsoft.Teams.Apps.CannedResponses/Controllers/BaseCannedResponsesController.cs#L79

https://github.com/OfficeDev/microsoft-teams-apps-quickresponses/blob/master/Source/Microsoft.Teams.Apps.CannedResponses/Controllers/CompanyResponseController.cs

**Comment by mattgillam** [comment]
thank you @Prasad-MSFT I will look at that when I can and ask for help if needed. Closing the issue, thanks for your help.
