### ISSUE TITLE
Documentation to support getting a webhook in connector.

### ISSUE THREAD

**Issue by samctrumpet** [OfficeDev/Microsoft-Teams-Samples#260]
I've been having major issues with the Microsoft teams connector documentation. Its incomprehensible at the moment for anyone who doesn't have a degree in Microsoft Documentation as they are half done and incomplete.

I just want to get the webhook URL when the connector opens but there is no documentation to support this. The current documentation literally just says "get the url from getSettings". Calling this function does nothing.

![image](https://user-images.githubusercontent.com/95428078/156387691-d50e4bb6-47ca-490e-8361-a53f2c91e731.png)

I've followed multiple different tutorials and documentation guides now and still nothing. I've followed this guide which no longer works.
https://docs.microsoft.com/en-us/learn/modules/msteams-webhooks-connectors/7-exercise-o365-connectors

I've wasted 2 days on this now. I've actually spoken with other developers who refuse to work on Microsoft Teams apps because its super complicated and convoluted. 

 Please can a guide be created for Node.js, with a sample app that shows

* Creating the connector
* Getting the webhook URL
* Sending the webhook URL to a Sample App to store against a user.
* Consuming the webhook URL on the Sample App to send a message to Microsoft teams.

**Comment by sayali-MSFT** [comment]
@samctrumpet -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@samctrumpet :-Here is some document related to Webhook and Connector.
1.[Creating the connector](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating)
2.[Create a Webhook URL](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook#create-an-incoming-webhook-1)
3.[Create actionable messages and send it through Incoming Webhook or Office 365 Connector.](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL)
4.[Sample Incoming webhook](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/incoming-webhook/csharp)

Hope this is helpful for you.

**Comment by samctrumpet** [comment]
@sayali-MSFT thanks for linking the documentation.

So it actually appears that the SDK is broken at the moment, someone else has raised an issue here https://github.com/OfficeDev/microsoft-teams-library-js/issues/970

**Comment by barrettlee** [comment]
@sayali-MSFT ,  Sorry, we all have tried the docs, samples and other resources, following precisely, again and again for a long time. There is another issue here https://github.com/OfficeDev/microsoft-teams-library-js/issues/680 from October, still open.
I think at this point there is either something that a lot of people are all doing identically wrong - configuration, missing a step, etc OR there is a bug in Teams or the SDK.

**Comment by sayali-MSFT** [comment]
@barrettlee -We are already checking it with engineering team and let you know if we get any updates.

**Comment by sayali-MSFT** [comment]
Issue is tracking here - https://github.com/OfficeDev/microsoft-teams-library-js/issues/680

**Comment by sayali-MSFT** [comment]
Hope your queries are resolved.
We are closing this issue for now, please feel free to reopen it, if required.
