### ISSUE TITLE
Calling and meeting bot

### ISSUE THREAD

**Issue by Shubham7054** [OfficeDev/Microsoft-Teams-Samples#262]
I am trying to set up calling and meeting bot using [this](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-calling-meeting/csharp#summary) documentation. In this step "Update MicrosoftAppId, MicrosoftAppPassword, AppId, AppSecret with your client_id and client_secret app registered in demo tenant. Update BotBaseUrl with your ngrok URL." What will be the MicrosoftAppId, AppId and UserId? Is it azure bot id?

**Comment by Meghana-MSFT** [comment]
We are looking into it, we will update you.

**Comment by Meghana-MSFT** [comment]
MicrosoftAppId, AppId  is the client_id of the app registered in demo tenant. Userid is id of the user to whom Online meeting policy need to be granted
![image](https://user-images.githubusercontent.com/81138249/156585474-d6ed85b6-840a-4c7f-b4a1-69a2e60cbeb3.png)

**Comment by Shubham7054** [comment]
Hi, thanks for replying. 
Here, does demo tenant means I've to create a demo tenant on office 365?

**Comment by Meghana-MSFT** [comment]
Demo tenant here means the tenant which you use.

**Comment by Shubham7054** [comment]
"Create a policy for a demo tenant user for creating the online meeting on behalf of that user using the following powershell script". Could you please help me figure out where should I run the script under above step

**Comment by Meghana-MSFT** [comment]
you can run the given script in Powershell.

**Comment by v-chetsh** [comment]
@Shubham7054  - Shall we close this issue now?

**Comment by Shubham7054** [comment]
Hi, thanks I'm closing this
