### ISSUE TITLE
Meeting app side panel without a bot.

### ISSUE THREAD

**Issue by JerryYangKai** [OfficeDev/Microsoft-Teams-Samples#272]
Hi, I have tried the Meetings SidePanel sample and it goes well, what I will do next is I just want to including the tab in my project, I do not want to add the bot any more. So I removed the bot folder and some related code, then changed the manifest. 

When I trying to test the side panel without bot, it seems not worked, I tried two solution.
1. Add the app in the meeting, the config page always loading and do not show the page, like this.
![image](https://user-images.githubusercontent.com/53805504/157578677-efac2673-2504-40f8-be2b-a8414d8d2519.png)

2. Add the app in the meeting chat, in this way the config page works well, but in the meeting after I select the app, the side panel page is still loading.
![image](https://user-images.githubusercontent.com/53805504/157581658-fc4e8cab-56a7-4730-804a-d8bbe54f1df5.png)

What I want to know is do the side panel always need a bot to run?

**Comment by sayali-MSFT** [comment]
@JerryYangKai -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@JerryYangKai - [Before you work with apps for Teams meetings, you must fulfill the  prerequisites.](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?view=msteams-client-js-latest&tabs=dotnet#notificationsignal-api)
1.The Meeting Details API must have a bot registration and bot ID. It requires Bot SDK to get TurnContext. To use the Meeting Details API, you must obtain different RSC permission based on the scope of any meeting, such as private meeting or channel meeting.

**Comment by JerryYangKai** [comment]
> @JerryYangKai - [Before you work with apps for Teams meetings, you must fulfill the prerequisites.](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?view=msteams-client-js-latest&tabs=dotnet#notificationsignal-api) 1.The Meeting Details API must have a bot registration and bot ID. It requires Bot SDK to get TurnContext. To use the Meeting Details API, you must obtain different RSC permission based on the scope of any meeting, such as private meeting or channel meeting. 2.The GetParticipant API must have a [bot registration and ID](https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-bot) to generate auth tokens.

@sayali-MSFT  Thanks for your quickly reply. Maybe I am not explain clearly about my question, I have found these API based on the BOT SDK, so I removed all the related things.
I will put some related code, in my manifest, removed the bot only contains the configurableTabs
`    "configurableTabs": [
        {
            "configurationUrl": "XXX/config",
            "canUpdateConfiguration": false,
            "scopes": [
              "groupchat"
            ],
            "context": [
              "meetingChatTab",
              "meetingDetailsTab",
              "meetingSidePanel"
            ]
        }
    ],`
    
In config page, the code like these.
`  render() {
    microsoftTeams.initialize();
    microsoftTeams.settings.registerOnSaveHandler((saveEvent) => {
      const baseUrl = `XXX`;
      microsoftTeams.settings.setSettings({
        suggestedDisplayName: "My Tab",
        entityId: "Test",
        contentUrl: baseUrl + "/tab",
        websiteUrl: baseUrl + "/tab",
      });
      saveEvent.notifySuccess();
    });

    microsoftTeams.settings.setValidityState(true);
    return (
      <div>
        <h1>Tab config</h1>
      </div>
    );
  }`

And the Tab page I changed to this one.
`  return (
    <div>
      <h1>Tab</h1>
    </div>
  );`

So the project only contains a single page withn nothing else and just make it show in side panel. Could you please help about this one？ Thanks.

**Comment by sayali-MSFT** [comment]
@JerryYangKai - We are checking it with engineering team and let you know once we get any updates.

**Comment by sayali-MSFT** [comment]
@JerryYangKai -We are unable to repro the scenario.
Here we can remove the Bot in manifest as you mention above and removed all the related things. It's working fine for us. Could you please check it once with the below code?
Ref Sample:-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-sidepanel/csharp
  
           microsoftTeams.initialize();
            microsoftTeams.appInitialization.notifySuccess();
            microsoftTeams.settings.registerOnSaveHandler(function (saveEvent) {
                  const baseUrl = `XXX`;
                  microsoftTeams.settings.setSettings({
                    entityID: "Test",
                    contentUrl: baseUrl + "/Home/SidePanel",
                    websiteUrl: baseUrl + "/Home/SidePanel",
                    suggestedTabName: "My Tab",
                  
                });
                saveEvent.notifySuccess();
           });
          microsoftTeams.settings.setValidityState(true);


![side panel](https://user-images.githubusercontent.com/93527375/158129444-02c8932d-d3b9-4d88-a037-479326c4f7a5.png)

**Comment by JerryYangKai** [comment]
@sayali-MSFT  Thanks! I will double check in my environment.
I still have two points, one is I am using the sample in nodejs, not the csharp.
Another point is in the toturial it has not explained the base url, is it the ngrok url or the localhost:3978? (Maybe it caused the fail)

**Comment by sayali-MSFT** [comment]
@JerryYangKai -I can modified the code sample as you mention above and then check it.
it is a localhost:3978 .
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-sidepanel/nodejs

**Comment by JerryYangKai** [comment]
> @JerryYangKai -I can modified the code sample as you mention above and then check it. it is a localhost:3978 . https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-sidepanel/nodejs

@sayali-MSFT  I found in my meetings, I can not call the localhost endpoint, using the ngrok endpoint I will see the page, so another question, which Teams version are you testing on?

**Comment by sayali-MSFT** [comment]
@JerryYangKai - Microsoft Teams Version 1.5.00.6771 (64-bit).

**Comment by sayali-MSFT** [comment]
@JerryYangKai -Could you please confirm if your issue has resolved or still looking for any help?

**Comment by JerryYangKai** [comment]
@sayali-MSFT  I have finally find what the problem is, inside the meeting, the side panel's content url can not be the localhost.
I changed to use ngrok endpoint or Azure website url works well.
Could you please double check it with the tech side? Why the localhost endpoint can not show in side panel.

**Comment by sayali-MSFT** [comment]
@JerryYangKai -Could you please share the manifest schema with the localhost URL, which you have tried?

**Comment by JerryYangKai** [comment]
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.12/MicrosoftTeams.schema.json",
  "version": "1.0.0",
  "manifestVersion": "1.12",
  "id": "07227802-f2c2-45ef-ab38-7f8d29c5d3a9",
  "packageName": "com.microsoft.teams.extension",
  "name": {
    "short": "TestMeetig0317-local-debug",
    "full": "TestMeetig0317-local-debug"
  },
  "developer": {
    "name": "Teams App, Inc.",
    "mpnId": "",
    "websiteUrl": "https://localhost:53000",
    "privacyUrl": "https://localhost:53000/index.html#/privacy",
    "termsOfUseUrl": "https://localhost:53000/index.html#/termsofuse"
  },
  "description": {
    "short": "Short description of TestMeetig0317-local-debug",
    "full": "Full description of TestMeetig0317-local-debug"
  },
  "icons": {
    "outline": "outline.png",
    "color": "color.png"
  },
  "accentColor": "#FFFFFF",
  "configurableTabs": [
    {
      "configurationUrl": "https://localhost:53000/index.html#/config",
      "canUpdateConfiguration": true,
      "scopes": [
        "team",
        "groupchat"
      ],
      "context": [
        "meetingChatTab",
        "meetingDetailsTab",
        "meetingSidePanel",
        "meetingStage"
      ]
    }
  ],
  "validDomains": [
    "localhost"
  ],
  "webApplicationInfo": {
    "id": "20ac6cb0-43e2-4e01-b3e2-105910c4dc15",
    "resource": "api://localhost/20ac6cb0-43e2-4e01-b3e2-105910c4dc15"
  }
}
```

**Comment by sayali-MSFT** [comment]
@JerryYangKai -As per my understanding ,
we need a tunneling service to route the paths globally that's why we use ngrok.
localhost will restrict to that machine only and will not expose that url globally.
I don't think it will be possible with localhost.

**Comment by JerryYangKai** [comment]
@sayali-MSFT  Thanks, that's helpful! I will close the issue.
