### ISSUE TITLE
How to use captureAudio.tsx file

### ISSUE THREAD

**Issue by 1mehmood0** [OfficeDev/Microsoft-Teams-Samples#277]
I am having trouble integrating the mentioned function into my teams app which is based on node.
Consider me as a beginner.

**Comment by Nivedipa-MSFT** [comment]
@1pervysage0 - Could you please share more details and which sample code you are referring?

**Comment by 1pervysage0** [comment]
@Nivedipa-MSFT  
samples/tab-device-permissions/nodejs/src/components/CaptureAudio.tsx

**Comment by Nivedipa-MSFT** [comment]
@1pervysage0 - Could you please share the error logs which you are getting?

**Comment by 1pervysage0** [comment]
@Nivedipa-MSFT  actually I am not able to compile because the file in typescript and I am using JavaScript. So there is always an error of some kind. I want to ask how will you proceed with the given code snippet and integrate it where? Which API will you use it to call that function? 

Assume that there is a task module opening from the messaging extension and the content within the iframe of task module is coming from different source website.

**Comment by Nivedipa-MSFT** [comment]
@1pervysage0 - For capturing audio you need to use media capability API's from Microsoft Javascript Teams SDK.
You can use **selectmedia** and **getmedia** API's

You can refer below javascript code for capturing audio.

```
let mediaInput: microsoftTeams.media.MediaInputs = {
    mediaType: microsoftTeams.media.MediaType.Audio,
    maxMediaCount: 1,
};
microsoftTeams.media.selectMedia(mediaInput, (error: microsoftTeams.SdkError, attachments: microsoftTeams.media.Media[]) => {
    if (error) {
        if (error.message) {
            alert(" ErrorCode: " + error.errorCode + error.message);
        } else {
            alert(" ErrorCode: " + error.errorCode);
        }
    }
    // If you want to directly use the audio file (for smaller file sizes (~4MB))    if (attachments) {
    let audioResult = attachments[0];
    var videoElement = document.createElement("video");
    videoElement.setAttribute("src", ("data:" + y.mimeType + ";base64," + y.preview));
    //To use the audio file via get Media API for bigger audio file sizes greater than 4MB        audioResult.getMedia((error: microsoftTeams.SdkError, blob: Blob) => {
    if (blob) {
        if (blob.type.includes("video")) {
            videoElement.setAttribute("src", URL.createObjectURL(blob));
        }
    }
    if (error) {
        if (error.message) {
            alert(" ErrorCode: " + error.errorCode + error.message);
        } else {
            alert(" ErrorCode: " + error.errorCode);
        }
    }
});
```
Ref Doc: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/mobile-camera-image-permissions#:~:text=%20Integrate%20media%20capabilities%20%201%20Advantage%20of,on%20the...%205%20Code%20snippets.%20%20More%20

**Comment by Nivedipa-MSFT** [comment]
@1pervysage0 - Could you please confirm if the above suggestion helped you in any way or are you still facing the issue?

**Comment by 1pervysage0** [comment]
Actually this is in typescript. How can i integrate the above function with JavaScript file?
Using it, server wont start.

**Comment by Nivedipa-MSFT** [comment]
@1mehmood0 - first you have to install the microsoft/teams-js package
You can install the package using npm or yarn:

```
npm install --save @microsoft/teams-js
yarn add @microsoft/teams-js
```
 reference the entire library using a script tag. There are three ways to do this:
```
<!-- Microsoft Teams JavaScript API (via CDN) -->
<script src="https://statics.teams.microsoft.com/sdk/v1.5.2/js/MicrosoftTeams.min.js" crossorigin="anonymous"></script>
 
<!-- Microsoft Teams JavaScript API (via npm) -->
<script src="node_modules/@microsoft/teams-js@1.5.2/dist/MicrosoftTeams.min.js"></script>

<!-- Microsoft Teams JavaScript API (copied local) -->
<script src="MicrosoftTeams.min.js"></script>
```
Then you can use this SDK functions.

Ref Doc: https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest

**Comment by Nivedipa-MSFT** [comment]
@1mehmood0 - Follow below steps:
1. Install the install the microsoft/teams-js package 
2. Reference the microsoft/teams-js library using a script tag in your javascript file.
3. Now you can directly use the microsoft/teams-js package functions in your javascript file like below:
`microsoftTeams.media.selectMedia()`

**Comment by 1mehmood0** [comment]
@Nivedipa-MSFT  I tried doing that but in iframe of task module on clicking the function invoking button, nothing happens.
I get the error of `DOMException: Permission Denied`

**Comment by Nivedipa-MSFT** [comment]
@1mehmood0 - Have you added devicePermissions property in manifest file like below?
```
"devicePermissions": [
    "media",
],
```

**Comment by 1mehmood0** [comment]
@Nivedipa-MSFT yes of course it was the fist thing I did.

**Comment by Nivedipa-MSFT** [comment]
@1mehmood0 - Could you please share your code zip file to check at our end?

**Comment by ChetanSharma-msft** [comment]
Hello @1mehmood0 - Hope you are doing well!!
Could you please confirm if your issue has resolved or still looking for any help?

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
