### ISSUE TITLE
nodejs hello world app crashes

### ISSUE THREAD

**Issue by asklar** [OfficeDev/Microsoft-Teams-Samples#284]
Followed the instructions in the docs: https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-nodejs?tutorial-step=2
the app crashes when running npm start:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/22989529/158904471-da6302be-fe6c-4886-b790-e1fbe499f7fa.png">

Changing package.json fixes the issue:
```diff
-    "start": "nodemon --exec babel-node src/app.js",
+    "start": "npx babel-node src/app.js",
```

**Comment by sayali-MSFT** [comment]
@asklar - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@asklar - If you are getting an error with npm install try deleting package-lock.json and re-running npm install.
Reference sample doc:-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-hello-world/nodejs

**Comment by sayali-MSFT** [comment]
@asklar -Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by asklar** [comment]
the problem isn't with npm install, it's when starting the app. npm start calls babel-node, which is deprecated

**Comment by sayali-MSFT** [comment]
@asklar -We are unable to repro the issue.It's working fine for us. If you still facing issue please follow the steps:-

Remove your node_modules and follow these steps:

` npm install --save-dev @babel/core @babel/cli @babel/preset-env @babel/node`

Then, check the existence of these files:

node_modules/.bin/babel-node

node_modules/.bin/babel-node.cmd - windows only

node_modules/@babel/node/bin/babel-node.js

If everything looks good add to package.json:

`"start": "nodemon --exec babel-node index.js"`

![localhost](https://user-images.githubusercontent.com/93527375/160380048-95e17329-d039-493d-8993-f67bfdd1b7d9.png)

**Comment by sayali-MSFT** [comment]
@asklar -Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by ChetanSharma-msft** [comment]
Hello @asklar - Hope you are doing well!!
Could you please confirm if your issue has resolved or still looking for any help?

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
