### ISSUE TITLE
RSC "ChannelMessage.Read.Group" doesn't work with Teams app manifest v1.12

### ISSUE THREAD

**Issue by timoleo23** [OfficeDev/Microsoft-Teams-Samples#299]
Hi, the definition of the Teams App Manifest is not correct.

Based on the offcial documentation the JSON format to enable RSC permissions is different between v1.11 and v1.12+
https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent#update-your-teams-app-manifest

This sample uses the manifest version v1.12 with the schema definition of v1.11 and before = it generates a manifest parsing error when uploading the app in Teams.

Also, when using v1.12 definition, we don't receive the messages: **it doesn't work**.

We need to use v1.11 and the associated shema definition.
Here is what's working:
```json
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
    "version": "1.0.0",
    "manifestVersion": "1.11",
    ...
    "webApplicationInfo": {
      "id": "5278c93e-XXX-XXXX-xxxx-6ce34ff25f13",
      "resource": "https://RscBasedStoreApp",
      "applicationPermissions": [
        "ChannelMessage.Read.Group"
      ]
    }
}
```

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will update you.

**Comment by Jenscaasen** [comment]
Can confirm: 1.12 does not allow the webApplicationInfo node in the schema. Reverting to 1.11 as shown by @timoleo23  fixes the problem.

**Comment by Meghana-MSFT** [comment]
@timoleo23 - We already have a bug raised for this issue, and the team is working on it. I will keep you posted on the updates.

**Comment by timoleo23** [comment]
Hi @Meghana-MSFT, do we have an update or ETA on this issue? Thanks

**Comment by timoleo23** [comment]
Hi @Meghana-MSFT , do we have an update or ETA on this issue?

**Comment by Meghana-MSFT** [comment]
Currently we do not have any ETA to share, I will keep you posted.

**Comment by Meghana-MSFT** [comment]
@timoleo23 - We see that bot is responding without @mention as well for 1.12 version as well. Can you please check and confirm once?

**Comment by Meghana-MSFT** [comment]
@timoleo23 - We see that bot is responding without @mention as well for 1.12 version as well. Can you please check and confirm once?

**Comment by ChetanSharma-msft** [comment]
@timoleo23 - Hope you are doing well!!
Could you please confirm if your issue has resolved or still looking for any help?

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you have any questions. Thank you.
