### ISSUE TITLE
Missing step in configuring the messaging endpoint for meeting event sample

### ISSUE THREAD

**Issue by jenny0322** [OfficeDev/Microsoft-Teams-Samples#304]
Hi, 
I followed the steps in the meetings events sample and my bot did not work. 
Upon investigation, I realized that there is an additional step after where I have to configure the messaging endpoint in the portal (e.g .ngrok address/api/messages). 
<img width="740" alt="Screen Shot 2022-04-08 at 11 12 51 AM" src="https://user-images.githubusercontent.com/5885069/162498515-59f3a0ea-b178-4024-a01e-19f716459049.png">

**Comment by sayali-MSFT** [comment]
@jenny0322 - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@jenny0322 - Changes are done in document as per requirement.
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-events

**Comment by sayali-MSFT** [comment]
@jenny0322 -We are closing this issue for now, Please feel free to reopen it, if required.
