### ISSUE TITLE
Tab-DeepLink CSharp does not work out of the box

### ISSUE THREAD

**Issue by eoinobrien** [OfficeDev/Microsoft-Teams-Samples#310]
I've been looking at deep links and wanted to verify my assumptions using https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-deeplink/csharp.

The sample seems incomplete. Some things I have noticed:
* The code and the README mention Channels tabs, but the manifest has no tabs with `team` scope
* After installing the app in a Team, I mentioned the bot, the returned links do not link anywhere (because there is no tab)
* Tabs in the personal scope point to the root ngrok url, which has nothing hosted so returns an error

**Comment by sayali-MSFT** [comment]
@eoinobrien - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@eoinobrien -We are tried this sample with our end it's working fine. need to do changes in manifest json.

**Comment by eoinobrien** [comment]
Thanks @sayali-MSFT.

Something else that I noticed when I got things working was that the deep linking from the channel posts to the tab doesn't work.

I've attached a video below showing this. Notice how when I click on the link in the card, the view refreshes but we are not navigated to the tab or subentity.
https://user-images.githubusercontent.com/6508687/164506171-2765d2ad-a2a8-4dcc-805e-27b1178137a1.mp4

I think this might be an issue in the deep link code directly, (I've asked a question of the docs folks: https://github.com/MicrosoftDocs/msteams-docs/issues/5768)

**Comment by sayali-MSFT** [comment]
@eoinobrien - shall we close the issue if your issue is resolved? For the [second issue](https://github.com/MicrosoftDocs/msteams-docs/issues/5768) we will track it there only.

**Comment by eoinobrien** [comment]
@sayali-MSFT My issue is resolved, but can you be sure to track the work required, so others can use this sample without having to make the required changes to the manifest file

**Comment by sayali-MSFT** [comment]
@eoinobrien -Sure.
