### ISSUE TITLE
Microsoft-Teams-Samples\samples\tab-personal Package extraction failed

### ISSUE THREAD

**Issue by chenzuo** [OfficeDev/Microsoft-Teams-Samples#312]
Microsoft-Teams-Samples\samples\tab-personal
![image](https://user-images.githubusercontent.com/10744915/165203566-8e78ffd7-84eb-4b7b-a316-1d57a0c5650a.png)
'{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.12/MicrosoftTeams.schema.json",
  "manifestVersion": "1.12",
  "id": "1aaaaaaa-2bbb-3333-4ccc-5ddddddddddd",
  "version": "1.0.0",
  "packageName": "com.custom.tab",
  "developer": {
    "name": "Contoso",
    "websiteUrl": "https://teams.xxxx.cn",
    "privacyUrl": "https://teams.xxxx.cn/privacy",
    "termsOfUseUrl": "https://teams.xxxx.cn/",
    "mpnId": ""
  },
  "name": {
    "short": "Tab",
    "full": "PersonalTab"
  },
  "description": {
    "short": "short description here",
    "full": "full description here"
  },
  "icons": {
    "outline": "icon-outline.png",
    "color": "icon-color.png"
  },
  "accentColor": "#D85028",
  "configurableTabs": [],
  "staticTabs": [],
  "bots": [],
  "connectors": [],
  "composeExtensions": [],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "toDo.ngrok.io"
  ]
}'
the package : [tab.zip](https://github.com/OfficeDev/Microsoft-Teams-Samples/files/8559085/tab.zip)

**Comment by sayali-MSFT** [comment]
@chenzuo -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@chenzuo -We are unable to repro the scenario.It's working fine from our end. Looks like issue with packages.
Could you please try with the following manifest json?
[manifest.zip](https://github.com/OfficeDev/Microsoft-Teams-Samples/files/8562646/manifest.zip)
![image](https://user-images.githubusercontent.com/93527375/165288573-c4a0bfaa-598b-4b47-9ba2-cc3a624360ec.png)

**Comment by sayali-MSFT** [comment]
@chenzuo - Did you get chance to check with the above manifest json?

**Comment by chenzuo** [comment]
copy that, i will redo follow the document.if have any questions i'll push the issues on here,please wait while. thanks lot .

**Comment by chenzuo** [comment]
![image](https://user-images.githubusercontent.com/10744915/165880501-a4962f58-4f57-42b4-a550-698f21489242.png)
It works perfectly,thank you very much.
I would suggest you modify the source and replace it use correct json as well...
I am very surprised that this project is still supported, very very unexpected. :)
