### ISSUE TITLE
meetings-sidepanel and meetings-stage-view crash within 10 seconds

### ISSUE THREAD

**Issue by greyoy** [OfficeDev/Microsoft-Teams-Samples#324]
Using both preview and publish to organisation, the add-in will load, click "add to a meeting", select meeting, wait for configure page, click save.

The add-in now loads, then within ten second the page crashes, closes and get removed from the tab menu. The add-in remains installed but you cannot re-open or find the tab to re-open the panel.

Why?

**Comment by sayali-MSFT** [comment]
@greyoy - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@greyoy - Could you please check it once with updated teams version?
Microsoft Teams Version 1.5.00.12910 (64-bit)

If not working then you need to add following Context in configuration Tab section in manifest json -
` "context": [
        "meetingSidePanel",
        "meetingChatTab",
        "meetingDetailsTab"
      ]`

**Comment by tinsheep** [comment]
@sayali-MSFT FYI this is working for me after adding the additional contexts

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
