### ISSUE TITLE
 integrate Microsoft teams meeting room function

### ISSUE THREAD

**Issue by zsoftbuilder** [OfficeDev/Microsoft-Teams-Samples#328]
Our springboot system needs to integrate Microsoft teams meeting room function, is what we need in our springboot system to add the function of the meeting, what should I do?Have related demo?

**Comment by sayali-MSFT** [comment]
@zsoftbuilder -Are you developing Microsoft Teams APP?

**Comment by zsoftbuilder** [comment]
Not the APP, just in the existing springboot system integration teams function

**Comment by sayali-MSFT** [comment]
@zsoftbuilder - Please have look at this document-
1.https://docs.microsoft.com/en-us/microsoftteams/rooms/third-party-join?msclkid=36a9b9cfd11b11eca80f4e8eee634858
2.https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-deploy?msclkid=36aa938fd11b11ec93ccb4bd108cc66b

**Comment by sayali-MSFT** [comment]
@zsoftbuilder - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
