### ISSUE TITLE
The `LangVersion` should be specified with a constant instead of `latest`

### ISSUE THREAD

**Issue by Jandev** [OfficeDev/Microsoft-Teams-Samples#333]
The projects have a target framework of `netcoreapp3.1` and a `LangVersion` stated to `latest`.

However, as time progresses, the `latest` will point to versions which aren't supported by .NET Core 3.1.
At the moment the `Microsoft.Teams.Samples.HelloWorld.Web` project doesn't work after cloning, when the developer has the latest bits (VS2022, .NET 6/7, etc.) installed.

As shown in [this SO answer](https://stackoverflow.com/a/70665021/352640), the latest version supported by .NET Core 3.1 is 8.0.

Therefore, we should change the language version of all projects to point towards 8.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>8</LangVersion>
  </PropertyGroup>
  
</Project>
```
Changing this will make sure the projects are able to build proper.

**Comment by Nivedipa-MSFT** [comment]
@Jandev - We are checking this internally. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue as of now. Please feel free to reopen if required.
