### ISSUE TITLE
'something went wrong in ProcessInvoke' 502 error

### ISSUE THREAD

**Issue by wheelie33** [OfficeDev/Microsoft-Teams-Samples#334]
Built a messaging extension that opens a task module.  When a user creates a brand new chat that is in "draft" mode, the application launch gets a 502 error.  We tested this with another app (Starbucks) and they have the same issue.

There's almost nothing we can find in any documents that help us troubleshoot besides telling our client "Send a message first"

If you type a message and send to the person you are chatting with, the app will then launch perfectly normal.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/17298183/168314783-948c2231-93eb-4888-a369-df4b44362bd9.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/17298183/168314929-26f026df-6b83-46ef-a26c-889914f0a66b.png">

**Comment by Meghana-MSFT** [comment]
We are looking into this issue, we will get back to you.

**Comment by Meghana-MSFT** [comment]
We are able repro this issue. We have raised a bug for the same and we will keep you posted on the updates.

**Comment by Meghana-MSFT** [comment]
@wheelie33 - We are not able to repro this issue now. Can you please check and confirm once?

**Comment by wheelie33** [comment]
We will test this in our upcoming cycle this week.  Thank you

**Comment by Meghana-MSFT** [comment]
Can you please check if you are able to repro this issue and confirm once?

**Comment by ChetanSharma-msft** [comment]
Hello @wheelie33 - Hope you are doing well!!
Could you please confirm if your issue has resolved or still looking for any help?

**Comment by wheelie33** [comment]
Yes, thank you.  seems to work properly now.

**Comment by Meghana-MSFT** [comment]
Thank you for confirming. We will close the question. Please feel free to reach out if you have any issues. Thank you.
