### ISSUE TITLE
Manifest files updated to v1.12 without changing applications permissions parameter, breaks RSC samples

### ISSUE THREAD

**Issue by eoinobrien** [OfficeDev/Microsoft-Teams-Samples#362]
Hi,

This PR #296 updated the manifest version of a bunch of Apps but it has now broken apps that use RSC permissions.

The manifest schema changed between v1.11 and v1.12 (https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent#manifest-changes-for-resource-specific-consent).

And instead of using
```json
"webApplicationInfo": {
    "id": "XXxxXXXXX-XxXX-xXXX-XXxx-XXXXXXXxxxXX",
    "resource": "https://RscBasedStoreApp",
    "applicationPermissions": [
        "TeamSettings.Read.Group"
    ]
}
```

you use:
```json
"authorization": {
    "permissions": {
        "resourceSpecific": [
            {
                "name": "TeamSettings.Read.Group",
                "type": "Application"
            }
        ]
    }
}
```

The samples with issues are 
* meetings-events/nodejs
* ‎meetings-events/csharp
* bot-receive-channel-messages-withRSC/nodejs
* bot-receive-channel-messages-withRSC/csharp

Can we either revert the manifest version or preferably update them to the correct schema?

Thanks

**Comment by Meghana-MSFT** [comment]
Thank you for providing the feedback, we will look into it and make changes if necessary.

**Comment by Meghana-MSFT** [comment]
@eoinobrien - The team is looking into it and will make necessary updates to the samples.

**Comment by Meghana-MSFT** [comment]
@eoinobrien - The samples have been updated correctly.

**Comment by Meghana-MSFT** [comment]
Thanks for confirming. Please feel free to reach out to us if you face any issue. Thank you.
