### ISSUE TITLE
SSO example full of deprecated features

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/Microsoft-Teams-Samples#371]
I am following the Teams SSO tutorial which refers to this repository

https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-tabs-and-messaging-extensions-with-sso

I believe it wants you to use this project, although it is not clear: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso/csharp/App%20SSO%20Sample

I notice there is a bunch of obsolete features being used, such as DialogManager and AzureADOptions

Can this example please be updated to reflect the current state of the library?

**Comment by Prasad-MSFT** [comment]
Thanks for reporting. We will redirect this to appropriate team and will get it updated accordingly.

**Comment by Prasad-MSFT** [comment]
We are checking it. We will get it updated accordingly.

**Comment by Prasad-MSFT** [comment]
We have taken this into consideration and team is working to update the sample. We will notify you once its completed. Thanks!

**Comment by ChetanSharma-msft** [comment]
Here is the PR link: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/423

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
