### ISSUE TITLE
Outgoing webhook not working

### ISSUE THREAD

**Issue by tojuasp** [OfficeDev/Microsoft-Teams-Samples#377]
Trying to implement a outgoing webhook for Teams. Using the sample code and ngrok for routing. Localhost correctly receives the call, formulates the correct response and seems to return but the Outgoing webhook "bot" still responds: "Sorry, there was a problem encountered with your request" in the response thread at Teams.

**Comment by Prasad-MSFT** [comment]
Could you please refer this sample and check if it helps?
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/outgoing-webhook/csharp

**Comment by Prasad-MSFT** [comment]
Is your issue resolved or are you still looking for any help?

**Comment by tojuasp** [comment]
The C# sample seems to work. Would be nice to understand the why the other one does not and what is the actual requirement to get this working with a custom solution? I tried to do just as the documentation asked but no-go. 

This C# sample return payload just seems to include a lot of null fields, are those the ones that are actually required?

**Comment by tojuasp** [comment]
Actually it seems it was a ngrok thing... I had wrong authentication information on my other machine where I tested nodejs sample. Ngrok didn't say anything, it just looked like it worked just fine. After updating the authentication token, nodejs sample started to work as well.
