### ISSUE TITLE
Cannot create Azure bot - Cannot create a v2 converged app.

### ISSUE THREAD

**Issue by st1992** [OfficeDev/Microsoft-Teams-Samples#379]
<img width="1487" alt="Screenshot 2022-06-24 at 11 26 13 AM" src="https://user-images.githubusercontent.com/42057594/175472704-c95d314d-0d4f-4ab9-9f8b-ec4a7ac74904.png">

**Comment by st1992** [comment]
The validation has passed but not able to create the app, this is really frustrating.

**Comment by ChetanSharma-msft** [comment]
@st1992 - Can you please let us know the exact sample that you are following and getting this error?

**Comment by Dimitrispant** [comment]
I also face the same issue and I cannot figure out what is going wrong. Any thoughts? @ChetanSharma-msft in my case I deployed my kb in language studio and after that I followed these steps provided here:
https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/tutorials/bot-service

**Comment by Nivedipa-MSFT** [comment]
@st1992 - Can you please let us know the exact sample or steps that you are following and getting this error?

**Comment by Nivedipa-MSFT** [comment]
@st1992 - Is above documnet helped you in any way or are you still facing this issue? If yes could you please share the repro steps?

**Comment by ChetanSharma-msft** [comment]
> I also face the same issue and I cannot figure out what is going wrong. Any thoughts? @ChetanSharma-msft in my case I deployed my kb in language studio and after that I followed these steps provided here: https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/tutorials/bot-service

The Azure Web App Bot and Bot Channels Registration resource types are deprecated.
So to create a bot service, we have to use Azure bot in Azure portal.

Please try to create it again and let us know whether you are still facing the issue?

**Comment by briceglase** [comment]
@ChetanSharma-msft I tackled the issue by creating an App Service plan (Windows not Linux) then referencing it when creating the bot

**Comment by ChetanSharma-msft** [comment]
@st1992 - Every resource in Azure is associated with a App service plan. 
So, please create the App Service plan first and then try to create your resources.

**Comment by ChetanSharma-msft** [comment]
Hello @st1992 - Hope you are doing well!!
Could you please confirm if your issue has resolved or still looking for any help?

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you have any questions. Thank you.
