### ISSUE TITLE
education 

### ISSUE THREAD

**Issue by m-sebteahmadi** [OfficeDev/Microsoft-Teams-Samples#389]
https://www.linkedin.com/posts/microsoft-education_swipe-for-a-surprise-activity-6948672600013246464-chFx?utm_source=linkedin_share&utm_medium=android_app

**Comment by m-sebteahmadi** [comment]
Education

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
