### ISSUE TITLE
How to support two teams bots in one api service?

### ISSUE THREAD

**Issue by 298029lkk** [OfficeDev/Microsoft-Teams-Samples#395]
As an example, I have two teams bot application, bot A and bot B.And both bots create AAD.
bot A------>Azure AD 1
bot B------>Azure AD 2

Now I want to use the same service for both bot apps, instead of creating 2 services.
Can it be done please?

**Comment by 298029lkk** [comment]
As far as I know, Azure AD information is configured in appsetting, and its authentication is also implemented by the framework.
I don't know how to modify it.

**Comment by Prasad-MSFT** [comment]
@298029lkk - No you can't use same service. A single service is configured to single Azure AAD.

**Comment by 298029lkk** [comment]
@Prasad-MSFT Ok, thanks for your reply. Is this limited by the framework? Is it possible to extend it in the future?
Because I'm currently facing this problem. I have multiple bot apps, but I want to share a service.

**Comment by Prasad-MSFT** [comment]
@298029lkk - Yes its limited by the framework. There is no information/plan to extend it in the future.

**Comment by 298029lkk** [comment]
@Prasad-MSFT Ok, thanks.
