### ISSUE TITLE
Change Notification Adaptive Card Issue

### ISSUE THREAD

**Issue by aarontumambing** [OfficeDev/Microsoft-Teams-Samples#413]
Hi everyone,

I am having an issue trying to click the "Sign in" card. I believe I followed the steps correctly. Instead of using ngrok, I published the code to the azure web service.

this is the error when I click "Sign in"
![image](https://user-images.githubusercontent.com/86734163/181600071-b19fa006-e042-4476-81c5-6ac30015127f.png)

I created the OAuth and plugged it in the "ConnectionName" in appsettings.json

please let me know any of my oversights.
thank you!

**Comment by ChetanSharma-msft** [comment]
@aarontumambing - Thanks for reporting this issue.
We will check on it and get back to you.

**Comment by sayali-MSFT** [comment]
@@aarontumambing - You need to create a manifest and include token.botframework.com in the validDomains section; otherwise the OAuthCard Sign in button will not open the authentication window. Use the [App Studio](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio) to generate your manifest.

Reference doc-https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp#adding-teams-authentication

We got the related thread-https://techcommunity.microsoft.com/t5/teams-developer/oauth-not-working-in-teams/m-p/3356135#M5519

**Comment by aarontumambing** [comment]
@sayali-MSFT thank you for the information.

i added token.botframework.com to the manifest, zipped it, then imported the manifest to teams.
after waiting a few mins, the Microsoft sign in button appeared. After clicking the button, the bot replied with:
![image](https://user-images.githubusercontent.com/86734163/181762527-e00849d1-91e4-44d6-bf5f-3d9b7a727ded.png)


now the bot doesnt give me the card anymore and continuously gives me the error message.

I believe i didn't change the source code... any idea what this could be?

thank you!

**Comment by sayali-MSFT** [comment]
Could you please share the Error log?
There is a 10 or 15 second timeout that can occur, and if it does then I think that would cause what you're seeing.
See more at https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0

**Comment by aarontumambing** [comment]
@sayali-MSFT  this is the error
![image](https://user-images.githubusercontent.com/86734163/181810043-196b3561-830c-41ec-9179-3e0ee522529b.png)

**Comment by ChetanSharma-msft** [comment]
Hello @aarontumambing - This looks like some timeout error, can you please share the console error logs from your browser client?
Also, can you please try with the mentioned sample in below doc?
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample#prerequisites

**Comment by aarontumambing** [comment]
hi @ChetanSharma-msft 

I'm not sure how to share error logs when its deployed in a web server. Could you tell me how to do that?
we're not allowed to run a tunneling software so instead, we upload our program to azure web service

The sample you provided works for me
![image](https://user-images.githubusercontent.com/86734163/182167590-a96fa91f-f148-4977-b5ba-044e6926f40f.png)

**Comment by ChetanSharma-msft** [comment]
@aarontumambing - Thanks for the confirmation.
Looks like some configuration issues in your web server or the configured URL's are not properly accessible.
Please check the configuration and try it once.

I am not sure but please check in your web server for error logs.

**Comment by sayali-MSFT** [comment]
@aarontumambing -Did you get chance to check?

**Comment by aarontumambing** [comment]
hello @ChetanSharma-msft  @sayali-MSFT 

Can you give me a specific area to look at? when you gave me the other sample, all the configuration changes I did was on the appsettings.json file and published the code onto the same resource group.
![image](https://user-images.githubusercontent.com/86734163/182367907-75d85729-f420-4d9c-a1ec-03c276f80efb.png)

**Comment by sayali-MSFT** [comment]
@aarontumambing -Teams auth sample is working fine from our end.

**Comment by aarontumambing** [comment]
@sayali-MSFT yes the teams auth sample also works for me, what about the change notification sample?

https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-change-notification/csharp

**Comment by sayali-MSFT** [comment]
@aarontumambing -We will try it from our end and let you know.

**Comment by sayali-MSFT** [comment]
@aarontumambing -Did you get chance to check?

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
