### ISSUE TITLE
bot-calling-meeting not launching

### ISSUE THREAD

**Issue by JulianJoachim** [OfficeDev/Microsoft-Teams-Samples#424]
Hello everyone,

I hope this is the right place to ask such a question. I've been following [this ](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-calling-and-meeting) guide to create a calling-meeting bot. I had some issues along the way but eventually managed to roughly understand whats going on and got through everything without errors - up until I build the manifest.zip and tried to add it to teams. No errors appeared, but the bot is unable to do anything. For the past few days Ive done everything I possible could imagine (including redoing ALL of the steps on another computer), but I just cant figure out what Im doing wrong.

To clarify:

1. I follow the steps from the guide mentioned above and receive a manifest.zip
2. I launch ngrok with ngrok http --host-header=rewrite 3978
3. I launch the "bot-calling-meeting" sample which has my edited manifest.json aswell as my edited appsettings.json
4. I upload it to teams or try using the Bot Framework Emulator to get any signs of life but it this fails.

What I personally just cannot understand is why Im supposed to tunnel the port 3978 for ngrok? When I launch the sample bot I get the following: 
![image](https://user-images.githubusercontent.com/65426326/182870217-c385e1b8-235d-4e94-9487-040e32b53ede.png)

And this web-page opens on its own: 
![image](https://user-images.githubusercontent.com/65426326/182870402-dad6ef13-b7f2-4207-8202-85f7225d8654.png)

Here it says once again to connect to http://localhost:3978/api/messages, but in the sample code available here, this port is not mentioned once besides on this very webpage (which is just a plain html text).

In short: My bot cant be reached whatsoever and I dont understand why. The guide tells me to use port 3978 for tunneling but I cant comprehend how this port is ever used. I also dont understand why its instead launching port 5000 and 5001, because I havent seen this port being used at all in the guide or anywhere else.

Lastly Id like to mention that accessing localhost:5001/api/messages gives me the following: 
![image](https://user-images.githubusercontent.com/65426326/182871958-95355912-3c4c-40da-b2d1-b73704badcd2.png)

sadly, even when using localhost:5001/api/messages it doesnt seem to work. 
![image](https://user-images.githubusercontent.com/65426326/182873654-114cca84-6b02-4dea-8a86-1cb27a02c924.png)

I feel like Im just missing something very simple that I however cant figure out myself, so Id deeply appreciate any help! Thanks.

Lil Update: when using the Bot Framework-Emulator on https://localhost:5001/api/messages I indeed get the "welcome to bot" message - however thats all it does and adding it to teams still does nothing. And something else I noticed: I cannot open the URL I forwarded with ngrok, which afaik should be possible:
![image](https://user-images.githubusercontent.com/65426326/182892857-2677d5fd-7a43-48ad-a58f-e9fc41eae4de.png)

**Comment by sayali-MSFT** [comment]
@JulianJoachim -We are looking into this we will get back to you soon.

**Comment by Nivedipa-MSFT** [comment]
@JulianJoachim - You have to run the ngrok on port 5001 or change the port number as 3978 in launchSetting.json.

**Comment by JulianJoachim** [comment]
@Nivedipa-MSFT as said at the bottom, updated part of my question, Ive tried that already.

Accessing the bot then works, but ONLY in the tab opened by running the code. If I go to any other tab or use the forwarded ngrok url (e. g. https://5b26-2a02-8109-9a40-29e4-8d57-acf4-5d4b-b7aa.eu.ngrok.io), I always meet some kind of error. This is probably also why my bot wont respond at all.

I really sticked to what the guide said, and it already misled me with the port issue, so I wonder if there may be something else I have to do thats not mentioned in the guide.

Feel free to check out the error I get on your own at https://5b26-2a02-8109-9a40-29e4-8d57-acf4-5d4b-b7aa.eu.ngrok.io/

On that note, it would be great if, for the future, you could edit the code to instantly launch port 3978. Its unneccesarily complicated that the whole guide is based on port 3978 and suddenly you have to figure out on your own that the sample code doesnt actually use it. Even in the samples' own readme it says port 3978.

**Comment by Nivedipa-MSFT** [comment]
@JulianJoachim - Thanks for your feedback. We will update the port number in launchSetting.json. 
We will let you know once its updated.

**Comment by Nivedipa-MSFT** [comment]
@JulianJoachim - Are you running this code with IIS express?

**Comment by JulianJoachim** [comment]
@Nivedipa-MSFT I am not, Ive tried to do so in the past but it always launched with a 44346 port which seemed wrong to me. Should I be using IIS express?

**Comment by Nivedipa-MSFT** [comment]
@JulianJoachim - Could you please check by using Profile CallingBotSample?
Also update the applicationURI  of CAllingBotSample profile to http://localhost/:3978.

**Comment by JulianJoachim** [comment]
@Nivedipa-MSFT Unfortunately I already did both of those things. Ive tried IIS Express once in the beginning but have only been using the CallingBotSample profile for the last few days.

My launchSettings.json looks as such:

![image](https://user-images.githubusercontent.com/65426326/183077152-ed741ca9-0a94-416a-963a-fafcc9219a7f.png)

**Comment by JulianJoachim** [comment]
Oh. I think I found the problem... In the original launchSettings.json it said "https://localhost:5001" which I simply edited to 3978... I however didnt notice it was using http**s** instead of normal http. Will try it without now.

**Comment by JulianJoachim** [comment]
It seems like this was the only problem for now. Thanks for your assistance!

**Comment by JulianJoachim** [comment]
@Nivedipa-MSFT, sorry for re-opening this thread but I got another difficulty I'm facing and cant seem to find anything online:

I want my bot to run 24/7. Currently, I have to run the code aswell as ngrok on my local machine. The biggest problem here: I always have to update both my code aswell, aswell as the messaging endpoint in the azureportal. Surely theres a better way to do this. Would appreciate if you could give me some instructions, sample code or some online ressources to help me here.

**Comment by Nivedipa-MSFT** [comment]
@JulianJoachim - We are checking this internally. We will update you soon.

**Comment by JulianJoachim** [comment]
Ive found a solution that seems to work myself and this no longer is a priority, closing this.
