### ISSUE TITLE
Cannot GET /api/request

### ISSUE THREAD

**Issue by yingying96** [OfficeDev/Microsoft-Teams-Samples#426]
Hi Team,

I'm getting the error `Cannot GET /api/request`
It is happening for both localhost (http://localhost:3978/api/request) and the ngrok url on my teams app.

**Error message on teams, same as the error on localhost**
![image](https://user-images.githubusercontent.com/19566726/183410234-09de8a39-1884-4f00-8bcf-81d19936da84.png)

**Here's the app details**

![image](https://user-images.githubusercontent.com/19566726/183394169-e12b39d2-d75d-4f32-b07a-1b4b12252d85.png)

![image](https://user-images.githubusercontent.com/19566726/183394227-b36ebf69-ef7d-4116-999f-7ab920cb60a6.png)

![image](https://user-images.githubusercontent.com/19566726/183394276-d93c493a-dc49-4e94-85aa-db8ced572b02.png)

**Comment by Nivedipa-MSFT** [comment]
@yingying96 - We are investigating your query. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@yingying96 - Could you please confirm is your issue resolved or are you still facing the issue?

**Comment by Nivedipa-MSFT** [comment]
@yingying96 - Could you please change the **tabAuth** to **TabAuth** in redirect URI's of single page application and check again?

**Comment by yingying96** [comment]
Thanks for the reply. Yes i have changed.

![image](https://user-images.githubusercontent.com/19566726/185395314-42e2aefa-e69a-4b61-b7aa-af8628977ee3.png)


![image](https://user-images.githubusercontent.com/19566726/185395257-507817a7-36fe-46a1-bf57-b61ad869c35e.png)

**Comment by Nivedipa-MSFT** [comment]
@yingying96 - Could you please verify your configuration settings as per [readme](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-request-approval/csharp/README.md) file?

**Comment by yingying96** [comment]
Do you mean the manifest.xml? 

```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.12/MicrosoftTeams.schema.json",
 "manifestVersion": "1.12",
  "version": "1.0.2",
  "id": "340919fe-072f-48df-8591-d80c42915311",
  "packageName": "com.microsoft.teams.tabrequestapproval",
  "developer": {
    "name": "Microsoft",
    "websiteUrl": "https://www.teams.com",
    "privacyUrl": "https://www.teams.com/privacy",
    "termsOfUseUrl": "https://www.teams.com/termsofuse"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Tab Request Approval",
    "full": "Activity feed notification to notify about approval request."
  },
  "description": {
    "short": "App helps user to raise a request and notify manager for approve or reject it.",
    "full": "This is an Tab app where requester can raise a request and a notification send to manager for its approval or rejection."
  },
  "accentColor": "#235EA5",
  "staticTabs": [
    {
      "entityId": "request",
      "name": "Request",
      "contentUrl": "https://eb68-124-197-112-6.ap.ngrok.io/request",
      "websiteUrl": "https://eb68-124-197-112-6.ap.ngrok.io/request",
      "scopes": [
        "personal"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "wvv0z.onmicrosoft.com"
  ],
  "activities": {
    "activityTypes": [
      {
        "type": "approvalRequired",
        "description": "Required approval",
        "templateText": "A task created with title {approvalTaskId}"
      }
    ]
  },
  "webApplicationInfo": {
    "id": "340919fe-072f-48df-8591-d80c42915311",
    "resource": "api://eb68-124-197-112-6.ap.ngrok.io/340919fe-072f-48df-8591-d80c42915311"
  }
}
```

**Comment by Nivedipa-MSFT** [comment]
@yingying96 - Have you run the solution of tab request sample?

**Comment by yingying96** [comment]
Yup

![image](https://user-images.githubusercontent.com/19566726/185397998-6a0344c6-190b-4e0a-a4d6-b97e7009725b.png)

**Comment by Nivedipa-MSFT** [comment]
@yingying96 - Could you please try with the C# sample once. Meanwhile we will test nodejs sample and update you.

**Comment by Nivedipa-MSFT** [comment]
@yingying96 - For nodejs sample you have to do following changes.
1. In manifest change request to UserRequest.
![image](https://user-images.githubusercontent.com/92150070/185617999-26e84af4-d026-4ab8-8d3b-71538e3bc451.png)

2.  change the TabAuth to tabAuth in redirect URI's of single page application.

Please check and let us know if it's working or not.

**Comment by yingying96** [comment]
Updated! 

![image](https://user-images.githubusercontent.com/19566726/185733647-748a9dd2-0b31-4861-9a94-d087aa96ba78.png)


![image](https://user-images.githubusercontent.com/19566726/185733652-cb91a2f8-2bd9-47e5-907d-47848d51efd0.png)

**Comment by Nivedipa-MSFT** [comment]
@yingying96 - We have tested nodejs sample and we are also getting same error. We are checking this internally. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@yingying96 - We have updated UserNotification instead of UserRequest and we are getting request page now.

![image](https://user-images.githubusercontent.com/92150070/186393950-8648d28d-cb77-4aba-ad41-1c10cb4ee9ff.png)

We will raise the PR for changes in manifest for sample.

**Comment by ChetanSharma-msft** [comment]
@yingying96 - We have merged the fixes. [PR link: ](https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/445)

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
