### ISSUE TITLE
Error Building Microsoft.Teams.Samples.HelloWorld.Web on Mac

### ISSUE THREAD

**Issue by haacked** [OfficeDev/Microsoft-Teams-Samples#43]
I'm following the instructions here: https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio.

When I build, I get the following error:

> Microsoft.Teams.Samples.HelloWorld.Web.csproj(28, 7): [MSB3073] The command "pwsh Compress-Archive -Path \"/Users/haacked/dev/aseriousbiz/Microsoft-Teams-Samples/samples/app-hello-world/csharp/Microsoft.Teams.Samples.HelloWorld.Web/Manifest/*/" -DestinationPath /"/Users/haacked/dev/aseriousbiz/Microsoft-Teams-Samples/samples/app-hello-world/csharp/Microsoft.Teams.Samples.HelloWorld.Web/bin/Debug/netcoreapp3.1/helloworldapp.zip\" -Force" exited with code 64.

[This line is the culprit](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/app-hello-world/csharp/Microsoft.Teams.Samples.HelloWorld.Web/Microsoft.Teams.Samples.HelloWorld.Web.csproj#L28):

```xml
<Exec Command="powershell.exe Compress-Archive -Path \&quot;$(ProjectDir)Manifest\*\&quot; -DestinationPath \&quot;$(TargetDir)helloworldapp.zip\&quot; -Force" />
```

**Comment by haacked** [comment]
I should mention I'm using Rider on a Mac. I am trying to build the Solution.

**Comment by haacked** [comment]
```xml
      <Exec Command="pwsh -Command Compress-Archive -Path &quot;$(ProjectDir)Manifest/*&quot; -DestinationPath &quot;$(TargetDir)helloworldapp.zip&quot; -Force" />
```

Changing it to this worked for me on Mac OS after installing powershell via `brew install powershell`. I assume it'll work for Windows too.

**Comment by Wajeed-msft** [comment]
Hi @haacked - I'll check this in Windows once and could update the sample.

**Comment by Wajeed-msft** [comment]
Hi @haacked - would you like to contribute to it by raising the PR for it? Otherwise, I'll make the change sometimes this week.

**Comment by haacked** [comment]
I'll give it a quick try.

**Comment by ChetanSharma-msft** [comment]
Hello @haacked - Hope you are doing well!!
Please confirm whether your issue has resolved or still looking for any help?
