### ISSUE TITLE
Unable to Post Github API's in Incoming Webhook

### ISSUE THREAD

**Issue by muhammad-shameem** [OfficeDev/Microsoft-Teams-Samples#431]
We have configured an Incoming Webhook in github repo , Application-Type = Json, Enabled SSL , Everything seems fine to me , only issue is github API's are not working . When i try to post github api's it give me "Bad payload received by generic incoming webhook." error. But when i try to post dummy "Hello World" using curl it's working. Please fix it.

**Comment by ChetanSharma-msft** [comment]
Hello @muhammad-shameem - Thanks for sharing your feedback.
Can you please share the repro steps and the sample link that you have tried ?

**Comment by Meghana-MSFT** [comment]
Can you please share the repro steps and the sample link that you have tried?

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you have any questions. Thank you.
