### ISSUE TITLE
In-Meeting Task Modules pop up appears in dark as blank (desktop client)

### ISSUE THREAD

**Issue by pjpraveenjayakumar** [OfficeDev/Microsoft-Teams-Samples#438]
we have implemented the teams tab task module from the below sample reference and same task module has been added as side panel in meeting, and in meeting Task module appears in dark as blank (below snap) and it only happens in desktop client and with web client it's working fine. (This is adoptive card-based task module).
reference 1: https://github.com/nanddeepn/code-samples/tree/master/MSTeams/task-modules-tab/YouTubePlayer_AdaptiveCards
reference 2: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meeting-recruitment-app/nodejs
**web client works fine:**
![image](https://user-images.githubusercontent.com/109327327/185064887-a75dcff2-1c9a-4bd7-82c3-99ae46c2095b.png)

**desktop client:**
![image](https://user-images.githubusercontent.com/109327327/185064206-630bb1ce-83a5-4e53-94b6-44308e80d989.png)

**Comment by sayali-MSFT** [comment]
@pjpraveenjayakumar - We are looking into this we will get back to you soon. thanks!

**Comment by sayali-MSFT** [comment]
@pjpraveenjayakumar -We already raised Bug for the issue and concerned team is looking into it. We will inform you once we get any update.

**Comment by pjpraveenjayakumar** [comment]
@sayali-MSFT thanks for the update.

**Comment by sayali-MSFT** [comment]
@pjpraveenjayakumar -We are checking the status of the fix release with the engineering team. We will let you know once we have any updates on it. 
Thanks!!

**Comment by sayali-MSFT** [comment]
@pjpraveenjayakumar - Issue is resolved.
 Microsoft Teams Version 1.6.00.9979 (64-bit).
Could you please check it once and confirm the same.

**Comment by ChetanSharma-msft** [comment]
Hello @pjpraveenjayakumar - We are closing this issue for now, please feel free to reopen it, if required.
