### ISSUE TITLE
How to get audio record in meetingSidePanel?

### ISSUE THREAD

**Issue by r0y6a3n0** [OfficeDev/Microsoft-Teams-Samples#442]
I'm trying to get audio record in meeting side panel, however i failed. Does anyone has related experience？
I used this sample code: [hello-world-in-meeting](https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/hello-world-in-meeting)
then I changed the app manifest's to :
"context":[
        "channelTab",
        "privateChatTab",
        "meetingChatTab",
        "meetingDetailsTab",
        "meetingSidePanel",
        "meetingStage"
     ]
"devicePermissions": [
    "media",
],
also added the check the microphone permission code:
navigator.permissions.query({name:'microphone'}).then(function(result) {
      alert(result.state);
    });​

Both meetingSidePanel and meetingChatTab will show permission is granted.
Then i used [recorder.js ](https://github.com/mattdiamond/Recorderjs/tree/master/examples) to check audio is recorded or not.
It works in  meetingChatTab but can not get any audio file in meetingSidePanel. This confused me for a long time.

**Comment by Prasad-MSFT** [comment]
@r0y6a3n0 - Is there any console error you are getting?

**Comment by r0y6a3n0** [comment]
@Prasad-MSFT 
I don't get any console error. I just get DOMException: Permission denied in meetingChatTab(web version) but it works in channel tab. And in teams desktop app , I can get record permission in meetingChatTab. 
When this code below run in meetingChatTab, something went wrong but I didn't see any error.
The stream seems to be null. I am not sure. I saw the log doesn't show "Media stream created."

  function startUserMedia(stream) {
    var input = audio_context.createMediaStreamSource(stream);
    __log('Media stream created.');    
    recorder = new Recorder(input);
    __log('Recorder initialised.');
  }
    navigator.getUserMedia({audio: true}, startUserMedia, function(e) {
      __log('No live audio input: ' + e);
    });

**Comment by r0y6a3n0** [comment]
![B2128246-454D-4732-925C-97AAB37CD4D3](https://user-images.githubusercontent.com/6906747/186309207-439650b5-757c-475d-b17f-6d4f9eee5d38.jpeg)
I can’t get audio here. Same code in meeting side panel not work.

**Comment by Prasad-MSFT** [comment]
We are checking with engineering team if it supports in meeting side panel. We will inform you once we get any update. Thanks!

**Comment by Prasad-MSFT** [comment]
@r0y6a3n0 - There is no such update as of now. We will inform you once we get further info from engineering team. Thanks!

**Comment by r0y6a3n0** [comment]
@Prasad-MSFT I'm trying to get audio stream in the meeting and do speech recognition with my ASR model since I saw CART captions api is available. Is it supported to get the audio stream in meeting side panel? If not, I just give up this try.

**Comment by Prasad-MSFT** [comment]
@r0y6a3n0 - Device permissions in the meetings side panel are not supported yet in the General/Public ring.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
