### ISSUE TITLE
What is the api/function/process of opening a .docx file in Word app in Teams

### ISSUE THREAD

**Issue by qianwenyuan** [OfficeDev/Microsoft-Teams-Samples#459]
I am developing my Teams app, and I would like to know the api/function/process of how to open a .docx file in Word app in Teams, as I want to integrate it into my own functions. I analyzed network packages while I interacting with Teams in browsers, it seems like a process that i) POST a complicated http request, which includes file info, ii) Receive a HTML file as the response, iii) Use the HTML file to show the content of my file. I don't know if I am right, and would like to know more details. Thanks

**Comment by sayali-MSFT** [comment]
@qianwenyuan - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@qianwenyuan - Here is workaround for API use deeplink-
```
/// <summary>
        /// Link to open file in teams.
        /// </summary>
        public const string OpenFileInTeamsURL = "https://teams.microsoft.com/_#/{0}/viewer/teams/{1}";
```
Ref Doc-https://github.com/OfficeDev/microsoft-teams-apps-newemployeeonboarding/blob/main/Source/Microsoft.Teams.Apps.NewHireOnboarding/Constants/DeepLinkConstants.cs

We can use deep-link to open any file in Teams.

```
// If learning content url contains file extension opening the file in teams scope else redirecting to browser.
                card.Actions.Add(
                    new AdaptiveOpenUrlAction
                    {
                        Title = localizer.GetString("ViewLearningPlanButtonText"),
                        Url = string.IsNullOrEmpty(filExtension)
                    ? new Uri(learningPlan.Link?.Url)
                    : new Uri(string.Format(CultureInfo.InvariantCulture, DeepLinkConstants.OpenFileInTeamsURL, filExtension, actionDataUrl)),
                    });
            }
```

Ref Doc- https://github.com/OfficeDev/microsoft-teams-apps-newemployeeonboarding/blob/main/Source/Microsoft.Teams.Apps.NewHireOnboarding/Cards/LearningPlanCard.cs

`new Uri(string.Format(CultureInfo.InvariantCulture, DeepLinkConstants.OpenFileInTeamsURL, filExtension, actionDataUrl)),`

**Comment by sayali-MSFT** [comment]
@qianwenyuan -Did you get chance to check?

**Comment by ChetanSharma-msft** [comment]
@qianwenyuan - Please let us know if your issue has resolved or still need any guidance?

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
