### ISSUE TITLE
How to add Attendance bot App to Group chat programmatically?

### ISSUE THREAD

**Issue by ayon-maji** [OfficeDev/Microsoft-Teams-Samples#467]
I have tried with Microsoft Graph Explorer for checking is it working or not but It gives me response with Specific permission mismatch but I have given proper RSC Application permission to App manifest and published it my dev portal. Please guide.

**Comment by sayali-MSFT** [comment]
@ayon-maji - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@ayon-maji -To install the Microsoft Teams bot in a team or group chat, add the teams or groupchat scope to your bot.
here is sample for reference-
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/57.teams-conversation-bot

**Comment by sayali-MSFT** [comment]
@ayon-maji -Did you get chance to check?

**Comment by ayon-maji** [comment]
@sayali-MSFT Not yet. Will check it tonight.

**Comment by ayon-maji** [comment]
@sayali-MSFT I have checked it not working with MS Graph API. I have created the manifest for Teams Attendance BOT and published it in my dev Tenant and after that I have tried to add that app using MS Graph API explorer but failed. Here is my graph result screenshots.
![Screenshot (228)](https://user-images.githubusercontent.com/98821176/190712393-29f328f5-d054-4d06-81c1-7f82d4a1b4a7.png)

and this is my manifest-

{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
  "manifestVersion": "1.11",
  "version": "1.0.0",
  "id": "8d06f32f-0eac-4886-bb38-3998311ced93",
  "packageName": "com.microsoft.teams.meetingattendancereport",
  "developer": {
    "name": "Microsoft",
    "websiteUrl": "https://www.microsoft.com",
    "privacyUrl": "https://www.microsoft.com/privacy",
    "termsOfUseUrl": "https://www.microsoft.com/termsofuse"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Meeting Attendance Bot",
    "full": "Meeting Attendance Bot"
  },
  "description": {
    "short": "Bot sent meeting attendance report in chat.",
    "full": "This is a sample application which demonstrates how to get attendance reports using Graph API and send it in meeting chat."
  },
  "accentColor": "#235EA5",
  "bots": [
    {
      "botId": "c8fb9760-c7eb-4d46-b615-249326266e10",
      "scopes": [ "groupchat" ],
      "isNotificationOnly": true
    }
  ],
  "validDomains": [
    "*.ngrok.io",
    "https://1d85-103-135-228-14.ngrok.io"
  ],
  "permissions": [ "messageTeamMembers" ],
  "webApplicationInfo": {
    "id": "7e23a7cc-94e0-46cb-acaa-f8f8d4132e25",
    "resource": "https://RscPermission",
    "applicationPermissions": [
      "OnlineMeeting.ReadBasic.Chat"
    ]
  }
}

**Comment by sayali-MSFT** [comment]
@ayon-maji -Currently, this operation does not support installation of apps that require resource-specific consent permissions. For details, see [Known issues](https://learn.microsoft.com/en-us/graph/known-issues#Installation-of-apps-that-require-resource-specific-consent-permissions-is-not-supported).

Reference Document-https://learn.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-1.0&tabs=http

**Comment by ayon-maji** [comment]
@sayali-MSFT is there any solution to get meeting duration / attendees without OnlineMeetings.Read.All Application permission?

**Comment by sayali-MSFT** [comment]
@ayon-maji -Without permission it is not possible to get meeting duration/attendees.
Here is one sample to get the meeting event like meeting start date time,duration, but you need to add the following permission in manifest json.
  "applicationPermissions": [
      "OnlineMeeting.ReadBasic.Chat"
    ]
    
   Reference sample- https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-events/csharp/MeetingEvents/AppPackage

**Comment by ayon-maji** [comment]
@sayali-MSFT I already have tried with that sample but this operation does not support installation of apps that require resource-specific consent permissions

**Comment by sayali-MSFT** [comment]
@ayon-maji -Currently, Without permission it is not possible to get meeting duration/attendees.

Could you please help by suggesting this feature on - [Microsoft Teams · Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by ayon-maji** [comment]
@sayali-MSFT ok

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
