### ISSUE TITLE
Unable to render a Dynamics 365 account record in a Teams Stage view

### ISSUE THREAD

**Issue by Maheshyu1710** [OfficeDev/Microsoft-Teams-Samples#472]
I am trying to render a stage view with the url that redirects to a Dynamics 365 account record, currently when I follow the Microsoft Documentation and pass the Dynamics 365 encoded URL of an account entity, I see a pop with message - {Teams app name} is unable to show this view
Contact your IT admin if the problem persists.
I have added the domain "*.dynamics.com" in the valid domain section in the app manifest too.

My objective is to render a Dynamics 365 url using a Teams Stage view

![image](https://user-images.githubusercontent.com/46625719/191024902-54037f67-c81c-4ef4-b189-efe57666be03.png)
App name - Peppermint Connect new local

**Comment by Meghana-MSFT** [comment]
This question is tracked on https://techcommunity.microsoft.com/t5/teams-developer/microsoft-teams-stage-view-fails-to-load-dynamics-365/m-p/3604341#M6251. We are closing this issue here.
