### ISSUE TITLE
Receiving meeting start/end events without RSC

### ISSUE THREAD

**Issue by khatada** [OfficeDev/Microsoft-Teams-Samples#491]
I am developing a Teams app and bot for meeting. My teams bot needs to receive meeting start and end events for some functionalities.

According to my research, in order for the bot to receive meeting start and end events, the bot requires OnlineMeeting.ReadBasic.Chat which needs chat scope RSC. 
However, the chat scope RSC is in developer preview and my company will not allow me to use it.
https://www.microsoft.com/ja-jp/microsoft-365/roadmap?filters=&searchterms=85551

Is there any way to get events about meeting starts and ends without developer preview feature?

**Comment by Meghana-MSFT** [comment]
we are looking on the possibility of this issue. we will get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @khatada - Sorry for delay in response.
We are checking internally with engineering team and get back to you once get any confirmation.

**Comment by khatada** [comment]
@Meghana-MSFT 

The RSC for chat scope is currently developer preview state, so I would like to receive the start/end event of the meeting without specifying the RSC in the manifest.

Once the chat scope RSC is changed to GA, we can use RSC. Therefore, I would like to know when it will be GA.

**Comment by Meghana-MSFT** [comment]
@khatada - If requirement is using the chat scope RSC permission in the manifest to receive the meeting start/end event, then yes, the feature itself is already GAed. You can use it without need to switch to developers preview.

**Comment by khatada** [comment]
@Madhuri-MSFT Thank you for response.

> the feature itself is already GAed. 

But the below document says that chat scope RSC is only available in public developer preview not GAed

https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/test-resource-specific-consent
> Resource-specific consent for chat scope is available in [public developer preview](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro) only.

**Comment by Meghana-MSFT** [comment]
If the requirement is only to get Meeting start/end events with chat scope RSC permission in the manifest, you can start using it. Engineering team is working to update docs related to meeting start/end events accordingly.

**Comment by khatada** [comment]
My requirement is to only receive meeting start/end events with  chat scope RSC permission in the manifest.
I'm happy with your answer because I now know that I can start using it because it's GA.

I am waiting for the documentation to be updated as I would like to know clearly what the GA is about.

**Comment by khatada** [comment]
@Meghana-MSFT 

When will the documentation update be completed for the GA of the RSC for the meeting start/end events?
I need to explain the GA of the RSC by the "official" teams sdk documents to my company.

**Comment by Meghana-MSFT** [comment]
@khatada - We will let you know once the doc is updated.

**Comment by khatada** [comment]
@Meghana-MSFT Any update?

**Comment by Meghana-MSFT** [comment]
@khatada - Apologies for the delay in response. Engineering team has shared the below response -

"The feature" is not RSC. The "feature" is meeting start/end event and this is the feature that is GAed. RSC support in the chat scope is going to be GAed in Jan. 

As a consumer of Meeting start/end event, they do not need to worry about the GA status of the RSC feature. As long as Meeting start/ende vent is GAed. From the customer perspective, they do not need to worry about issues related to dependencies that this feature has.
"you can still use Meeting Start/End event without switching into dev preview". 
 
One question I have is -
Could you help me to understand why it is not enough for the customer to let their company know that the meeting start/end event is GAed? Can you please let us know any concerns?

**Comment by Meghana-MSFT** [comment]
Did you get a chance to look at above comment. Please do share if any concerns.

**Comment by ChetanSharma-msft** [comment]
Hello @khatada - Could you please confirm whether your issue has resolved or need any help here?

**Comment by khatada** [comment]
@Meghana-MSFT 

Thanks for your answer.

My understanding is that the RSC of chat scope is required to receive meeting start/end events. So I was waiting for the RSC to become GA.
My customer will not agree to use the feature unless not only that is GA, but also another feature it depends on is GA as well.

Now that I know from your response that the RSC for the chat scope will be GA in January, I can use this feature.


No additional help is needed at this time. Thank you very much.

**Comment by Meghana-MSFT** [comment]
Thank you confirming back, we are closing this issue. Please feel free to reach out to us if you have any questions. thanks.

**Comment by Meghana-MSFT** [comment]
Thank you confirming back, we are closing this issue. Please feel free to reach out to us if you have any questions. thanks.
