### ISSUE TITLE
tab sso scope

### ISSUE THREAD

**Issue by itacirgabral** [OfficeDev/Microsoft-Teams-Samples#492]
- https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-sso/nodejs/src/server/tabs.js#L54
- https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_node.html#clientcredentialrequest

using the scope equals to `https://graph.microsoft.com/User.Read` the request returns:
```json
{
    "errorCode": "invalid_grant",
    "errorMessage": "AADSTS65001: The user or administrator has not consented to use the application with ID '2ea8224c-7b07-42a5-847b-742425be8b30' named 'FLASHPAY'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 44b6c146-5e0b-4567-98b1-c990fea63400\r\nCorrelation ID: b5e488b9-78c0-4efa-a801-82658b42a2cd\r\nTimestamp: 2022-10-08 21:09:45Z",
    "subError": "consent_required",
    "name": "InteractionRequiredAuthError"
}
```
but using https://portal.azure.com/ > Azure Active Directory > App registrations > your app > Expose an API > Scopes
![Screenshot from 2022-10-08 17-17-13](https://user-images.githubusercontent.com/6052177/194728152-a449a58e-0e31-4cf3-9479-ba373e2d2b53.png)
you get the tokens.

can anyone confirm the procedure?

**Comment by Meghana-MSFT** [comment]
@itacirgabral - Steps mentioned here at https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/nodejs#step-1-register-an-azure-ad-application is the correct procedure to setup the sample.

**Comment by ChetanSharma-msft** [comment]
@itacirgabral - Hope you are doing well!!
Could you confirm whether your issues have resolved?

If yes, can we close this issue?
