### ISSUE TITLE
Suggested Actions for non text activities

### ISSUE THREAD

**Issue by 01** [OfficeDev/Microsoft-Teams-Samples#493]
Is suggested actions for Bots on MS teams only enabled for text message activities? I am trying to include suggested actions on activities such as adaptive cards but does not seem to work.

**Comment by Nivedipa-MSFT** [comment]
@01 - In the document its already mentioned that **"SuggestedActions are only supported for one-on-one chat bots and text based messages and not for Adaptive Cards or attachments"**.

![image](https://user-images.githubusercontent.com/92150070/194804310-faffba4e-8cba-47e4-88ee-f45c36c224fa.png)

Ref Doc: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet#send-suggested-actions

Please let us know if you have any further query.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
