### ISSUE TITLE
docs.microsoft.com links in readme.md need to be updated to learn.microsoft.com

### ISSUE THREAD

**Issue by TheBluLion** [OfficeDev/Microsoft-Teams-Samples#502]
Links to microsoft learn more documentation in readme.mds need to be updated to learn.microsoft.com anywhere where docs.microsoft.com is reference.

**Comment by TheBluLion** [comment]
Microsoft-Teams-Samples/samples/app-sso/nodejs at main * OfficeDev/Microsoft-Teams-Samples (github.com)<https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso/nodejs>

There are multiple links within the doc but should be findable using find on page

**Comment by Nivedipa-MSFT** [comment]
@TheBluLion - We have check the links in readme files and those are redirecting to the learn.microsoft.com
Could you please confirm which links need to be updated here?

**Comment by TheBluLion** [comment]
I think your peer reached out yesterday and updated the links already- thanks for checking in.

**Comment by Nivedipa-MSFT** [comment]
@TheBluLion - We are closing this issue for now. Please feel free to reopen if required.
