### ISSUE TITLE
Links in https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso/nodejs/client/readme.md need to be updated

### ISSUE THREAD

**Issue by TheBluLion** [OfficeDev/Microsoft-Teams-Samples#503]
all links referencing facebook.github.io needs to be updated to correct location at https://create-react-app.dev/docs/code-splitting/

**Comment by Meghana-MSFT** [comment]
@TheBluLion - The links have been updated. Thank you. We are closing this issue, please feel free to reach out to us if you face any issue.

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you have any questions. Thank you.
