### ISSUE TITLE
Bug: Sample app-sso crash down

### ISSUE THREAD

**Issue by wenytang-ms** [OfficeDev/Microsoft-Teams-Samples#513]
In sample [app-sso](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso/nodejs), using node 16, once open Message extension first, the server will crash as following
Anyway, it works with node 14.
![image](https://user-images.githubusercontent.com/75360946/198882555-63d76db9-dd48-42ac-9717-4136fc9b32b3.png)

**Comment by sayali-MSFT** [comment]
@wenytang-ms - Thanks for reporting your issue.
We will try with node 16 from our end and let you know the update.

**Comment by wenytang-ms** [comment]
Tried it again and it worked, sorry for that.

**Comment by sayali-MSFT** [comment]
@wenytang-ms -Glad to hear you that your issue is resolved.

**Comment by wenytang-ms** [comment]
Sorry for reopen this issue. 
I found another error with node 16, npm 8 with following crash down picture once there going to send 412 response in the `onInvokeActivity` in the `server/bots/botActivityHandler.js`
![image](https://user-images.githubusercontent.com/75360946/198953365-2717f4c1-b6ef-48d0-a303-3faec30373a3.png)

**Comment by sayali-MSFT** [comment]
@wenytang-ms -We will try it from our end and let you know the update.

**Comment by ChetanSharma-msft** [comment]
Hello @wenytang-ms - We have tried this sample with below versions but it's working for us.
npm => 8.19.2
node => v16.18.0

We get 412 user consent error in this sample if the token is NOT exchangeable.
Please make sure that you have added all the required permissions and your configuration is correct.

Also, please check if you have grant admin consent for your graph API's:
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso/nodejs

**Comment by wenytang-ms** [comment]
All right.
I mean that once the botAdapitivity return 412 responses, but bot-builder never catch and process this exception. 
This exception should be caught in server or anywhere. If not, in node 16 may crash down the app.
I also submit an issue to botbuilder-js, and they add this problem to their backlog.
Thanks

**Comment by wenytang-ms** [comment]
@sayali-MSFT  Feel free to close the ticket.

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required.
