### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mbrecken76** [OfficeDev/Microsoft-Teams-Samples#53]
- Issue Type: `Performance`
- Extension Name: `ms-teams-vscode-extension`
- Extension Version: `1.2.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\MBRECK~1\AppData\Local\Temp\TeamsDevApp.ms-teams-vscode-extension-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Wajeed-msft** [comment]
@asnow003 - could you please help with this?

**Comment by ChetanSharma-msft** [comment]
Hello @mbrecken76 - Please confirm whether your issue has resolved or still looking for any help ?

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
