### ISSUE TITLE
 SSO Tab app cannot be created if domain name is more than 30 characters

### ISSUE THREAD

**Issue by osamum** [OfficeDev/Microsoft-Teams-Samples#55]
I want to make SSO Tab apps with Microsoft Teams Toolkit.
My domain fully qualified name's length is 31 characters.
However, Microsoft Teams toolkit's UI only allows for 30 characters.
What should I do?

**Comment by Wajeed-msft** [comment]
@asnow003 - do you have any suggestion on this?

**Comment by Wajeed-msft** [comment]
@osamum - did you try setting the domain name manfully in Azure portal directly?

**Comment by osamum** [comment]
Where do I enter the Azure portal?
I don't think there is a box to enter the domain name in the AAD screen of the Azure portal .
Did you mean [Redirect URL] in AAD's [App registrations] menu?

**Comment by osamum** [comment]
In fact, I can develop SSO Teams tab apps without Microsoft Teams Toolkit.
However, I would recommend the Microsoft Teams Toolkit to others.
They use Office Developer accounts, and their domain names tend to be long because *.onmicrosoft.com is appended to their domain names.
So it would be great if you could lengthen the character limit for the domain name in the UI when creating an SSO Tab  in Microsoft Teams Toolkit.

**Comment by Wajeed-msft** [comment]
@asnow003 - could you please confirm if length can be increased?

**Comment by ChetanSharma-msft** [comment]
Hello @osamum - Could you please confirm whether your issue has resolved or still looking for any help?

**Comment by osamum** [comment]
Has the code been corrected in response to my problem report?

**Comment by ChetanSharma-msft** [comment]
Hello @osamum - Sorry for delay in response.
We will check it on and let you know the updates.

**Comment by Wajeed-msft** [comment]
@osamum - Teams Toolkit has undergone multiple updates since this issue was opened. I no longer see option to add Valid domain while creating a new App instead it picks up automatically either from local (ngrok) or from deployed instance. 

![image](https://user-images.githubusercontent.com/31851992/209805682-c8ad5749-6656-49c5-ae9c-e12ab2e8f091.png)

Please give it a try and let me know if you are still facing the issue.

**Comment by ChetanSharma-msft** [comment]
Hello @osamum - Hope your issue has resolved.
We are closing this issue for now, please feel free to reopen it, if required.
