### ISSUE TITLE
Duplicate file error in sample ingestion 

### ISSUE THREAD

**Issue by mtrilbybassett** [OfficeDev/Microsoft-Teams-Samples#568]
There are 2 readme.md files under these "parent" sample paths. I would recommend reviewing files and determine if they are needed. If not, they should be deleted. 

**samples/bot-suggested-actions/nodejs/Images/Readme.md** versus the readme.md at samples/bot-suggested-actions/nodejs/Readme.md

**samples/outgoing-webhook/nodejs/Images/README.md** versus the readme.md at samples/outgoing-webhook/nodejs/README.md

**samples/tab-personal-sso-quickstart/csharp_dotnetcore/Images/README.md** versus the readme.md at samples/tab-personal-sso-quickstart/csharp_dotnetcore/README.md

**samples/meetings-attendance-report/csharp/MeetingAttendance/Images/README.md** versus the readme.md at samples/meetings-attendance-report/csharp/README.md

**Comment by Nivedipa-MSFT** [comment]
@mtrilbybassett - We will delete the second readme file which is reside in /Images/ path and will raise a PR.

**Comment by ChetanSharma-msft** [comment]
Hello @mtrilbybassett - I have raised a PR for it: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/570

**Comment by ChetanSharma-msft** [comment]
Hello @mtrilbybassett - Removed duplicate files and pushed the changes in main branch.
Please check and confirm once.

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you have any questions. Thank you.
