### ISSUE TITLE
desktop teams tab sso authentication

### ISSUE THREAD

**Issue by goutham54** [OfficeDev/Microsoft-Teams-Samples#572]
Iam Unable to do teamstab sso authentication in Teams desktop app
when Iam using teams app in Browser then it is working without asking singIn the powerBi report is rendering properly 
<img width="959" alt="Capture3" src="https://user-images.githubusercontent.com/95201692/202420231-cd3b3877-f091-40e1-beba-62a0dc5d18c0.PNG">

but  when I'm trying in desktop not working properly
Im using below code for after getting token from tabsso then with this token Im  rendering powerBi report in my custom page through Azure ad Login.
<img width="875" alt="azureAdlogin" src="https://user-images.githubusercontent.com/95201692/202418591-ea39cdd3-8e23-4ff1-8551-70d2cdaf41ad.PNG">

Im getting out put in  teams desktop . after clicking singIn also the report is not rendering.
<img width="910" alt="teamsadlogin" src="https://user-images.githubusercontent.com/95201692/202418939-15f043e5-21c5-4a2f-96fb-e38b8b317391.PNG">

is there any limitations for teams tab sso authentication in Teams Desktop app

pls provide relevant information for that .
Thank you .

**Comment by sayali-MSFT** [comment]
@goutham54 -Thanks for reporting your issue.
We are trying this scenario from our end and get back to you.

**Comment by sayali-MSFT** [comment]
@goutham54 -Currently, OAuth flow using 3rd party IDP provider is implemented. It is prompting for password in Desktop teams. But in web teams, don't see password prompt.

In Web Teams Client, the password prompt is not showing because there is an Active AAD session in the browser which is used for auth and acquire token.

In Desktop Client, password prompt is showing because Desktop doesn't have any AAD session to be shared and is asked to login.

**Comment by goutham54** [comment]
thank you for sharing information, could you provide any links for achieve AAD login in teams ssotab  in desktop app

**Comment by sayali-MSFT** [comment]
Please have look into this sample-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/csharp

**Comment by goutham54** [comment]
Thank you very much for sharing the information

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
