### ISSUE TITLE
Teams Bot SSO not working.

### ISSUE THREAD

**Issue by mandadimuralidharreddy** [OfficeDev/Microsoft-Teams-Samples#580]
Bot SSO not working for https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/js
But it working for this example https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-auth/nodejs

**Comment by Meghana-MSFT** [comment]
We will setup the above 2 samples and check from our end. Can you please share some more information regarding the issue that you, see?

**Comment by mandadimuralidharreddy** [comment]
its working now. but SSO randomly stops working.

**Comment by ChetanSharma-msft** [comment]
Thank you for confirming that it's working now. We are closing this issue for now, please feel free to re-open if you have any further questions.

**Comment by Meghana-MSFT** [comment]
Please do share bot logs or bot id in case if you face the same issue again.
