### ISSUE TITLE
Automatic Installation of bot is not working while invoking from message extension

### ISSUE THREAD

**Issue by arunagga** [OfficeDev/Microsoft-Teams-Samples#581]

**Comment by Meghana-MSFT** [comment]
Can you please share more details/steps on your issue?

**Comment by Meghana-MSFT** [comment]
@arunagga - Can you please share more details on your issue?

**Comment by arunagga** [comment]
> @arunagga - Can you please share more details on your issue?

I guess this is the orignal link https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/582

**Comment by Meghana-MSFT** [comment]
@arunagga - We are closing this issue as the same question is being tracked at https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/582
