### ISSUE TITLE
Automatic Installation of bot is not working while invoking from message extension

### ISSUE THREAD

**Issue by arunagga** [OfficeDev/Microsoft-Teams-Samples#582]
As per docs if we check the flow and show the adaptive card to add the bot in the corresponding context then it will automatically install the bot for us.
Reference: https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/create-task-module?tabs=javascript#request-to-install-your-conversational-bot

**Steps to Reproduce**

1. Clone https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-type-ahead-search-adaptive-cards/nodejs.
2. Add messaging extension in manifest.json
```json
"composeExtensions": [
    {
        "botId": "{{Microsoft-App-Id}}",
        "commands": [
        {
          "id": "requestFeedback",
          "type": "action",
          "title": "Request feedback",
          "description": "Request feedback",
          "initialRun": false,
          "fetchTask": true,
          "context": [
            "compose",
            "message"
          ]
        },
        ]
    }
  ],
```
3. Add the following messaging extension invoke handler in TeamsBot
```javascript
 handleTeamsMessagingExtensionFetchTask(
  context: TurnContext,
  action: MessagingExtensionAction
): Promise<MessagingExtensionActionResponse> {
  try {
    await TeamsInfo.getPagedMembers(context);
  } 
  catch (e) {
    return {
      task: {
        type: "continue",
        value: {
          card: CardFactory.adaptiveCard(
            AdaptiveCards.declare(cardWithInstallButton).render()
          ),
          
        },
      },
    };
  }
}
```
For me this adaptive card look like
```json
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "text": "Add the bot",
          "wrap": true,
          "spacing": "Small",
          "horizontalAlignment": "Center",
          "size": "Large"
        }
      ]
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "ActionSet",
          "actions": [
            {
              "type": "Action.Submit",
              "title": "Add the bot",
              "data": {
                "msteams": {
                  "justInTimeInstall": true
                }
              }
            }
          ],
          "spacing": "Large"
        }
      ],
      "separator": true,
      "spacing": "Large"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3"
}

```
4.After this invoke command from message extension this will going to return the adaptive card with install button present in the same.
5. After Clicking on the same the bot should get install automatically and we receive the invoke action here in handler.
```javascript
 public async handleTeamsMessagingExtensionSubmitAction(
    context: TurnContext,
    action: MessagingExtensionAction
  ): Promise<MessagingExtensionActionResponse> {
return {
      task: {
        type: "continue",
        value: {
          card: CardFactory.adaptiveCard(
            AdaptiveCards.declare(successCard).render()
          ),
          
        },
      },
    };
}
```
6.Issue is it come here but bot won't get installed

**Expected Behaviour**
Before invoke message with `name = composeExtension/submitAction` and `value.data.msteams.justInTimeInstall = true`.
Bot should be get installed in the context.
ie. Prior coming to this handler `handleTeamsMessagingExtensionSubmitAction`

**Actual Behaviour**
We are getting invoke message in the handler `handleTeamsMessagingExtensionSubmitAction` but bot is not getting installed in the same.

**Comment by Nivedipa-MSFT** [comment]
@arunagga - Could you please share how you are uploading the app via app catalogue or sideloading the app?

**Comment by arunagga** [comment]
Sideloading

**Comment by Nivedipa-MSFT** [comment]
@arunagga - Could you please upload the app via Teams admin center and check again? Meanwhile we are also testing this with sideloading.

**Comment by arunagga** [comment]
> @arunagga - Could you please upload the app via Teams admin center and check again? Meanwhile we are also testing this with sideloading.

Sure i will try to check this by uploading app from admin centre in the meanwhile do let me your result for the testing.

**Comment by Nivedipa-MSFT** [comment]
@arunagga - We have tested this via sideloading app and its working fine at our end.
At the first time we are getting card to add bot into scope. After adding bot for second time we are not getting justInTimeInstall card. 

We have added the code like below:
```
async handleTeamsMessagingExtensionFetchTask(context, action) {
        try {
                const member = await this.getSingleMember(context);
                return {
                    task: {
                        type: 'continue',
                        value: {
                            card: GetAdaptiveCardAttachment(),
                            height: 400,
                            title: `Hello ${ member }`,
                            width: 300
                        }
                    }
                };
            } catch (e) {
                if (e.code === 'BotNotInConversationRoster') {
                    return {
                        task: {
                            type: 'continue',
                            value: {
                                card: GetJustInTimeCardAttachment(),
                                height: 400,
                                title: 'Adaptive Card - App Installation',
                                width: 300
                            }
                        }
                    };
                }
                throw e;
            }
        }

```
Please refer below video for your reference:
[recording-2022-11-21-14-22-49.webm](https://user-images.githubusercontent.com/92150070/203008507-c4cfb34e-5fce-43cc-8a0b-48439f209592.webm)

Please let us know if you have any further query.

**Comment by arunagga** [comment]
I am still facing the same issue, i have attached one video for the same.
link: https://www.loom.com/share/1428712dc22c43e7b3f6597b9fe25858

**Comment by Nivedipa-MSFT** [comment]
@arunagga - Are you facing same issue for all other users also? Or only specific to Graddy?

**Comment by arunagga** [comment]
For all of them

**Comment by Nivedipa-MSFT** [comment]
@arunagga - We have tested this again, but it was working fine at our end. Could you please share your code zip file to check at our end?
Meanwhile could you please try to setup below sample and check whether its working for you? In below sample the justInTimeInstall card has used. We have tested this with below sample also and it's working correctly.
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/51.teams-messaging-extensions-action

**Comment by Nivedipa-MSFT** [comment]
@arunagga - Could you please confirm that is your issue resolved or are you still facing this issue?

**Comment by arunagga** [comment]
Yes, I am still facing this issue, give me sometime i will get back to you shortly

**Comment by Nivedipa-MSFT** [comment]
@arunagga - Did you checked this?

**Comment by Nivedipa-MSFT** [comment]
@arunagga - Did you get a chance to check this?

**Comment by arunagga** [comment]
Thanks @Nivedipa-MSFT , it worked for me now

**Comment by Nivedipa-MSFT** [comment]
@arunagga - Glad to hear that your issue is resolved. Could you please share your valuable feedback here [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u).

**Comment by maxime-wegrow** [comment]
do this behavior has change with the new Teams version ?

with the last version of teams available on Windows 11 when the user click on the Install button handleTeamsMessagingExtensionSubmitAction  is not called
