### ISSUE TITLE
delegated permission not working

### ISSUE THREAD

**Issue by xerosanyam** [OfficeDev/Microsoft-Teams-Samples#586]
not getting `onTeamsMeetingEndEvent` when I use
```
"authorization": {
    "permissions": {
      "resourceSpecific": [
        {
          "type": "Delegated",
          "name": "OnlineMeeting.ReadBasic.Chat"
        }
```

getting ` Bot not allowed to get meeting details`

**Comment by Meghana-MSFT** [comment]
As mentioned in document, can you please use application permissions and let us know if that helps.

**Comment by xerosanyam** [comment]
But my question is around `delegated` permission. I do not want to use `application` permission. Our customers are not allowing `application` level permission

**Comment by Meghana-MSFT** [comment]
It is currently available only with application permission not with delegated permissions.

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you have any questions. Thank you.
