### ISSUE TITLE
Request.prototype.closed = function closed() Error

### ISSUE THREAD

**Issue by yd081581** [OfficeDev/Microsoft-Teams-Samples#587]
Hi ,
First time try and getting the blw error: 

Request.prototype.closed = function closed() {
                             ^
TypeError: Cannot set property closed of #<Readable> which has only a getter
    at patch (C:\Users\xxxxx\Microsoft-Teams-Samples\samples\app-hello-world\nodejs\node_modules\restify\lib\request.js:848:30)

**Comment by Meghana-MSFT** [comment]
We are setting up the above sample at our end, we will get back to you. Which node version are you using currently? Can you please check if this is a related issue - https://github.com/restify/node-restify/issues/1925?

**Comment by yd081581** [comment]
> 

$ node -v
v18.12.1

**Comment by Meghana-MSFT** [comment]
Can you please try downgrading your version once and see if it runs successfully. Since the PR is still in open state - https://github.com/restify/node-restify/pull/1929

**Comment by yd081581** [comment]
> Can you please try downgrading your version once and see if it runs successfully. Since the PR is still in open state - [restify/node-restify#1929](https://github.com/restify/node-restify/pull/1929)

thanks...working after downgrade.

**Comment by ffchristian** [comment]
can we rather fix this? I think it would be better to support new versions of node as node goes on otherwise we would need to migrate to another framework I open this issue which was closed but not tackle
https://github.com/restify/node-restify/issues/1925

**Comment by Meghana-MSFT** [comment]
Changes are done for restify for the above mentioned app-hello-world nodejs sample.
