### ISSUE TITLE
Add element to an existing Teams App

### ISSUE THREAD

**Issue by arambazamba** [OfficeDev/Microsoft-Teams-Samples#59]
I have a very simple question that I cannot find an answer to ... Lets say I have an existing Teams App and I want to add another element (Tab, Bot, ...) to it using the VS Code Teams Toolkit ... I know I can add the metadata, but I don't seem to find a way to get automatic scaffolding for the item I added. Is this possible?

**Comment by Wajeed-msft** [comment]
@asnow003 - could you please help here?

**Comment by ChetanSharma-msft** [comment]
Hello @arambazamba - Hope you are doing well!!
Could you please confirm whether your issue has resolved or still looking for any help?

**Comment by Wajeed-msft** [comment]
@arambazamba - automatic scaffolding is not possible when adding new capabilities. It is supported only while creating a new app.
