### ISSUE TITLE
access power Bi report in teams desktop through team tabsso authentication

### ISSUE THREAD

**Issue by goutham54** [OfficeDev/Microsoft-Teams-Samples#593]
Hi,
i want to access power Bi report in teams desktop app through teams tab sso authentication.  Im following the same concept from the github link :https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/csharp.
 Here  Im getting sso authentication token and passing that  token  to AAd login authentication and  redirect url is  the power bi report url 
Im following code like:
<img width="840" alt="AAdLogic" src="https://user-images.githubusercontent.com/95201692/203984067-aca6edb5-0aa4-4056-8833-36130ec4a6ae.PNG">
Im getting output in Teams Desktop app  ,   **powerBi Sign-In**  button as shown below screen shot , when Iam clicking the signIn button  its navigating the Browser but nothing happening in browser as well as Teams desktop app  so, Im not getting power Bi report  as I expecting. 
actually I  want to know How can we authenticate powerBi report from teams desktop app through AAd login using tabsso authentication token.
<img width="960" alt="AddloginOutput" src="https://user-images.githubusercontent.com/95201692/203984375-cb30671e-fa66-4482-b80a-dbba841fce4b.PNG">

Thank you 
Goutham Pamula

**Comment by Prasad-MSFT** [comment]
@goutham54 - Is there any console error you are getting? Could you please also verify if you have properly configured redirect URI for your app in Azure?

**Comment by ChetanSharma-msft** [comment]
Hello @goutham54 - Sorry for delay in response.
Please confirm whether your issue has resolved or need any further help?

Meanwhile, we will try it from our end and let you know the updates.

**Comment by goutham54** [comment]
not resolved , pls could you provide any information.

**Comment by ChetanSharma-msft** [comment]
Hello @goutham54 - Sorry for delay in response.
Could you please confirm whether you are facing this issue in Teams Desktop Client only or in Web client also?

If you are facing this issue in Web client as well, could you please check your console logs and share if any?

**Comment by goutham54** [comment]
teams web client it is working fine , Im facing the issue in teams  desktop

**Comment by ChetanSharma-msft** [comment]
Could you please share the code base, so that we can try to repro from our end?

**Comment by goutham54** [comment]
code sample: this code is working in teams web browser and it is not working in teams desktop app
`  
       let state = _CreateGUID;  
        localStorage.setItem("simple.state", state);
        localStorage.removeItem("simple.error");
        let queryParams = {
            client_id: _clientId,
            response_type: token,
             scope: `api://${_clientId}/access_as_user`,
             response_mode: "fragment",
            client_info: 1,
            resource: "https://graph.microsoft.com/User.Read openid",
            redirect_uri: "https://app.powerbi.com/reportEmbed?reportId={ReportId}&autoAuth=true&ctid={tenantId}",
            nonce: auth_Js.CreateUUID(),
            state: state,
            sso_reload: true,
            login_hint: "userEmail"
        };
        let authorizeEndpoint = "https://login.microsoftonline.com/common/oauth2/authorize?"
            + $.param(queryParams);;
         window.location.assign(authorizeEndpoint);
       
    
`

**Comment by Prasad-MSFT** [comment]
@goutham54 - We tried to repro the issue at our end, and we also faced same problem.  On clicking the Sign-in button its navigating to the browser but nothing happening in browser as well as Teams desktop app.
We have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. Thanks!

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
