### ISSUE TITLE
RSC permission in manifest not allowing to install app to team

### ISSUE THREAD

**Issue by murali-innerfit** [OfficeDev/Microsoft-Teams-Samples#594]
I am getting below error when I try to install custom app which uses RSC.
![image](https://user-images.githubusercontent.com/119105995/204082746-9421dc76-87bd-4fb8-8e3c-cbb8fa4852f6.png)
My sample manifest
`{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.12/MicrosoftTeams.schema.json",
    "version": "1.0.0",
    "manifestVersion": "1.12",
    "id": "7df0646c-d47a-4466-80bb-a07669f7e084",
    "packageName": "com.ms.app",
    "name": { "short": "RSC App", "full": "RSC App" },
    "developer": {
      "name": "Team Inc",
      "websiteUrl": "https://test.me/",
      "privacyUrl": "https://www.notion.so/401a23507de449e68655e990504dae6e",
      "termsOfUseUrl": "https://www.notion.so/942cd2a95d884206a368dc1d4b8a0446"
    },
    "description": {
      "short": "test",
      "full": "RSC"
    },
    "icons": { "outline": "outline.png", "color": "color.png" },
    "accentColor": "#004492",
    "bots": [
      {
        "botId": "8828a357-461f-4e75-7e00-f66271a7907c",
        "scopes": ["personal","team","groupchat"],
        "isNotificationOnly": false,
        "supportsCalling": false,
        "supportsVideo": false,
        "supportsFiles": false
      }
    ],
    "permissions": [
      "identity",
      "messageTeamMembers"
    ],
    "validDomains": [
      "*.ngrok.io",
      "token.botframework.com",
      "login.microsoftonline.com"
    ],
    "webApplicationInfo": {
      "id": "8828a357-461f-4e75-7e00-f66271a7907c",
      "resource": "https://botid-8828a357-461f-4e75-7e00-f66271a7907c"
    },
    "staticTabs": [
      { "entityId": "conversations", "scopes": ["personal"] },
      { "entityId": "about", "scopes": ["personal"] }
    ],
    "defaultGroupCapability": {
      "team": "bot",
      "groupchat": "bot",
      "meetings": "bot"
    },
    "authorization": {
      "permissions": {
        "resourceSpecific": [
          { "name": "Member.Read.Group", "type": "Application" },
          { "name": "TeamMember.Read.Group", "type": "Application" }
        ]
      }
    }
  }
  `

**Comment by Prasad-MSFT** [comment]
@murali-innerfit - According to the error message it seems like there is already an app installed which is using the same app id. Could you please verify that? Also is the same app getting uploaded without adding RSC permissions section in manifest?

**Comment by murali-innerfit** [comment]
I have uninstalled all apps in team but still getting same error.
When I remove RSC from manifest am not getting this error.

**Comment by Prasad-MSFT** [comment]
@murali-innerfit - We tried uploading the app to team using the manifest schema provided and got below error.
![image](https://user-images.githubusercontent.com/62237649/204450842-00297100-3559-4f07-8c4e-94bf3d701ae0.png)

However, on removing RSC from manifest it gets uploaded successfully.
We have raised a bug for this issue. We will inform you if there is any update from engineering team.

**Comment by Prasad-MSFT** [comment]
@murali-innerfit - Apologies. We are following up with engineering team about this issue. We will update this thread once we hear from them. Thanks!

**Comment by ChetanSharma-msft** [comment]
This is as per design  refer here for more: https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent

To install your app on which you've enabled RSC permission in a team, chat, or user, follow these steps:

Ensure that you've configured [consent settings](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/grant-resource-specific-consent#configure-consent-settings) for team, chat, or user.

[Upload your custom app in Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/grant-resource-specific-consent#upload-your-custom-app-in-teams).
