### ISSUE TITLE
The app configuration in App Studio does not exist

### ISSUE THREAD

**Issue by estruyf** [OfficeDev/Microsoft-Teams-Samples#60]
When reopening the project, the extension doesn't find the app anymore. Although the app is still available with the same ID in App Studio.

![Screenshot 2021-03-27 at 10 13 02](https://user-images.githubusercontent.com/2900833/112716187-22f3f380-8ee5-11eb-9187-8b91911c25c4.png)

**Comment by asnow003** [comment]
Just checking.  Are you logged in with the same user in Teams as you are in VS Code.
If so can you give me the steps of what sample you chose also so I can try to reproduce.

**Comment by estruyf** [comment]
Yes, logged in with the correct user. The app itself was created from the teams extension. Not related to a sample, but the VSCode extension points to this repository.

**Comment by asnow003** [comment]
Right I just tested by creating a personal app.  When I go to the welcome page and click on app studio and authenticate again with the same user I used to scaffold the app I see my configuration.

The only way you would see that error message in VS code is if you are not in the same tenant/organization in which you created the scaffold.  Can you verify the user you are logged in as in VS Code all match... or try again to be sure.

**Comment by estruyf** [comment]
Did that many times already. When I restart VSCode, open the app, navigate to configuration, it asks me to login. Specify my DEV tenant, and it shows that screen.

I can create a new one without an issue.

________________________________

**Comment by asnow003** [comment]
Let me give it a try with my dev tenant to be sure is not an issue there.

**Comment by estruyf** [comment]
Is the extension open source? Otherwise I could do a debug run.

**Comment by asnow003** [comment]
No not open source.  It would be an issue with authentication in VS Code itself because we just pass the token we get from VS Code to our service.  So it would either be something in VS Code or the service.

**Comment by asnow003** [comment]
if this is a dev tenant of yours that doesn't have confidential information on it... you could create me a basic user login so I could try also.  Please email me at allen.snow@microsoft.com with the login info

**Comment by estruyf** [comment]
@asnow003 I found the issue, seems my ID somehow changed on MS Teams. I checked the traffic with fiddler, and saw and saw the failing API calls. That is how I saw that my ID was different. Used the new ID and updated it in the `package.json` file,
