### ISSUE TITLE
 Tabs Azure AD Single Sign-On Sample: resourceDisabled

### ISSUE THREAD

**Issue by web265p3** [OfficeDev/Microsoft-Teams-Samples#61]
I am trying to run your sample: "Microsoft Teams - Tabs Azure AD Single Sign-On Sample"
Like [here ](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/nodejs)

Following the steps was not hard and everything worked until I launch my app. In this case I get an error message:

![image](https://user-images.githubusercontent.com/20642406/112801546-4fd51180-9071-11eb-92fa-6516a013563e.png)

Unfortunately I could not find anything with Google and because there is not a lot I could do wrong - the sample instructions are pretty clear - I think something else must be wrong.  
How can I start to investigate where the error is coming from? If I inspect the window of the app with DevTools I do not get more information actually... 

Just that:

main-f2e44df2875d9103.js:1 AuthenticationService: Authentication - {"context":"ShellService::requestMessage","subContext":"AuthElectron","message":"Received an error from IPC::{\"eventName\":\"aadGetToken\",\"error\":\"resourceDisabled\",\"correlationId\":\"8fbcbc8e-d9eb-43ef-b70f-dbcb3b12d37a\"}::isOnline-true","errorCode":"RemoteOperationFailed","correlationId":"8fbcbc8e-d9eb-43ef-b70f-dbcb3b12d37a"}

**Comment by Wajeed-msft** [comment]
@web265p3 - just to make sure all the configs are correct, could you please try [Teams Toolkit](https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/visual-studio-code-tab-sso)?

**Comment by Wajeed-msft** [comment]
Please re-open if you are still facing this issue.
