### ISSUE TITLE
Teams Bot Node.js - send a proactive message to a particular person that is not part of conversation but has app installed? 

### ISSUE THREAD

**Issue by sanasz91mdev** [OfficeDev/Microsoft-Teams-Samples#617]
Hello

how can i send a proactive message to a particular person that is not part of conversation but has app installed. all i have is that person's email address. can teams bot application send him/her a proactive message by just knowing email address?

**Comment by sayali-MSFT** [comment]
@sanasz91mdev -Sending a proactive message is different from sending a regular message. There's no active turnContext to use for a reply. You must create the conversation before sending the message. For example, a new one-to-one chat or a new conversation thread in a channel. You can't create a new group chat or a new channel in a team with proactive messaging.

Reference Document-https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet

**Comment by sanasz91mdev** [comment]
@sayali-MSFT alright, i have a case where i need to send a proactive notification to a team's member that a ticket is assigned to him/her. I might assign ticket in a conversation with bot , but the person to whome ticket is assigned should be notified

how may i achieve this? ... again, i just have email address of Team's member to whom i assigned ticket.

**Comment by sayali-MSFT** [comment]
@sanasz91mdev - Currently, Teams doesn't support sending proactive messages using email or User Principal Name (UPN).
Reference document- https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#send-the-message

Could you please help by suggesting this feature on - [Microsoft Teams · Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by sanasz91mdev** [comment]
> ht assign ticket in a conversation with bot , but the person to whome ticket is a



> @sanasz91mdev - Currently, Teams doesn't support sending proactive messages using email or User Principal Name (UPN).
> 
> Reference document- https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#send-the-message
> 
> Could you please help by suggesting this feature on - [Microsoft Teams · Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

So i cannot send proactive notification in my case? ... i can only send the notification IFF the person to whom i want to send proactive notification is part of conversation, right?

**Comment by sayali-MSFT** [comment]
@sanasz91mdev -Yes. Correct.
You can create a new conversation with a user or a conversation thread in a channel and you must have the correct ID.

**Comment by sayali-MSFT** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
