### ISSUE TITLE
Upload large file to user's OneDrive using bot

### ISSUE THREAD

**Issue by ferryjan** [OfficeDev/Microsoft-Teams-Samples#620]
Hi, 

I am using this project to upload file to user's OneDrive:
[https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-file-upload/csharp](url)

It is working good with small files. However, when I try to upload large files, everytime after 10 seconds, an error message show up. It is saying "Something went wrong, please try again."

![1](https://user-images.githubusercontent.com/38276075/206394275-2f6d621c-1468-4249-80f7-d26d655e175e.png)

Actually, there is nothing wrong. It just takes time to upload the file. After awhile, it is showing the file is uploaded.

![2](https://user-images.githubusercontent.com/38276075/206394831-4637efe5-a9df-4e11-82b9-cb0c69c1edb9.png)

This is not a good user experience, it will confuse user. How to prevent this message to show up? Thanks!

**Comment by Prasad-MSFT** [comment]
@ferryjan - We are also able to repro the issue. When large file is being uploaded, initially it throws error `Something went wrong. Please try again`, but later file is being uploaded successfully. 
![image](https://user-images.githubusercontent.com/62237649/206436694-e58f6a51-f267-4b79-b118-cd886b1564e5.png)
![image](https://user-images.githubusercontent.com/62237649/206436733-177ec9df-9558-4f66-af11-f4b4f82ac0d3.png)
We have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. Thanks!

The bot has 15 seconds to acknowledge the call with a status 200. If the bot doesn't respond within 15 seconds, an HTTP GatewayTimeout error (504) occurs.
Please refer below doc which explains how to handle long running operations.
https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0

**Comment by Prasad-MSFT** [comment]
@ferryjan - Apologies. We are following up with engineering team about this issue. Currently there is no ETA to share. We will update this thread once we hear from them. Thanks!

**Comment by Prasad-MSFT** [comment]
@ferryjan - According to [this](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#upload-bytes-to-the-upload-session) documentation,
where it refers to this doc [Upload bytes to the upload session](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#upload-bytes-to-the-upload-session) for large file uploading that must use multi-part uploading. Each chunk of a large file to upload can't be too large. The best practice is 5 - 10MB per chunk (<60MB per single upload request for a chunk). Never try to upload large file in a single chunk. Please refer to that doc for all detailed numbers for the best practice.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
