### ISSUE TITLE
get filter data from  power Bi report  using rest api's

### ISSUE THREAD

**Issue by goutham54** [OfficeDev/Microsoft-Teams-Samples#634]
Hi , I have public power Bi report Url . So now I need filtered data in report by passing parameter with the report url.

I have a report url and Im passing filter parameter below like . but this is not working as i expect.
<img width="921" alt="powerBireportUrl" src="https://user-images.githubusercontent.com/95201692/208114559-85665d66-0c29-41eb-89d3-b740384a55e8.PNG">

**I want to apply filters dynamically to that respective power bi report by using any rest api call.**
is there any rest api to get filter data from power bi report url .
pls provide relevant information. 

Thank you 
Goutham Pamula

**Comment by Meghana-MSFT** [comment]
@goutham54 - Can you please confirm if you are developing any Teams application or testing any of the Teams sample in this repo? Can you please share more details. Thanks.

**Comment by goutham54** [comment]
I'm using some javascript code for rendering powerBi report with filter which i applied. but  filter is not applying  to respective report .
![Screenshot (313)](https://user-images.githubusercontent.com/95201692/208416187-fafafb0c-ea40-44ec-ab4a-463b00eca4bd.png)
what i have done mistakes in above code. can you suggest information.

**Comment by Wajeed-msft** [comment]
@goutham54 - This seems like more of Power BI related query which [Microsoft Power BI Community](https://community.powerbi.com/t5/Developer/bd-p/Developer) can help to resolve much faster. Could you please help to raise it on [Microsoft Power BI Community](https://community.powerbi.com/t5/Developer/bd-p/Developer) forum? 
Please let me know if you have any concerns.

**Comment by ChetanSharma-msft** [comment]
Hello @goutham54 - Hope you are doing well!!
Please confirm if you are able to raise the issue in BI community, so that we can close this issue?

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
