### ISSUE TITLE
adaptive card form submit in Power virtual agent bot  new features

### ISSUE THREAD

**Issue by goutham54** [OfficeDev/Microsoft-Teams-Samples#639]
Hi,
actually  my requirement  is I'm   submit the form data through adaptive card in power virtual agent bot. So, previously it was done through composer topic and that topic called in pva conversation flow . But composer is removed in PVA new releases and Im able to render the adaptive card form through pva conversation flow which is added as new feature in pva . but when i do  form submit the card how can i get the data .
sample adaptive card which im using in pva canvas 
<img width="287" alt="adaptive" src="https://user-images.githubusercontent.com/95201692/208882416-414ab273-9f15-45d8-94f8-74b640980858.PNG">

thanks 
Goutham Pamula

**Comment by sayali-MSFT** [comment]
@goutham54 - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@goutham54 -We are trying the same with composer, but as you mention above PVA is remove the composer in latest release.
Could you please share the document link which you refer for this so that we can try it from our end?
https://learn.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example4

**Comment by goutham54** [comment]
yes, In old pva version we have option for composer. I'm sharing the screen shot below
<img width="733" alt="composerOption1" src="https://user-images.githubusercontent.com/95201692/210709705-5da7fcc8-20c4-4085-95d2-4a86a8240175.PNG">

but In new pva  releases I didn't find any option for open composer and also i didn't find any document about composer in new pva releases . is this removed in new pva releases if it is removed how can i do adaptive card form submit.
could pls share the information.

Thanks
Goutham Pamula

**Comment by sayali-MSFT** [comment]
@goutham54 - We are checking with the internal team and will get back to you once we get any update.

**Comment by sayali-MSFT** [comment]
@goutham54 - Bot Framework Composer integration is not available to users who only have the [Teams Power Virtual Agents license](https://learn.microsoft.com/en-us/power-virtual-agents/requirements-licensing-subscriptions). You must have a [trial](https://learn.microsoft.com/en-us/power-virtual-agents/sign-up-individual) or full Power Virtual Agents license.

Reference Document-https://learn.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example4
![pva](https://user-images.githubusercontent.com/93527375/213633507-1ade1441-da28-406a-a832-246310617401.png)

**Comment by ChetanSharma-msft** [comment]
Hello @goutham54 - Hope your query has resolved.
We are closing this issue for now, please feel free to reopen it, if required.
