### ISSUE TITLE
Cannot run handleTeamsTaskModuleFetch in bot-task-module

### ISSUE THREAD

**Issue by akshay-gadkari** [OfficeDev/Microsoft-Teams-Samples#656]
I am testing the node sample. The comment on line 24 of teamsTaskModuleBot.js says that "When any of the options are selected, `handleTeamsTaskModuleFetch` is called", but the function does not seem to run when I select any option. None of the console logs I've added within the function are displayed.

This was tested using the bot framework emulator V4. Let me know if any other information is needed.

**Comment by Nivedipa-MSFT** [comment]
@akshay-gadkari - Thanks for reporting your issue. We will test this and update you soon.

**Comment by akshay-gadkari** [comment]
When running in teams, I ran into a different issue. `this.onMessage` doesn't work, even though the bot runs and I can send messages to it in chat. It never gets to run `handleTeamsTaskModuleFetch`.

**Comment by Nivedipa-MSFT** [comment]
@akshay-gadkari - We are facing some issues while testing. We will update you soon.

**Comment by akshay-gadkari** [comment]
Yes, this is still a problem when I use the debugger to test in Teams client. As a workaround, I've created a separate function to listen for turnContext.activity and respond based on the values there.

Is there any specific code that causes `handleTeamsTaskModuleFetch` to run? If I can check that, it might make debugging easier for me.

**Comment by ChetanSharma-msft** [comment]
Hello @akshay-gadkari - These methods are specific to Teams client and can't be invoked/tested from bot emulator.
We will still check with engineering team and let you know the updates.

**Comment by akshay-gadkari** [comment]
I'm not currently testing with the bot framework emulator, but the VS Code debugger which opens Teams in a browser. If I test with the debugger, will I have the problem as using the emulator?

**Comment by Nivedipa-MSFT** [comment]
@akshay-gadkari - We have tested this with VS Code debugger in Teams web browser. You will not get the same problem as emulator when you will test this with VS Code debugger which opens Teams in browser.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
