### ISSUE TITLE
Encoutering "Error: Authorization has been denied for this request"

### ISSUE THREAD

**Issue by hungngocphat01** [OfficeDev/Microsoft-Teams-Samples#658]
Hi,

I'm new to MS Bot Framework, and I am encountering an issue. I have cloned this repository and ran the NodeJS `bot-conversation` sample, following the exact same steps as described in the README file:

- Set up an Azure Bot app with type **UserAssignedMSI** (creating a single-tenant or multi-tenant application is not possible in my organization). 
- `npm install` 
- Edit the `.env` file and fill out `MicrosoftAppType`, `MicrosoftAppId`, `MicrosoftAppTenantId` (I'm sure these fields were filled correctly).
- Setting up `ngrok`
- Packaging and sideloading manifest file to Teams
- Run the bot

However, when I try to send any message to the bot (either from Web Chat or Teams), I always get the following error: `Error: Authorization has been denied for this request`. It is caught in the `onTurnError` method in `index.js`. I'm running the exact same code as provided in the repository, without any modifications and it is still not working. What could be the possible solution to this problem?

Thank you.

**Comment by ChetanSharma-msft** [comment]
Hello @hungngocphat01 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Pawan-MSFT** [comment]
Hello @hungngocphat01 - Could you please follow below steps:

1) Create a new app registration in your Tenant with multi-tenant.
2) Add **"MultiTenant(default)"** value for MicrosoftAppType in your .env file. 

**Note:** No need to configure UserAssignedMSI in bot.


Please try it and let us know, if you still face any issue.

**Comment by Meghana-MSFT** [comment]
@hungngocphat01 - Can you please try above steps and let us know if that helped?

**Comment by hungngocphat01** [comment]
@Meghana-MSFT  @Pawan-MSFT - 
Hi, 
I'm sorry for the late reply. By default, I cannot access the Azure app registration section in my work Azure account.

I've tried with my personal account by creating a multi-tenant app registration in Azure, plus a new bot registration at dev.botframework.net. It finally worked without any issues so far. 

Just have one final question. Does _local_ bot hosting (for experimenting) with _ngrok_ require a _multi-tenant_ app registration? If so, please add a brief clarification to the framework docs to inform any future developers who could experience a similar problem, since not everyone is familiar with the Azure authentication policies.

Thank you very much for your support.

**Comment by Pawan-MSFT** [comment]
@hungngocphat01 It is not mandatory to use multi-tenant app, but if you are using single tenant then your app registration and your azure bot registration should be in same tenant. 
Please let us know if you have further questions.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
