### ISSUE TITLE
Tabs-SSO CSharp project authentication Issue

### ISSUE THREAD

**Issue by grumpykiwi** [OfficeDev/Microsoft-Teams-Samples#66]
I downloaded the Tabs SSO example for MVC and followed the instructions to get it running

For some reason, running the app straight out of Visual Studio via F5 does not even try to authenticate. After wrestling the dreaded return URL error and a 401 I have it running fine in Teams. On load it displays the user profile data ok.

My questions are:

When running as a standalone web app, should it try to authenticate? Is this expected?
If not expected, where should I start looking for an issue?
If expected, how I do change the app to authenticate by default?

I have a bunch of other functionality written inside a stand alone MVC app that makes extensive calls to Graph API to get presence info and user photo for an internal app. It would be nice to be able test and debug without having the overhead of reloading it in Teams every time.

I have defined all of the extra permissions needed in the manifest. Is there anything else I need to do? A code sample perhaps for requesting additional permissions using the token received via SSO.

Any help greatly appreciated.

Thanks

Mark

**Comment by Wajeed-msft** [comment]
> When running as a standalone web app, should it try to authenticate? Is this expected?

Currently this sample is designed to authenticate in Microsoft Teams only. It uses Teams SDK to perform SSO auth. You can add checks if it's running inside Microsoft Teams by adding query string parameter and perform auth outside of Teams context. 

> A code sample perhaps for requesting additional permissions using the token received via SSO.

Could you please help to raise a request here? https://github.com/OfficeDev/Microsoft-Teams-Samples/discussions/categories/new-sample-ideas

**Comment by Wajeed-msft** [comment]
@grumpykiwi - closing this for now, please re-open if you are still facing this issue.
