### ISSUE TITLE
HTTP 401 responses when completing app-complete-auth example (Node)

### ISSUE THREAD

**Issue by dan-c-drawboard** [OfficeDev/Microsoft-Teams-Samples#670]
I've completed the setup instructions for the `app-complete-auth` NodeJS example, however all bot interactions are failing with 401 or failing to reach my local server completely.

Adding the app to MS Teams failed initially with an unexplained error with the bot. When retried, it did seemingly install without immediate error, however all messages to the bot are failing to send, and likewise message extension functions are "Unable to reach app". I cannot see any request activity occurring in ngrok's log, so Teams is not reaching my local machine at all.

Testing the bot through Azure's Test in Web Chat feature, I can see request activity in ngrok, however all requests are being met with `401 Unauthorized`. The same effect is produced by testing with the Bot Framework Emulator connecting directly to `http://localhost:3978/api/messages`.

The bot registration has been configured as UserAssignedMSI (this was unspecified in the instructions) and I am using an unpaid ngrok account. 

Any help or advice would be greatly appreciated.

**Comment by ChetanSharma-msft** [comment]
Hello @dan-c-drawboard - Thanks for reporting your issue.
We will further investigate on this issue and let you know the updates.

**Comment by sayali-MSFT** [comment]
@dan-c-drawboard - We are not able to repro the issue, as it is working fine from our end.
Could you please check the ngrok configuration once? 
![ngrok1](https://user-images.githubusercontent.com/93527375/213360370-c390ccef-6ada-43b2-bea3-f13dc63e9582.png)
![ssoauth](https://user-images.githubusercontent.com/93527375/213360502-87531bd5-0abc-43bf-a38b-3a93c23e4f36.png)

**Comment by sayali-MSFT** [comment]
@dan-c-drawboard -Did you get chance to check the configuration?

**Comment by dan-c-drawboard** [comment]
Hello - thank you for your interest and sorry for my delayed response. This issue can be closed, but I do have some feedback below:

My problems stemmed from apparent mistakes made when completing the Azure setup. I feel that the instructions for setting up the bot registration is missing some detail.

There is ambiguity when creating the bot: at the point of selecting Microsoft App ID, where the default selection (and other MS bot documentation) suggests that **User-Assigned Managed Identity** is the correct option, when the sample `.env` file assumes the bot has been configured as **MultiTenant**. It would be nice to have this setting and its implications clearly explained in detail when executing this step.

Additionally on the same page of the bot registration, there is no mention of using the existing app registration option to create the bot using the app registration ID created in the first chapter of the setup instructions. I reattempted the entire setup process multiple times before making this leap on a whim. This may have been a common sense assumption for users with Azure experience, but this seems like a massive omission for anyone unfamiliar with Azure, compounded by deferring the setup to the generic bot-setup article.

Thank you again for your engagement.

**Comment by ChetanSharma-msft** [comment]
@dan-c-drawboard - Thanks for sharing your valuable feedback.

We will keep it in mind and will update the instructions accordingly.
