### ISSUE TITLE
Proactive Installation Sample App - Cannot get it to work

### ISSUE THREAD

**Issue by mrhub** [OfficeDev/Microsoft-Teams-Samples#672]
I do get a error in the log when running the sample, 
`System.AggregateException: Failed to acquire token for client credentials. (AADSTS700016: Application with identifier 'Application (client) ID' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.`
Im using the client id from my Azure bot - Configuration - Microsoft App ID in the azure portal.

The instruction is a little unclear, perhaps im doing it wrong...
I joined the first and second step, since I do not see any use for the second app registration, and use the app registration with the API permissions when creating the azure bot service.

**Comment by Prasad-MSFT** [comment]
@mrhub - From the error message it seems like the app id is not available in directory. Please verify if you are using correct client/app id. Also are you using [C#](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-proactive-messaging/csharp) sample or [teamsfx ](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-proactive-messaging-teamsfx)sample?
When you set up the bot do it through the CLI, don't try to do it through the web interface.
Please refer similar issue [here](https://github.com/microsoft/BotBuilder-Samples/issues/1974) and let us know if this helps.

**Comment by mrhub** [comment]
Yes, I do have the permissions, but I did not that instructions, I asked our admin to approve it manually. Does it matter?

![image](https://user-images.githubusercontent.com/3517450/213183091-3339083f-6f2f-4380-bca5-2e614f807035.png)

**Comment by Prasad-MSFT** [comment]
The permissions seem to be correctly configured only. But please do follow the instruction mentioned and verify if you have added proper ids and secret details in `appsettings.json` file as well. Make sure to upload the app at org level, so that you can get `AppCatalogTeamAppId `and after that try to add the app in either personal or team scope.
FYI, we have tried this sample and it works properly at our end.

**Comment by mrhub** [comment]
Okay, the instruction says to upload a custom app, that do not get in our "org directory". So I did upload the zip file to our org and I can see it now in teams.
And I can see the app using the graph endpoint 
`https://graph.microsoft.com/v1.0/appCatalogs/teamsApps?$filter=distributionMethod eq 'organization'` 
to get the AppCatalogTeamAppId.
But I do not get that far, exception thrown when calling 
`var currentPage_Memebers = await TeamsInfo.GetPagedMembersAsync(turnContext, 10, null, cancellationToken);`
exception text:
`AdalServiceException: AADSTS700016: Application with identifier 'AppId' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.`

I do not have any control over the tenantId, it is read from the "turncontext" that is sent from teams.

What am I doing wrong??

**Comment by Prasad-MSFT** [comment]
There is some issue with the app id/tenant id you created and configured. Could you please retry the steps by following the guidelines step by step creating new app id? https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-proactive-installation

**Comment by mrhub** [comment]
I checked the Nodejs installation guide, and there it says 
`4. Supported account types: Select "Accounts in any organizational directory"`
there is no mention of multitenant in the csharp guide...

Now it works, changed from single tenant to multitenant.

Thanks for your support!
