### ISSUE TITLE
How can we integrate Amazon lex chat bot into Teams channel

### ISSUE THREAD

**Issue by goutham54** [OfficeDev/Microsoft-Teams-Samples#675]
Hi, I want to integrate **amazon lex chat bot into teams channel** . I'm unable to find any related documentations .

I found one link : https://www.linkedin.com/pulse/cleverer-chatbot-amazon-lex-microsoft-teams-wuming-zhang/

in this link they provided information like we have to create one sample echo bot farmwork  . could you please provide  any  **sample c# code** where we can link up with amazon lex and teams channel . what are apis or sdk's  we have to use.

**Comment by ChetanSharma-msft** [comment]
Hello @goutham54 - Thanks for raising your issue.
We will investigate your query and let you know.

**Comment by Meghana-MSFT** [comment]
While we are checking this at our end sharing an echo bot sample for your reference -

1. https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/02.echo-bot
2. https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=csharp%2Cvs#start-the-emulator-and-connect-your-bot

**Comment by ChetanSharma-msft** [comment]
Hello @goutham54 - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by vinayburam** [comment]
Have you integrated Lex chatbot  on teams
I am trying to achive same. Can you please guide
