### ISSUE TITLE
Need assistance in understanding tab device permission in Mac and Android device

### ISSUE THREAD

**Issue by SushmaSathyanarayana** [OfficeDev/Microsoft-Teams-Samples#679]
Need assistance in understanding tab device permission in Mac and Android device

**Comment by ChetanSharma-msft** [comment]
Hello @SushmaSathyanarayana - Could you please share all your queries here, so that we can try to help you further?

**Comment by SushmaSathyanarayana** [comment]
Hi Chetan,

Thanks for reaching out.

As per the article Request device permissions for your Microsoft Teams app - Teams | Microsoft Learn<https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=mobile%2Cteamsjs-v2%2Cmobile1> and GitHub sample Microsoft-Teams-Samples/README.md at main * OfficeDev/Microsoft-Teams-Samples * GitHub<https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-device-permissions/nodejs/README.md> the tab permission should work fine in all the client like iPhone, mac, window and Android.

However when one of our customer is running the sample in mac they are not be notified for prompt to enabled the permission or the app is not been listed in the setting->app permission. I verified that the functionality works fine on Windows client. Need your assistance on iPhone and mac.

Thanks in advance!!

Regards,
Sushma S

**Comment by Nivedipa-MSFT** [comment]
Hi @Sushma,

We will test this in iPhone and update you soon.

You can share your Feedback<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FDevSupportFeedback&data=05%7C01%7Cv-nivedipasu%40microsoft.com%7Cd7624a16170a4a99ea8808daf33e09d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638089745518816907%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wpgbV0A2Eiy18iVhQmrqdtXlV2KXjiH6q46A3DEwIsE%3D&reserved=0>/Escalate<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FDevCommunityEscalationForm&data=05%7C01%7Cv-nivedipasu%40microsoft.com%7Cd7624a16170a4a99ea8808daf33e09d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638089745518816907%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mVD%2B3Lg5sbYqnx1ZjVZnhM76wH4c1WvJqh1DjITF9nk%3D&reserved=0>

Thanks,
Nivedipa Suryavanshi
Teams Dev Community Response

**Comment by sayali-MSFT** [comment]
@SushmaSathyanarayana - We have tried on IOS device, it is working fine from our end.
Sample Link-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-device-permissions/nodejs
IOS version- 16.2
IOS Teams Version-4.23.772022235001/0110

Also If you want to add permissions on desktop you can click on App Permission icon-
![tabdevicepermiison](https://user-images.githubusercontent.com/93527375/213864475-88caee15-cc78-4480-b296-b814f42c8af9.png)


https://user-images.githubusercontent.com/93527375/213865862-678b4e02-91b5-4773-9d44-982cd1a5208e.mp4

![MicrosoftTeams-image (30)](https://user-images.githubusercontent.com/93527375/213865896-61458ac5-3b94-443f-bfb3-9670c4f98536.png)

**Comment by SushmaSathyanarayana** [comment]
Thanks Sayali.

I will share an update to cx and get back if there are any questions.

Regards,
Sushma S

**Comment by ChetanSharma-msft** [comment]
Hello @SushmaSathyanarayana  - Hope your queries are resolved.
We are closing this issue for now, please feel free to reopen it, if required.
