### ISSUE TITLE
Tab SSO - Not working with Azure deployment

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/Microsoft-Teams-Samples#68]
Hi Team,
This is related to the [tab-personal-sso-quickstart](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-personal-sso-quickstart/ts) sample.
I created the same sample by using visual studio toolkit.
**It is working fine with Ngrok but **not working with azure app service**.

Tried to deploy to azure webapp using following steps:
- npm run build
- Deploy to azure web app from visual studio code
- Created azure front door 

Once deployed tried to access app service URL(https://****.azurewebsites.net and tried to access https://****.azurefd.net)
Showing following error: "You do not have permission to view this directory or page."

Added "build/index.html" in app service configuration-> Default documents.
Able to access index.html. But when tried to access components(https://****.azurewebsites.net/tab), showing below error: 
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

Could you please let us know if we are missing some steps? or any other changes required to make it working in azure appservice

**Comment by karthigb** [comment]
@SubbaReddi Azure App Registrations doesn't support *.azurewebsites.net hosting URLs. The team is working to remedy this.

**Comment by SubbaReddi** [comment]
Hi @karthigb,
As we have limitation with azurewebsites, i already created azure front door and using the same in app registrations.
So, can you reopen the issue.

**Comment by SubbaReddi** [comment]
@karthigb Please let me know if we need to submit new bug for this issue.

**Comment by SubbaReddi** [comment]
Had discussion internally. It seems deploying to azure app service is not working with current project and it will be released in next few weeks.

**Comment by aosolis** [comment]
@karthigb @subbareddi IIRC AAD has lifted the restriction on azurewebsites.net
