### ISSUE TITLE
Receiving UserNotAuthorizedToGrantResourceSpecificPermission when adding bot to meeting

### ISSUE THREAD

**Issue by ericjungsait** [OfficeDev/Microsoft-Teams-Samples#686]
Implemented "Meeting-Attendance-bot" in Azure and appears to be running (based on logs) but when I try to add to a meeting, I keep getting 401 with an error of UserNotAuthorizedToGrantResourceSpecificPermission. I've granted Graph API permissions for my tenant but it still won't allow me to add.

**Comment by Prasad-MSFT** [comment]
From the error message it seems like there is some issue at granting RSC permissions. Could you please refer this doc and confirm if you have added required permissions and granted access?https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent
Also please confirm if you are using below sample and is it C# sample or NodeJS?
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-attendance-report

**Comment by ericjungsait** [comment]
> From the error message it seems like there is some issue at granting RSC permissions. Could you please refer this doc and confirm if you have added required permissions and granted access?https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent Also please confirm if you are using below sample and is it C# sample or NodeJS? https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-attendance-report

Thanks for reply, according to "https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-meetings-attendance-report-nodejs/", > Application permissions: OnlineMeetingArtifact.Read.All is required with admin consent, so I have that.

For testing purpose, I've also granted some other accesses as well like OnlineMeetings.ReadWrite.All, ChatMessage.Read.All...
**What permission is actual required to run this code...?**

We are using NodeJS version at the moment.

**Comment by Prasad-MSFT** [comment]
We tried to repro this issue by following below sample (https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-attendance-report/nodejs), however the app works fine at our end.
We have granted Application permissions: `OnlineMeetingArtifact.Read.All`.
![image](https://user-images.githubusercontent.com/62237649/215445245-86ee1122-cad3-4f86-9e00-a6738aff2bca.png)
Please make sure to allow applications to access online meetings on behalf of a user following below doc:
https://learn.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy

**Comment by ericjungsait** [comment]
> We tried to repro this issue by following below sample (https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-attendance-report/nodejs), however the app works fine at our end. We have granted Application permissions: `OnlineMeetingArtifact.Read.All`. ![image](https://user-images.githubusercontent.com/62237649/215445245-86ee1122-cad3-4f86-9e00-a6738aff2bca.png) Please make sure to allow applications to access online meetings on behalf of a user following below doc: https://learn.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy

Thanks for reply,
I'm trying to review what I've done for setting up applicatino access policy using powershell, on this part:
_Identify the app’s application (client) ID and the user IDs of the users on behalf of which the app will be authorized to access online meetings.

Identify the app’s application (client) ID in the [Azure app registration portal](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade).
Identify the user's user (object) ID in the [Azure user management portal](https://portal.azure.com/#blade/Microsoft_AAD_IAM/UsersManagementMenuBlade)_

Does this mean I need to create 1 additional random user account in 365?

**Comment by Prasad-MSFT** [comment]
1. Created an application access policy:
We run the following cmdlet, replacing the Identity, AppId
`New-CsApplicationAccessPolicy -Identity Test-policy -AppIds "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -Description "description here"`
2. Granted the policy to the user to allow the app ID contained in the policy to access online meetings on behalf of the granted user
`Grant-CsApplicationAccessPolicy -PolicyName Test-policy -Identity "xxxxc4xx-2xxb-xxxx-xxxx-xxxxd7xxxxxx"`

**.env file:**
```
MicrosoftAppId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
MicrosoftAppPassword=xxxxx~qxxjj-XxxxxP-Ixxx.Vxxmxxxxd5xxxxll
MicrosoftAppTenantId=3xxxx8xx-7xxx-xxx0-9de0-x7x7xxx69xxf
UserId=xxxxc4xx-2xxb-xxxx-xxxx-xxxxd7xxxxxx
```

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
