### ISSUE TITLE
bug bot-file-upload Python

### ISSUE THREAD

**Issue by tacoblacho** [OfficeDev/Microsoft-Teams-Samples#693]
Hi I have taken the code from bot-file-upload python and ran it. It goes ok where it shows:

![image](https://user-images.githubusercontent.com/42721475/215865190-33812362-9594-4c6f-92ae-874606f3f29a.png)

The Decline button works fine, but the ALLOW button doesn't work no matter how many times I try, it says: "Something went wrong. Try Again:

![image](https://user-images.githubusercontent.com/42721475/215865502-93c94833-6136-4c21-9848-187af2f83af8.png)

I have set the config AppID to the one that my bot is registered on. It seems Allow button is not working. Can you please help?

**Comment by Meghana-MSFT** [comment]
@tacoblacho - We already have a bug raised for this issue. Team is investigating the issue; we will keep you posted on the updates. Thanks!

**Comment by tacoblacho** [comment]
Ok Thanks, in the mean-time I need to deploy my solution. Is there any work-around to send files to a user, besides this method?

**Comment by Meghana-MSFT** [comment]
Can you please check if this helps? - https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http#example-4-send-a-message-with-file-attachment-in-it

**Comment by tacoblacho** [comment]
Thanks, I looked into it and there is no Python implementation of it if I understand correctly? Or if there is, where can I find a tutorial please?

**Comment by Meghana-MSFT** [comment]
The possible work-around could be using Graph. Here is a tutorial on [Build Python apps with Microsoft Graph](https://learn.microsoft.com/en-us/graph/tutorials/python?tabs=aad). 
But please note that The Microsoft Graph SDK for Python is currently in preview and should not be used in production.

**Comment by tacoblacho** [comment]
Ok, this requires me to re-write a lot of the code. Do you have a possible time-line expectation for this bug fix in the Bot FrameWork SDK? Is it weeks or is it months? Thanks

**Comment by Meghana-MSFT** [comment]
We currently do not have an exact ETA, we will keep you posted on the updates related to the bug.

**Comment by tacoblacho** [comment]
ok I see, thanks

**Comment by ChetanSharma-msft** [comment]
Fixes are done and PR is merged.
Closing this issue. Please feel free to reopen it if required.
