### ISSUE TITLE
Simple Auth Sample does not await app initialialization on simple_end page

### ISSUE THREAD

**Issue by mscherotter** [OfficeDev/Microsoft-Teams-Samples#694]
I am trying to get simple auth in my Teams app working with Adobe ID (a third party Oauth provider that I use on my site).
I am following the sample [here](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-auth/nodejs/src/views/tab/simple).  Everything is working to authorize with the Adobe ID, but when it gets to my end authentication page like [this](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/app-auth/nodejs/src/views/tab/simple/simple-end.hbs), I get an exception thrown with the message "SDK initialization timed out." when I call `await app.initialize();`.  The sample shown does not have the `await` term before app.initialize().  Is that incorrect?  If I remove the await, my code later on to notify authentication of success, fails with the exception "The library has not yet been initialized".
        authentication.notifySuccess("Yippee");
1. what do I need to do to allow app.initialize() to work?
2. How can the sample work if there is no await before it?

**Comment by Prasad-MSFT** [comment]
@mscherotter - Could you please confirm which SDK version and MS Teams version you are using?
Also, could you please try using `microsoftTeams.app.initialize().then(() => { }` and check if it helps?

**Comment by mscherotter** [comment]
@microsoft/teams-js 2.7.1
I get the same timeout using that method as well.

**Comment by Prasad-MSFT** [comment]
@mscherotter - We tried [this](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-auth) sample using `@microsoft/teams-js 2.7.1` and it worked for us without throwing any exception/error.
Checked with MS Teams desktop client. `Microsoft Teams Version 1.6.00.2979`

**Comment by Prasad-MSFT** [comment]
@mscherotter - Could you please confirm if your issue has been resolved or are you still looking for any help?

**Comment by ChetanSharma-msft** [comment]
Hello @mscherotter - Hope your issue has resolved.
We are closing this issue for now, please feel free to reopen it, if required.
