### ISSUE TITLE
Issue with setting up Azure Bot to create attendance list for Teams Meeting.

### ISSUE THREAD

**Issue by SAIT-Ramiz** [OfficeDev/Microsoft-Teams-Samples#700]
Azure Bot has been set up to create an attendance report of Teams meeting particpants. With some troubleshooting I found that MS Teams is having some issues with Azure Bot Services, but I am not able to track the actualy issue.
![Teams Error](https://user-images.githubusercontent.com/124753228/217418070-f68bd37f-3629-443e-91ca-11bb0574ebf4.PNG)

- Also can you please help me with exact permissions required to see the attendance report. Some part of the configuration seems to be working as I see Hello Screen but when attendee's join I do not see automate repy "Hello and Welcome to Meeting Attendance Bot"
![Bot](https://user-images.githubusercontent.com/124753228/217420041-150ec0d5-4a2c-4bcd-a165-82e49e0a6e8b.PNG)

I have been following this article but no luck. https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-meetings-attendance-report-nodejs/

**Comment by sayali-MSFT** [comment]
@SAIT-Ramiz - Thanks for reporting your issue.
We will investigate this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@SAIT-Ramiz - 
1.Did you get any console error while running the application?
One of the following permissions is required to see the attendance report.
<html>
<body>


Permission type | Permissions (from least to most privileged)
-- | --
Delegated (work or school account) | OnlineMeetingArtifact.Read.All
Delegated (personal Microsoft account) | Not supported.
Application | OnlineMeetingArtifact.Read.All


</body>
</html>

**Comment by SAIT-Ramiz** [comment]
No, I did not get any error, but I know it is not working. As per this articale it show the participant list should show after the meeting is ended.
https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-meetings-attendance-report-nodejs/

![Bot1](https://user-images.githubusercontent.com/124753228/217576974-4a4f0c42-34f7-4fce-a06e-d944c1a9a7cc.PNG)

However Teams shows this error, which is very Vague, it doesn't say what is wrong.
![Teams Error1](https://user-images.githubusercontent.com/124753228/217579833-81723a27-ba49-4801-b986-ddc36d146077.PNG)
![Web Chat Error](https://user-images.githubusercontent.com/124753228/217580179-3459c510-44a5-435c-b860-223fd6be19cd.PNG)

**Comment by SAIT-Ramiz** [comment]
Hi @ChetanSharma-msft 

Thank you for your help on this. The above error that I was getting is from App that was created by my Team Mate. However I am now trying to create a new app. Can you please help to verify few things for me. 
 I am following this article but I am not finidng the instruction very clear. https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-meetings-attendance-report-nodejs/

- Do we only need the following permission to set up attendance bot to mark attendance and show the list of participant during and after the meeting as shown in the above document.
- I am working on creating a new App can you help me verify how to create a messaging enpoint URL?
-  When I try to do admin consent it give me following error.
![Consent Error](https://user-images.githubusercontent.com/124753228/217935351-c843be58-f59a-4fbe-895e-8535c15d4381.PNG)

Your help is appreciated

**Comment by ChetanSharma-msft** [comment]
Hello @SAIT-Ramiz - 
1) You need to add below Graph API permissions while doing AAD App registration:
> Application permissions:
OnlineMeetingArtifact.Read.All

2) If you have permissions to give Admin consent you can use below link: https://login.microsoftonline.com/common/adminconsent?client_id=<%appId%>

3) Messaging Endpoint will be like:
Your complete domain URL/api/messages


Example:
https://app-azurebot.azurewebsites.net/api/message 

4) Please check if you are passing proper app id while doing admin consent.

We will also try this sample from our end and let you know the updates.

**Comment by SAIT-Ramiz** [comment]
When I try to give Admin consent with the necessary permissions, I get the following error.
![Error](https://user-images.githubusercontent.com/124753228/220403793-fbf59356-7505-4d00-8c2c-d0e598e3f535.PNG)

Sorry but I am not familiar with deploying apps. Can you please tell me what generates URL with /api/messages (do you have any articale that I can follow?

**Comment by sayali-MSFT** [comment]
@SAIT-Ramiz -
1. To add messaging endpoint, please have look into this document-
[Create and register your bot in Azure AD portal](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-messagingextension-searchcommand?tabs=latestversionofvisualstudio&tutorial-step=3)
 
2. Please verify once, are you using below link for permissions to give Admin consent: https://login.microsoftonline.com/common/adminconsent?client_id=<%appId%>

**Comment by SAIT-Ramiz** [comment]
Thank you Sayali for that info. Our Organization is looking for a live attendance solution. Will this resource help to create a live attendance platform. For Example, when meeting starts 5 mins after an Organizer would like to have an attendance report for people who are still in meeting. And would also like to see the attendane report at the end of the meeting. Can you please confirm if the below solution would help with that?

https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-meetings-attendance-report-nodejs/

If that won't servere the requirement, are you aware of another solution that would help with that requirement.

**Comment by sayali-MSFT** [comment]
@SAIT-Ramiz -Above sample, when meeting is ended that time Bot will send you the attendance report.
We will check it internally if we have any solution for live meeting attendance report and get back to you.

If you create Live event that time you will get the live attendance report as well.
Reference Link-https://support.microsoft.com/en-us/office/get-an-attendee-engagement-report-for-a-teams-live-event-b3101733-2eda-48a6-aeb3-de2f2bfecb3a

**Comment by SAIT-Ramiz** [comment]
Thank you @***@***.***>.

It will be great if you can let us know when you hear from internal Team. At this time Live Event option won’t work for us. Thank you though for that.

Regards,

**Comment by sayali-MSFT** [comment]
@SAIT-Ramiz -Currently, we do not support attendance report during the meeting at the moment. 
Could you please help by suggesting this feature on - [Microsoft Teams · Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by ChetanSharma-msft** [comment]
Hello @SAIT-Ramiz - We are closing this issue for now, please feel free to reopen it, if required.
