### ISSUE TITLE
Not handled exception for Graph photo request as Null 

### ISSUE THREAD

**Issue by diegoriera** [OfficeDev/Microsoft-Teams-Samples#702]
The bot-conversation-sso-quickstart is not working well when user profile does not contains photo, it is ending on exception.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/15849138/217801884-33c2580d-50a5-4a67-8f41-54208da2c6e4.png)

**Comment by Nivedipa-MSFT** [comment]
@diegoriera - Thanks for reporting your issue. We will test this and update you soon.

**Comment by diegoriera** [comment]
IcM https://portal.microsofticm.com/imp/v3/incidents/details/366504167/home

**Comment by Nivedipa-MSFT** [comment]
@diegoriera - We are trying this out and will raise the PR for this. Thanks.

**Comment by Nivedipa-MSFT** [comment]
@diegoriera - PR has merged. Could you please test this on latest repository and let us know if you are facing this issue?

**Comment by Nivedipa-MSFT** [comment]
@diegoriera - Did you get a chance to test this?

**Comment by Nivedipa-MSFT** [comment]
@diegoriera - Could you please confirm is your issue resolved or are you still facing this issue?

**Comment by ChetanSharma-msft** [comment]
Hello @diegoriera  - We are closing this issue for now, please feel free to reopen it, if required.
