### ISSUE TITLE
How do you send code snippets?

### ISSUE THREAD

**Issue by Wajeed-msft** [OfficeDev/Microsoft-Teams-Samples#704]
### Discussed in https://github.com/OfficeDev/Microsoft-Teams-Samples/discussions/646

<div type='discussions-op-text'>

<sup>Originally posted by **eduard-grosu** December 28, 2022</sup>
Hello! My bot handles lots of output and need a way to send them in chat using proper formatting.
For the time being I can't seem to find a way to send code snippets using Python's SDK module. Could someone help me with this?
Further, if this is not possible, can you upload files without asking the user to accept the files? I want it to upload in a group chat.

Thanks!</div>

**Comment by Nivedipa-MSFT** [comment]
@eduard-grosu - Thanks for reporting your issue. We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@eduard-grosu - Please let us know if you have any further query here or shall we close this issue?

**Comment by eduard-grosu** [comment]
@Nivedipa-MSFT It can be closed, thanks!

**Comment by Nivedipa-MSFT** [comment]
@eduard-grosu - Thanks for confirmation. Could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u).
