### ISSUE TITLE
graph-activity-feed samples have mismatches in teamsjs versions leading to them not working. And other concerns

### ISSUE THREAD

**Issue by eoinobrien** [OfficeDev/Microsoft-Teams-Samples#705]
Hi, 

I was investigating using activity feed notifications behaviour and I tried to use the samples in this repo to do the testing and I was unable to get it to work.

In the csharp example, I see the following error at https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/917570693b4b615c3aca6f836885d9b4be3caa31/samples/graph-activity-feed/csharp/ActivityFeedNotification/wwwroot/js/auth.js#L5
![image](https://user-images.githubusercontent.com/6508687/218196754-f87e6193-f7a5-4ff0-b531-6e5e34cb4e0c.png).

This is due to a mismatch of teams-js versions. Auth.js expects v2, but _Layout.cshtml which calls auth.js, imports Teams-js SDK v1.11 https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/917570693b4b615c3aca6f836885d9b4be3caa31/samples/graph-activity-feed/csharp/ActivityFeedNotification/Views/Shared/_Layout.cshtml#L9-L11 

There is a similar error in the nodejs example:
![image](https://user-images.githubusercontent.com/6508687/218198247-7af8920b-8016-4c64-b7d6-47d45060728f.png)
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/917570693b4b615c3aca6f836885d9b4be3caa31/samples/graph-activity-feed/nodejs/static/scripts/auth-delegated.js#L7
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/917570693b4b615c3aca6f836885d9b4be3caa31/samples/graph-activity-feed/nodejs/views/GroupChatNotification.ejs#L7-L11

A few other concerns:
* The auth scenario is odd and difficult to understand. The `getAuthToken` calls are automatic, and they include calls to get OBO tokens. I'd recommend having users click a button to login, this makes makes it clear to the users why the are seeing the Auth pop-up.  It also prevents pop-up issues if the user has consented to the SSO previously, but not to those permissions needed for the OBO tokens. In this case, browsers may block the pop up, as it doesn't have a user interaction.
* Mismatch of the versions of team-js used across the samples.
  * Note that there is both `microsoftTeams.initialize()` and `microsoftTeams.app.initialize()` which indicates that the sample is using both v1 and v2 versions of the SDK.
  * ![image](https://user-images.githubusercontent.com/6508687/218149877-d9290e86-e2be-4d61-bb4e-f014417984fb.png)
* Duplicate code in places https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/917570693b4b615c3aca6f836885d9b4be3caa31/samples/graph-activity-feed/nodejs/views/GroupChatNotification.ejs#L80-L82
* Using terms like `taskInfo` which is already a [word used in Teams Platform when working with task modules](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/invoking-task-modules#the-taskinfo-object)
  * https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/917570693b4b615c3aca6f836885d9b4be3caa31/samples/graph-activity-feed/nodejs/views/GroupChatNotification.ejs#L122 
  
 In general I found the example very confusing, and difficult to get working.

**Comment by Prasad-MSFT** [comment]
Hi @eoinobrien - Thanks for reporting this. We will check this at our end and inform you if there is any update.

**Comment by Prasad-MSFT** [comment]
@eoinobrien - We are also able to repro this issue at our end. The sample doesn't seem to work due to mismatch of teams-js versions. 
We will discuss this with respective team and will get the sample updated incorporating necessary changes. Thanks!

**Comment by ChetanSharma-msft** [comment]
Hello @eoinobrien - We have raised a PR for the above suggestions.
Could you please review and share the feedbacks on PR: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/713

**Comment by Prasad-MSFT** [comment]
@eoinobrien - The PR is merged. We are closing this issue for now. Please feel free to reopen if required. 
Thanks!
