### ISSUE TITLE
connector-github-notification is broken

### ISSUE THREAD

**Issue by nikitar** [OfficeDev/Microsoft-Teams-Samples#71]
Hi there,
I've spent a couple of hours trying to run this demo with limited success. Would it be possible for someone to update it to make sure it works? I realise you have a lot of things to do without this, but it's probably a rather trivial task for you. And it's a huge task for many users who are not familiar with the Teams setup.

Some of the issues I encountered:
- The manifest.json is incorrect. It produces errors when trying to side-load it. (Of the "Manifest parsing failed" variety)
- "Zip manifest.json file and sideload to any team" option results in githubconnector.azurewebsites.net app being used, not local ngrok, even though I updated urls in default.json. Probably because the config url is associated with the connector id, it does not come from the manifest.
- When I go for the "Alternative you can set your own connector" option, I manage to access the config page from Teams ("Continue to authenticate to Github"), click "continue" and nothing else happens. Just a blank page. See the screenshot: 
<img width="857" alt="Screenshot 2021-04-15 at 11 47 34" src="https://user-images.githubusercontent.com/396798/114803263-808fa780-9de2-11eb-95de-913be071edf0.png">
This is the part I was unable to get past.
- With the githubconnector.azurewebsites.net option, I was able to get slightly farther, but it failed without explanation during the configuration process too.

Some minor issues:
- Broken link https://msdn.microsoft.com/en-us/microsoft-teams/connectors
- Broken link aka.ms/teamsdocs
- Mentioning mongodb setup in the readme would've been nice, for those new to it. ("Download and install mongodb, change connection string to mongodb://localhost/test")
- I would also appreciate basic instructions on how to test this, how to know if it's working.

**Comment by Wajeed-msft** [comment]
@nikitar - could you please try following the steps mentioned here? 

https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/connector-generic/nodejs

**Comment by nikitar** [comment]
Thanks for the response @Wajeed-msft, I did get that one working for the most part. It does not offer an example of direct integration, however. It is just a configuration page with instructions about how to connect a single channel to a single form. And ms forms already support connectors. I was interested in how direct integration (particularly auth) with a third-party service (like github) would work.

**Comment by Wajeed-msft** [comment]
If you need to authenticate the user as part of loading your page in step 2 above, refer to [this link](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab) for details on how you can integrate login when your page is embedded. 

[Here is sample ](https://github.com/OfficeDev/microsoft-teams-sample-connector-csharp) which shows auth flow implemented with AAD. I'll move this to main repo.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
