### ISSUE TITLE
Search Message Extension error

### ISSUE THREAD

**Issue by wenytang-ms** [OfficeDev/Microsoft-Teams-Samples#719]
Hi team, thanks to your bot samples.
I found an error while running your [msgext-search](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search/nodejs)

My dev env
1. node.js 16
2. chrome latest

When I debug the search query result, there are errors show in console log as following picture.
![image](https://user-images.githubusercontent.com/75360946/220344625-0dad7c86-2e40-4d8d-ace4-2aaa328db17f.png)

It's seeming that there is something wrong with bot registration.  can you share your bot registration configuration?
I just register a multi-env with a new App ID, with a new secret.

Another question is what's the GraphQL resolver error with the `searchMessageExtension` field path?

**Comment by sayali-MSFT** [comment]
@wenytang-ms - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@wenytang-ms -Please follow the given steps in the below document-
https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-messagingextension-searchcommand?tabs=latestversionofvisualstudio&tutorial-step=3
![azureportal](https://user-images.githubusercontent.com/93527375/220602940-efd29e61-62a7-4263-b63f-a0a959ea0e90.png)

**Comment by wenytang-ms** [comment]
Thanks for the reply, this problem seems occasional.
Please feel free to close this issue
