### ISSUE TITLE
context.adapter.getSignInLink is not a function

### ISSUE THREAD

**Issue by guillewu** [OfficeDev/Microsoft-Teams-Samples#722]
I'm following this tutorial: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-adaptive-cards/nodejs/server/bot/botActivityHandler.js#L31

And I'm getting the following error: context.adapter.getSignInLink is not a function.

Is there an updated tutorial? Thanks

**Comment by Nivedipa-MSFT** [comment]
@guillewu - Thanks for reporting your issue. We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@guillewu - We have tested the below sample and follow the readme file for setup. And it was working fine at our end.
We have tested this on windows Teams web client.
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-adaptive-cards/nodejs

Screen recording of the sample test: [recording-2023-02-24-18-31-46.webm](https://user-images.githubusercontent.com/92150070/221185412-3538130c-b1c3-41fd-8eaf-9ceea193b23a.webm)

Could you please download the latest repository and test again.

**Comment by guillewu** [comment]
@Nivedipa-MSFT thanks for your reply! I see the issue is that in this sample it is using `BotFrameworkAdapter` class but it's deprecated (https://learn.microsoft.com/en-us/javascript/api/botbuilder/botframeworkadapter?view=botbuilder-ts-latest)

In other more recent samples it uses `CloudAdapter` class. Do you happen to have an example of how to `getSignInLink` using the `CloudAdapter` class? I can't seem to find it in the source code, nor examples online.

**Comment by Nivedipa-MSFT** [comment]
@guillewu - Could you please refer below NodeJS sample where `CloudAdapter` class has used.
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/14fded521862f3ee9861f07bb1497c2a190ee5f6/samples/app-complete-auth/nodejs/index.js#L50

**Comment by Nivedipa-MSFT** [comment]
@guillewu - Could you please confirm is your issue resolved or let us know if you have any further query here.
