### ISSUE TITLE
Is it possible for a bot to message each member of a team with a personal message when it gets added to a team?

### ISSUE THREAD

**Issue by Admiral-Skye** [OfficeDev/Microsoft-Teams-Samples#728]
I have a requirement for my teams app to inform users that it has been added to a team and what its capabilities are. I would like to do this through directly messaging each member of the team when the bot is added to the team and then to subsequently message any members who are newly added to the team. 

I have read through the documentation on Proactive messaging and from what I can tell from looking at the samples, each seems to indicate that the user needs to either interact with the bot initially or it can post messages to a team that it is listening to for users being added.

Is there a clear example on how this might be accomplished and if it is even possible?

**Comment by sayali-MSFT** [comment]
@Admiral-Skye - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@Admiral-Skye -When you bot is added to the team, you can get a list of the users in the team.
You can use [TeamsInfo.getPagedMembers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.adaptive.teams.actions.getpagedmembers?view=botbuilder-dotnet-preview) to get members details in the team.

If you want to send the message to all members, see 3 point [MessageAllMembers](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/csharp#running-the-sample).,

The bot will send a 1-on-1 message to each member in the current conversation.

[Code snippets](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-conversation/csharp/Bots/TeamsConversationBot.cs#L168)  -
```
 private async Task MessageAllMembersAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            var teamsChannelId = turnContext.Activity.TeamsGetChannelId();
            var serviceUrl = turnContext.Activity.ServiceUrl;
            var credentials = new MicrosoftAppCredentials(_appId, _appPassword);
            ConversationReference conversationReference = null;

            var members = await GetPagedMembers(turnContext, cancellationToken);

            foreach (var teamMember in members)
            {
                var proactiveMessage = MessageFactory.Text($"Hello {teamMember.GivenName} {teamMember.Surname}. I'm a Teams conversation bot.");

                var conversationParameters = new ConversationParameters
                {
                    IsGroup = false,
                    Bot = turnContext.Activity.Recipient,
                    Members = new ChannelAccount[] { teamMember },
                    TenantId = turnContext.Activity.Conversation.TenantId,
                };

                await ((CloudAdapter)turnContext.Adapter).CreateConversationAsync(
                    credentials.MicrosoftAppId,
                    teamsChannelId,
                    serviceUrl,
                    credentials.OAuthScope,
                    conversationParameters,
                    async (t1, c1) =>
                    {
                        conversationReference = t1.Activity.GetConversationReference();
                        await ((CloudAdapter)turnContext.Adapter).ContinueConversationAsync(
                            _appId,
                            conversationReference,
                            async (t2, c2) =>
                            {
                                await t2.SendActivityAsync(proactiveMessage, c2);
                            },
                            cancellationToken);
                    },
                    cancellationToken);
            }

            await turnContext.SendActivityAsync(MessageFactory.Text("All messages have been sent."), cancellationToken);
        }

```

Sample Link-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/csharp

**Comment by Admiral-Skye** [comment]
@sayali-MSFT Excellent! that worked flawlessly! 

Follow up question, Is there a mechanism I can leverage to prevent the same user from receiving a message if the bot is added to another team that that user is also a member of?

**Comment by sayali-MSFT** [comment]
@Admiral-Skye -There is no SDK or API to achieve the scenario. You need to add the custom logic to achieve this.

**Comment by Admiral-Skye** [comment]
@sayali-MSFT is it possible to access the state object(a) for the newly created conversation?

**Comment by sayali-MSFT** [comment]
@Admiral-Skye -Could you please elaborate more on your requirement?

**Comment by Admiral-Skye** [comment]
@sayali-MSFT Most examples that make mention of remembering conversation with your bot make use of the state management documented here: https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0#state-management

Is it possible for me to access this state management when creating a new conversation?

**Comment by sayali-MSFT** [comment]
@Admiral-Skye -Could you please refer the below sample- https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/45.state-management/Bots/StateManagementBot.cs

**Comment by ChetanSharma-msft** [comment]
Hello @Admiral-Skye - We are closing this issue for now, please feel free to reopen it, if required.
