### ISSUE TITLE
Having to reinstall app within teams whenever the mentionNotificationHttpTrigger function on azure is restarted/deployed

### ISSUE THREAD

**Issue by jamesburton85** [OfficeDev/Microsoft-Teams-Samples#729]
Hi, im testing with the adaptive card bot samples and have successfully deployed a teams app via the Teams Admin Portal to a bunch of machines. The problem is when I have to make a change or even just restart the mentionNotificationHttpTrigger azure function from the azure portal( that iv published via the teams tool kit from vs code) the app in teams will no longer receive messages until the user uninstalls the app and it is reinstalled. Am i missing something with how all this stuff connects to each other? Im not receiving any errors that i can see.

**Comment by sayali-MSFT** [comment]
@jamesburton85 - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by jamesburton85** [comment]
Solved it by implementing blob storage for the connections
