### ISSUE TITLE
Request to update bot-calling-meeting tutorial

### ISSUE THREAD

**Issue by PabloLION** [OfficeDev/Microsoft-Teams-Samples#737]
Hi, I recently followed this tutorial: [Calling and Meeting Bot Sample V4](https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-bot-calling-meeting-csharp/). And I want to make some fix to it.

1. Typo: the `Get-CsApplicationAccessPolicy -PolicyName Meeting-policy-dev -Identity "<<microsoft-app-id>>"` should actually be `Get-CsApplicationAccessPolicy -Identity Meeting-policy-dev`, according to docs of [Get-CsApplicationAccessPolicy](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsApplicationAccessPolicy.md)
2. I'd like to add a short part for `pwsh` for mac developers, like installing powershell and its modules with homebrew / dotnet. For example <https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-install>
3. folder `TeamsAppManifest` should be `Manifest`(?)
That's all so far. Should I make a PR?

**Comment by sayali-MSFT** [comment]
@PabloLION - Thanks for reporting your issue.
We will check this at our end and update the document, accordingly, let you know.

**Comment by PabloLION** [comment]
Thanks. If it's possible, would you mind adding me as a co-author to the commit?

**Comment by sayali-MSFT** [comment]
@PabloLION -Could you share the more information about second point.
Need to add a short part for pwsh for mac developers?

**Comment by PabloLION** [comment]
I would add `brew install powershell/tap/powershell` and the `pwsh`, then offer this link for users to check more details <https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.3>

**Comment by sayali-MSFT** [comment]
@PabloLION -Could you please raise PR on same repo for the suggested changes.

**Comment by PabloLION** [comment]
Yea sure, but I'm planning to do it much later like in a month. Is that OK?

**Comment by sayali-MSFT** [comment]
@PabloLION -Sure. Please inform once you raise the PR.

**Comment by ChetanSharma-msft** [comment]
Hello @PabloLION - Could you please let us know whether you have already raised an PR for it?

**Comment by ChetanSharma-msft** [comment]
We will review the PR and merge it accordingly.
