### ISSUE TITLE
401 Unauthorized Error Ngrok

### ISSUE THREAD

**Issue by mlimyadi5** [OfficeDev/Microsoft-Teams-Samples#738]
[12:06 PM] Limyadi, Matthew
Hi everyone I hope all is well, I have been working on getting a bot setup for the C# Sequential Flow Adaptive Card and I think I have hit a roadblock. I have attached an image of the error messages I am getting when trying to call the bot and test a sample incident. Any advice is appreciated thanks for your help, and look forward to hearing back from you.  

Here is the link to the article I am currently following: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-sequential-flow-adaptive-cards/csharp 

Error messages:
<img width="1569" alt="Screenshot 2023-03-13 at 11 57 58 AM" src="https://user-images.githubusercontent.com/114121284/224768511-c6dc72a2-d7ec-471b-9f1d-49d7ed7567d1.png">

**Comment by sayali-MSFT** [comment]
@mlimyadi5 - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by mlimyadi5** [comment]
@sayali-MSFT Thank you for your help. Just wanted to provide a quick update, I am now getting a 200 OK message followed by a 501 Not Implemented Error. 
![Screenshot 2023-03-14 at 1 17 44 PM](https://user-images.githubusercontent.com/114121284/225086271-5dd17a29-8b5e-4e91-b9b8-3b3f88d1b5f9.png)

**Comment by sayali-MSFT** [comment]
@mlimyadi5 -Have you updated the messaging endpoint in Bot?
While registering the bot, use https://<your_ngrok_url>/api/messages as the messaging endpoint.

**Comment by sayali-MSFT** [comment]
@mlimyadi5 -We are also trying the same sample but not able to repro the issue.
Could you please check messaging endpoint url in bot registration and also follow the steps in the given [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-sequential-flow-adaptive-cards/csharp#setup)?

While registering the bot, use https://<your_ngrok_url>/api/messages as the messaging endpoint.


https://user-images.githubusercontent.com/93527375/225525238-474c295f-6a1e-44e7-a131-a796f7239ac6.mp4

**Comment by mlimyadi5** [comment]
Hi @sayali-MSFT I was able to resolve this issue by reregistering the AAD app and recreating the bot then changing the settings from single tenant to multi-tenant, thank you for your time!
