### ISSUE TITLE
(BotBuilder) Input.Text placeholder color is not correct when isMultiline is True

### ISSUE THREAD

**Issue by pcanas** [OfficeDev/Microsoft-Teams-Samples#741]
## Describe the bug
Input.Text `placeholder` color is the same as the `value` color when `"isMultiline": True`. If this value is False, `placeholder` shows the appropriate behaviour.

Adaptive card, version 1.5

Your colleagues at the [BotBuilder team have confirmed that the issue is in your end and happens language-independent.](https://github.com/microsoft/botbuilder-python/issues/1989#issuecomment-1470989007)

## To Reproduce
1. Create a card with both versions. See the difference.

## Expected behavior
Placeholder should have a lighter color when `"isMultiline": True`

## Screenshots
<img width="444" alt="Captura de pantalla 2023-03-08 a las 16 18 30" src="https://user-images.githubusercontent.com/32467089/223752871-0b882834-6fa8-4a51-8d3a-4fc6a96049ea.png">

**Comment by Nivedipa-MSFT** [comment]
@pcanas - Thanks for reporting your issue. We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@pcanas - We have tested for both isMultiline is True and false using adaptive card version 1.5. For both the placeholder text is not lighter. Its looking same as normal text.
We have raised a bug for the same and we will let you know once we get any updates on it.

![image](https://user-images.githubusercontent.com/92150070/225556100-1b3a9602-0e98-4424-bc59-1be707298edd.png)

**Comment by ChetanSharma-msft** [comment]
Hello @pcanas - Sorry for delay in response.
We will check on the bug status with engineering team and let you know the updates.

**Comment by pcanas** [comment]
Thank you, looking forward to any updates

**Comment by Nivedipa-MSFT** [comment]
@pcanas - The engineering team has provided an update stating that this behavior is intentional. The current color already aligns with the default placeholder color, specifically the compose editor placeholder. It's important to note that this color is predefined by Fluent UI and applies universally across the Teams client.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
