### ISSUE TITLE
How to download live recorded video from teams in bot.

### ISSUE THREAD

**Issue by ShobharajaNagarro** [OfficeDev/Microsoft-Teams-Samples#751]
How to download the live recorded video in bot composer or SDK.
For example to download attachment in bot we usually get contentUrl or downloadUrl properties in Activity.Attachments

I'm getting following info in Activity.Attachemnts
`[ { "contentType": "text/html", "content": "<div><video src=\"https://as-api.asm.skype.com/v1/objects/x-xx-xx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/views/video\" itemscope=\"\" itemtype=\"http://schema.skype.com/AMSVideo\" data-duration=\"PT1.406S\" width=\"1280\" height=\"720\">\r\nVideo-Clip</video></div>" } ]`

![image](https://user-images.githubusercontent.com/127189165/227475923-9e8b9e93-c0a6-42d0-8c7e-1882b6f9f57e.png)

**Comment by Meghana-MSFT** [comment]
If you want download live recorded video using record a video clip option, then currently it is not supported. As you correctly said the bot does not have contentUrl or downloadUrl properties in Activity.Attachments.


 ![image](https://user-images.githubusercontent.com/81138249/227507474-f916af74-5d7f-43ed-84d3-700f9ce2f9a4.png)

**Comment by ChetanSharma-msft** [comment]
Hello @ShobharajaNagarro - Please let us know if you need any further help here or shall we close this issue?

**Comment by ChetanSharma-msft** [comment]
Hello @ShobharajaNagarro - Hope your issue has resolved.
We are closing this issue for now, please feel free to reopen it, if required.
