### ISSUE TITLE
How to enable microphone option for bot in teams

### ISSUE THREAD

**Issue by ShobharajaNagarro** [OfficeDev/Microsoft-Teams-Samples#752]
In teams you can send voice messages to user. The microphone option is not available if i want to send voice message to a bot.

Microphone button is enabled in personal chat
![image](https://user-images.githubusercontent.com/127189165/227476208-dc1aa49a-714d-4bbf-b9bd-52d7a9b2b428.png)

Microphone option is not available for bot
![WhatsApp Image 2023-03-24 at 14 37 56](https://user-images.githubusercontent.com/127189165/227558076-0e28783c-acba-40d4-9645-eed061c13f85.jpg)

**Comment by sayali-MSFT** [comment]
@ShobharajaNagarro - Please go through [Device capabilities](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/device-capabilities-overview) to integrate device capabilities, such as camera, QR or barcode scanner, photo gallery, microphone, and location with web apps.

**Comment by ChetanSharma-msft** [comment]
Hello @ShobharajaNagarro - Please let us know if you need any further help here or shall we close it?

**Comment by ChetanSharma-msft** [comment]
Hello @ShobharajaNagarro - We are closing this issue for now, please feel free to reopen it, if required.
