### ISSUE TITLE
The resource principal named RESOURCE_ID/TENANT_NAME.sharepoint.com was not found in the tenant

### ISSUE THREAD

**Issue by Shmata** [OfficeDev/Microsoft-Teams-Samples#754]
Hey guys,

I face with below error, could you please guide me how to solve it ? 
**The resource principal named RESOURCE_ID/TENANT_NAME.sharepoint.com was not found in the tenant named MY_COMPANY_NAME. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.**

Thanks in advance.

**Comment by sayali-MSFT** [comment]
@Shmata - Thanks for reporting your issue.
Could you please share the repro steps, so that we can try it from our end.

**Comment by ChetanSharma-msft** [comment]
Hello @Shmata - We are closing this issue for now, please feel free to reopen it, if required.
