### ISSUE TITLE
bot-calling-meeting play sounds when people join meeting

### ISSUE THREAD

**Issue by kmulvey** [OfficeDev/Microsoft-Teams-Samples#757]
Is it possible to get the bot-calling-meeting example to play a sound when people join the call? If so, can you point me to where i can detect that a new person has joined as well as how to play the sound? Thanks in advance

**Comment by Prasad-MSFT** [comment]
@kmulvey - Please refer below docs which might help:
1.https://learn.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/calls-meetings-bots-overview#real-time-media
2.https://learn.microsoft.com/en-us/graph/api/call-playprompt?view=graph-rest-1.0&tabs=http

**Comment by kmulvey-frameable** [comment]
thanks

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
