### ISSUE TITLE
How to integrate AWS Lexv2 into Teams

### ISSUE THREAD

**Issue by killua-7** [OfficeDev/Microsoft-Teams-Samples#761]
Hello, I am working on a Lex Bot that I would like to integrate into Teams but I haven't found any updated documentation on how to do so. 

Is it possible to integrate and if so, is there any examples on how to do so? Thanks.

**Comment by Meghana-MSFT** [comment]
Could you please refer this thread once - https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/675?

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
