### ISSUE TITLE
Possible for an app to read transcription data from a Teams meeting while it is in progress?

### ISSUE THREAD

**Issue by TetuHirai** [OfficeDev/Microsoft-Teams-Samples#763]
Is it possible to write code to read transcriptions in real-time from a Teams meeting while it is in progress? For example, if the speaker says "Hello, welcome to this workshop," I want the code to read the transcript data (that Teams auto-generated) associated with this as, for example, "Kevin: Hello, welcome to this workshop." The code can then further process this data in real-time.

The sample below seems to be able to read transcript data for meetings that have ended, but I need to develop an app to read this data *during* a Teams meeting (as each sentence of the transcript is generated).
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-transcription/csharp

The documentation below seems to indicate that we can only access the transcript data after the meeting has ended, but does anybody know of a workaround to get around this limitation?
https://learn.microsoft.com/en-us/graph/api/resources/calltranscript?view=graph-rest-beta

**Comment by TetuHirai** [comment]
Transferred this question to the following Q&A (so will close this comment):
https://github.com/OfficeDev/Microsoft-Teams-Samples/discussions/764

**Comment by Meghana-MSFT** [comment]
This is currently not supported, could you please help by raising this feature ask on [Microsoft Teams Feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).
