### ISSUE TITLE
bot-conversation-sso-quickstart sign-in prompt does not display in Microsoft Teams

### ISSUE THREAD

**Issue by mercer2000** [OfficeDev/Microsoft-Teams-Samples#767]
I'm running the bot-conversation-sso-quickstart sample running on my local machine using ngrok. The sample runs fine using Bot Emulator, but the sign-in dialog does not display in Microsoft Teams. 

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/18239028/230155255-d6b2a38e-59bc-4c0f-8bc0-c13fc0901780.png">

In the Manifest, I have added the following:

  "validDomains": [
    "token.botframework.com"
  ],
  "webApplicationInfo": {
    "id": "4654acbc-48ca-4f2e-8f7e-xxx",
    "resource": "api://botid-4654acbc-48ca-4f2e-8f7e-xxx"
  }

I was testing with Microsoft Bot Framework composer and using the EnterprisePeople sample, Teams properly showed the Sign-in dialog.

The following gets called, but no sign-in dialog is displayed. 

`
        private async Task<DialogTurnResult> PromptStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
            _logger.LogInformation("PromptStepAsync() called.");
            return await stepContext.BeginDialogAsync(nameof(OAuthPrompt), null, cancellationToken);
        }`

Appsettings.json file 

{

  "MicrosoftAppId": "4654acbc-48ca-4f2e-8f7e-xxx",
  "MicrosoftAppPassword": " ",
  "ConnectionName": "",
  "MicrosoftAppType": "MultiTenant", // Set this to SingleTenant if you are using a single tenant app registration
  "MicrosoftAppTenantId": "common" // Set your tenantId here if you are using single tenant app registration.
}

My localhost is running with SSL enabled and ngrok forwards to https://localhost:44360  

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-code?tabs=cs1%2Ccs2%2Ccs3%2Ccs4%2Ccs5&pivots=bot-app#Update%20development%20environment%20variables

**Comment by mercer2000** [comment]
I was missing ngrok.io as a validDomain in the team manifest. 

`"validDomains": [
  "yoursubdomain.ngrok.io"
]`

**Comment by Prasad-MSFT** [comment]
Is your issue resolved by adding `ngrok.io` as a validDomain in the team manifest?

**Comment by mercer2000** [comment]
Yes.

Sent via the Samsung Galaxy S23 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Prasad-MSFT** [comment]
Thanks for confirming. We are closing this issue for now. Please feel free to reopen if required. Thanks!
