### ISSUE TITLE
open meeting sidepanel automatically when joining

### ISSUE THREAD

**Issue by kmulvey-frameable** [OfficeDev/Microsoft-Teams-Samples#768]
Is it possible to open a sidepanel automatically without the user having to click the app on the top bar? Is there some way to programmatically open it?

**Comment by kmulvey-frameable** [comment]
im using a JS sidepanel bot if that matters

**Comment by Prasad-MSFT** [comment]
There is no way programmatically to open meeting side panel automatically without the user having to click the app on the top bar.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
