### ISSUE TITLE
bot-sso-adaptivecard

### ISSUE THREAD

**Issue by garrytrinder** [OfficeDev/Microsoft-Teams-Samples#776]
There are many issues with this sample and it doesn't work as shown.

I have followed all the steps to configure Azure AD and Azure Bot Service. I am also able to test the OAuth connection in the Azure Portal with no issues, so I'm confident that the configuration is fine.

1. `adaptivecards-templating` package is missing which causes `npm start` to fail.
2. After attempting to sign in, the app displays an error. 
![image](https://user-images.githubusercontent.com/11563347/232632303-9448f39c-51af-4ceb-8d45-a1e5504648fc.png), most likely as the `InvokeResponse` is awaited instead of returned in the `createAdaptiveCardInvokeResponseAsync` function.
3. An sso token is always returned when inspecting the context value property in the `onInvokeActivity` function. Due to this the `onInitiateSSO` function is never executed, I assume this is why the Azure AD consent prompt is never displayed.

**Comment by Prasad-MSFT** [comment]
@garrytrinder - Thanks for raising this. We will check at our end once and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
@garrytrinder - We are able to repro this issue.
On installing **npm i adaptivecards-templating**, `adaptivecards-templating package is missing` issue got resolved. However, other issues we also encountered as you did.
![image](https://user-images.githubusercontent.com/62237649/232741725-43ad6b25-39e9-49bd-8194-908dde4d30c5.png)

We have raised a bug for the same. We will inform you once we get any further update from engineering team. Thanks!

**Comment by garrytrinder** [comment]
Thanks for the update @Prasad-MSFT

**Comment by ChetanSharma-msft** [comment]
Hello @garrytrinder - Sorry for delay in response.
We will check on the bug status with engineering team and let you know the updates.

**Comment by vman** [comment]
Hi @ChetanSharma-msft we are facing this issue as well. Any update on when can we expect the fix? Thanks!

**Comment by ChetanSharma-msft** [comment]
Hello Everyone - We are actively looking into it and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
