### ISSUE TITLE
is it possible to disable screenshare programmatically? 

### ISSUE THREAD

**Issue by kmulvey-frameable** [OfficeDev/Microsoft-Teams-Samples#783]
Ive seen how this is possible through the admin portal but is it possible through the js lib, graph api or manifest file?

**Comment by Prasad-MSFT** [comment]
@kmulvey-frameable - Currently this is not feasible. To achieve your requirements, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).


Additionally you can refer similar thread: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2442

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required.
