### ISSUE TITLE
skype tokens for a bot

### ISSUE THREAD

**Issue by kmulvey-frameable** [OfficeDev/Microsoft-Teams-Samples#789]
Is it possible to get a skype token for a bot? Its easy to get one for a human but there are some functions I'd like the bot to be able to call that require a skype token like microsoftTeams.meeting.shareAppContentToStage(). Is this possible?

**Comment by Prasad-MSFT** [comment]
To obtain authorization token for skype bot APIs, please use below cURL function:
`curl -X POST -H "Cache-Control: no-cache" -H "Content-Type: application/x-www-form-urlencoded" -d 'client_id=<your-app-id>&client_secret=<your-app-secret>&grant_type=client_credentials&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default' 'https://login.microsoftonline.com/common/oauth2/v2.0/token'`

Also refer: 1. https://learn.microsoft.com/en-us/skype-sdk/skype-for-business-bot-framework/docs/overview
2. https://learn.microsoft.com/en-us/skype-sdk/websdk/docs/ptauthwebticket
