### ISSUE TITLE
Node example not work

### ISSUE THREAD

**Issue by vectorkft** [OfficeDev/Microsoft-Teams-Samples#791]
Hello,

The sample in: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/outgoing-webhook/nodejs is not working with current version of Teams ( Microsoft Teams Version 1.6.00.11166 (64-bit) ) on Windows 11 x64

There are two problems with it:
 - first problem is that the sample not contains the environment file, and the npm start commant try to serve it on port **8080**, however, the **ngrok redirect requires 3978**
 - second problem is, thet teams not display any of the messages send by the node app, just the "Sorry, there was a problem encountered with your request" message, because of the response.write usage, you need to use 
```JS
response.setHeader('Content-Type', 'application/json');
response.statusCode = 200;
``` 
instead of the line (currently is __line 28 on app.js__ )
```JS
response.writeHead(200);
```

**Comment by Meghana-MSFT** [comment]
@vectorkft - We checked this at our end by running the outgoing webhook nodejs sample. 

point 1 is correct, as you correctly said npm start command tries to serve it on port 8080.

For point 2, we see that it is working properly with  response.writeHead(200). We havent made any changes in sample except changing the port to 3978. The sample is running properly. 

![image](https://user-images.githubusercontent.com/81138249/236165251-5b1ea505-e00b-489f-a1dc-8201efc2068e.png)

**Comment by Meghana-MSFT** [comment]
1. PR has been raised to update the port in sample - https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/795
2. Could you please let us know if you are still facing the issue?

**Comment by ChetanSharma-msft** [comment]
PR is merged now.

@vectorkft - Could you please let us know if you are facing any other problems?

**Comment by ChetanSharma-msft** [comment]
Hello @vectorkft - Hope your issue has resolved.
We are closing this issue for now, please feel free to reopen it, if required.
