### ISSUE TITLE
get participant share list in JS sdk

### ISSUE THREAD

**Issue by kmulvey-frameable** [OfficeDev/Microsoft-Teams-Samples#792]
Is there a way to programmatically see if a user is allowed to share their screen in a meeting? I know there are ways to restrict who can share when creating the meeting, I just cant find that info in the JS sdk. The closest thing I've found is the UserMeetingRole enum linked below, but that is in the live-share sdk.

https://learn.microsoft.com/en-us/javascript/api/@microsoft/live-share/usermeetingrole?view=msteams-client-js-latest#@microsoft-live-share-usermeetingrole-presenter

**Comment by Prasad-MSFT** [comment]
@kmulvey-frameable - Using JS SDK, there is no way to check if a user is allowed to share their screen in a meeting or not. 
To achieve your requirements, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by kmulvey-frameable** [comment]
@Prasad-MSFT thanks
