### ISSUE TITLE
Add deprecation note to Adaptive Card tab samples

### ISSUE THREAD

**Issue by eoinobrien** [OfficeDev/Microsoft-Teams-Samples#794]
We have announced that "Adaptive Card tabs will be deprecated in the new Microsoft Teams" - https://learn.microsoft.com/en-gb/microsoftteams/platform/tabs/how-to/build-adaptive-card-tabs

Can we update the samples that use adaptive card tabs to include this deprecation notice?
* [tab-adaptive-cards/csharp](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-adaptive-cards/csharp)
* [tab-adaptive-cards/nodejs](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-adaptive-cards/nodejs)

There may be more samples but these two definitely should be updated.

Thanks.

**Comment by Nivedipa-MSFT** [comment]
@eoinobrien - Thanks for reporting your issue. We will raise the PR for adding the deprecation note in below sample.
[tab-adaptive-cards/csharp](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-adaptive-cards/csharp)
[tab-adaptive-cards/nodejs](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-adaptive-cards/nodejs)

**Comment by Nivedipa-MSFT** [comment]
@eoinobrien - The PR has been raised for this issue: #796.

**Comment by ChetanSharma-msft** [comment]
Hello @eoinobrien - PR changes are merged.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue. Please feel free to re-open it if required.
