### ISSUE TITLE
Join Scheduled Meeting button not visible

### ISSUE THREAD

**Issue by piyushag-git** [OfficeDev/Microsoft-Teams-Samples#797]
I have successfully deployed the app. However, I can only see "Create Call" and "Create Incident" in the welcome card. Please help!

<img width="833" alt="image" src="https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/6296667/86abc524-1661-4c16-8029-2fa4123cca73">

**Comment by Meghana-MSFT** [comment]
@piyushag-git - Could you please let us know if you have setup this sample - https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-calling-meeting/csharp?

Could you also let us know if you have made any changes to the sample?

**Comment by piyushag-git** [comment]
@Meghana-MSFT Yes, I set it up exactly like that and I haven't made any changes.

**Comment by Meghana-MSFT** [comment]
Thank you for confirming, we will check this and get back to you. Could you please share the tutorial you are referring to?

**Comment by piyushag-git** [comment]
The one you sent: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-calling-meeting/csharp

**Comment by Meghana-MSFT** [comment]
@piyushag-git - We are not getting the welcome card at all for the sample, we will check with concerned team once and update you back. Thank you for your understanding.

**Comment by Meghana-MSFT** [comment]
@piyushag-git - We were able to run the sample successfully. Please note that the welcome card you got is correct. Other buttons are visible after you create the call. Please find the screenshots as below

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/39ff120f-74ab-4d5a-81a4-655acd1b5493)

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/40be288b-7435-4d5f-a75b-9ea7027e116a)

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/4d9b070b-2944-4af2-828a-e16c1a595df8)

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/d92833d8-ae7a-49bd-86ca-e8074e2f4217)


Please note that we will inform the respective team regarding the difference in appsettings.json file.

**Comment by piyushag-git** [comment]
> @piyushag-git - We were able to run the sample successfully. Please note that the welcome card you got is correct. Other buttons are visible after you create the call. Please find the screenshots as below
> 
> ![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/39ff120f-74ab-4d5a-81a4-655acd1b5493)
> 
> ![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/40be288b-7435-4d5f-a75b-9ea7027e116a)
> 
> ![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/4d9b070b-2944-4af2-828a-e16c1a595df8)
> 
> ![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/d92833d8-ae7a-49bd-86ca-e8074e2f4217)
> 
> 
> Please note that we will inform the respective team regarding the difference in appsettings.json file.

Hi! Thanks for the reply. This was exactly my question, I am not able to see the "Join scheduled meeting"

**Comment by Meghana-MSFT** [comment]
@piyushag-git - We have informed the respective team. They are looking into this issue. Thank you for your understanding.

**Comment by piyushag-git** [comment]
Can you please help me with how to add the bot to a meeting? as I can only see create a call.

**Comment by Meghana-MSFT** [comment]
You will get add to a meeting button while adding the app in Teams. Please check the below screenshot - 

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/2fb620b0-a185-4609-9925-b83d6a7217f4)

**Comment by Meghana-MSFT** [comment]
PR has been raised to update appsettings.json file in the readme file - https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/811/files.

**Comment by ChetanSharma-msft** [comment]
PR is merged now.
We are closing this issue for now, please feel free to reopen it, if required.
