### ISSUE TITLE
Cannot use tab stage view in Outlook

### ISSUE THREAD

**Issue by yukun-dong** [OfficeDev/Microsoft-Teams-Samples#802]
I'm referencing this sample https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-stage-view/nodejs to create a app with link unfurling and stage view, but when I open the stage view using deep link, the stage view is empty:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/25220706/20a1178d-ff9e-4464-86d3-32b8d538a1cb)

I noticed the deep link in "tab-stage-view" sample starts with "teams", I wonder if this link also work in Outlook and Office.
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/23f68244351be8e6cc36de1c4c9f19d0c3571cb4/samples/tab-stage-view/nodejs/server/views/sampleTab.ejs#L20

**Comment by Prasad-MSFT** [comment]
@yukun-dong - We tried to repro this issue and below are the results, please let us know if you are trying in same way and getting issue.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/e63df0df-3317-450e-8f69-3618eedd15b1)
On clicking 'Execute deeplink' button
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/d5891056-6f42-4cda-a6ce-b9c578c17692)
and now on clicking 'Ok', you are getting empty screen.

**Comment by Prasad-MSFT** [comment]
@yukun-dong - Could you please confirm this?

**Comment by Prasad-MSFT** [comment]
Hi @yukun-dong - Could you please confirm this?

**Comment by ChetanSharma-msft** [comment]
Hello @yukun-dong - We are closing this issue for now, please feel free to reopen it, if required.
