### ISSUE TITLE
deeplink to chat in meeting

### ISSUE THREAD

**Issue by kmulvey-frameable** [OfficeDev/Microsoft-Teams-Samples#809]
is it possible to create a link that will open the chat panel withing a teams meeting?

**Comment by Meghana-MSFT** [comment]
Currently it is not possible to create a deeplink that will open the chat panel withing a Teams meeting. You can suggest this idea on [Microsoft Teams feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

Currently supported deeplinks are mentioned in this doc - https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by tdalon** [comment]
I have created a Feedback https://feedbackportal.microsoft.com/feedback/idea/c64ee2c4-e0a4-f011-aa43-7c1e529756a0
