### ISSUE TITLE
Conversation update activity is not working new Pva version

### ISSUE THREAD

**Issue by GouthamGoud03** [OfficeDev/Microsoft-Teams-Samples#814]
Hi , Im working with new PVA preview version. here Im using conversation update activity to update adaptive card . it is not working.
below screenshot 
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81476480/b2781b83-80fc-4765-a9ae-1de6168bb6bc)

pls could you provide details about conversation update activity or suggest any documents of new pva version.

**Comment by ChetanSharma-msft** [comment]
Hello @GouthamGoud03 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
Hello @GouthamGoud03 - Sorry for delay in response.
We are looking into it and will let you know the updates.

**Comment by Meghana-MSFT** [comment]
@GouthamGoud03 - Apologies for the delay, could you please share the repro steps you are following?

**Comment by Meghana-MSFT** [comment]
@GouthamGoud03 - Apologies for the delay, could you please share the repro steps you are following?
