### ISSUE TITLE
bot-proactive-messaging returning exception during execution

### ISSUE THREAD

**Issue by diegoriera** [OfficeDev/Microsoft-Teams-Samples#822]
The https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-proactive-messaging/csharp is returning exception as this is using deprecated classes

System.InvalidOperationException: 'Endpoint Routing does not support 'IApplicationBuilder.UseMvc(...)'. To use 'IApplicationBuilder.UseMvc' set 'MvcOptions.EnableEndpointRouting = false' inside 'ConfigureServices(...).'

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@diegoriera - PR has been raised to update the sample. The sample will get updated once PR is merged - https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/828. Thank you.

**Comment by ChetanSharma-msft** [comment]
Hello @diegoriera - PR is merged now.
We are closing this issue for now, please feel free to reopen it, if required.
