### ISSUE TITLE
Task Module returning exception when submitTask

### ISSUE THREAD

**Issue by Tuan-TIT** [OfficeDev/Microsoft-Teams-Samples#827]
Hi,

I have implemented Task Module use handleTeamsMessagingExtensionFetchTask and handleTeamsMessagingExtensionSubmitAction of bot module

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/22438257/c077c728-f22d-40d4-9dfa-4c5a53160059)

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/22438257/70e4587c-2ab6-4cc3-88f8-820cc849b88b)

in the web view

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/22438257/b54452d1-f32f-4504-8de5-55b541d9b524)

In the chat with user and bot, it work fine, but in the Teams (channel) it will send duplicate message and show an error like image below, this issue just happened in the last 2 weeks

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/22438257/eff43baa-fed3-4d1c-bb3d-f3da773fc875)

![Screenshot_29](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/22438257/c5d23334-12fb-4f93-968a-aa948545335a)

![Screenshot_30](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/22438257/f8d69154-417f-43d3-8b2b-af8b8633ab16)

**Comment by sayali-MSFT** [comment]
@Tuan-TIT - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@Tuan-TIT - We have tested this scenario using below sample and it is working fine from our end-
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/msgext-action/nodejs/bots/teamsMessagingExtensionsActionBot.js

 Microsoft Teams Version 1.6.00.15766 (64-bit)
 
Could you please check it once?

**Comment by Tuan-TIT** [comment]
@sayali-MSFT I have implemented this scenario in MS Project template (using Tabs App and Bot)
https://github.com/Tuan-TIT/task-module-tab-and-bot

Could you please check this source?

**Comment by sayali-MSFT** [comment]
@Tuan-TIT -Sure, we will try this and let you know the update.

**Comment by sayali-MSFT** [comment]
@Tuan-TIT -We have tried to setup the above sample and running locally but getting some issue. We will inform you updates once issue resolve.

**Comment by sayali-MSFT** [comment]
@Tuan-TIT -Tried to select the command but did not return the card.

Is there any deployed manifest or deployed tenant, so that we can test and repro?

![testas](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/93527375/64891612-f846-4f31-94b3-0db02f3b71e5)
