### ISSUE TITLE
Adaptive Cards missing input values in "turnContext.Activity.Value"

### ISSUE THREAD

**Issue by calusen** [OfficeDev/Microsoft-Teams-Samples#834]
Hi,
I'm starting to get errors when I submit an Adaptive Card in this sample:
"bot-sequential-flow-adaptive-cards"

The issue just started happening in the last 2 weeks or so.

Seems like the "turnContext.Activity.Value" ("data" element of the JSON) is missing the values from the input fields:

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/23235231/e3e42f00-b8c6-4bb9-86ee-96990b04c2e9)

/Claus

**Comment by ChetanSharma-msft** [comment]
Hello @calusen - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
We are also able to repro this issue, we will check internally and get back to you.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/d209fdea-be72-41fa-aa19-f551dbde7eed)

**Comment by calusen** [comment]
Thanks for helping out :)

**Comment by Meghana-MSFT** [comment]
@calusen - We have raised a bug for the same, we will keep you posted on the updates. Thank you.

**Comment by robin-liao** [comment]
It looks like this but uses Adaptive Card template. Please note that Teams doesn't support Adaptive Card template. You may instead use adaptive card with primitive values without template.

**Comment by calusen** [comment]
Hi @robin-liao and @Meghana-MSFT - Just to make sure I understand your answer correctly, the way the sample is build is no longer supported due a change in MS Teams?
  
/Claus
