### ISSUE TITLE
Teams bot can not create the call

### ISSUE THREAD

**Issue by namnam0610** [OfficeDev/Microsoft-Teams-Samples#836]
### Discussed in https://github.com/OfficeDev/Microsoft-Teams-Samples/discussions/835

<div type='discussions-op-text'>

<sup>Originally posted by **namnam0610** June 15, 2023</sup>
Hi all,

I followed the Teams bot calling-meeting tutorial (https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-calling-meeting/csharp) steps by steps but couldn't get the bot to create the call.
After sending the "welcome" message, and select the "Create Call" card which the bot replied, select the user to call, it showed that "working on that, you can close this windows" but the call did not come.
![2023-06-15_164904](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/dab1ffc7-6fd9-43d6-a817-0b5c65d57551)

I have some confusions as below:
1. About the Webhook in Teams Channel, is that /api/callback or /callback?
![webhook](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/10912022-4ef5-45ef-8e08-d1ae10a7c227)

3. In appssetings.json, the "Users" settings in the documentation and the sample json file is different.
Document:
![document](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/14452407-a9ba-41cd-9340-68d96cc6641b)
Sample config file:
![sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/07b1b2b7-7139-42d8-a6f9-127b7057890b)

Could anyone help me with this?

</div>

**Comment by Meghana-MSFT** [comment]
Thanks for reporting this, we will check and get back to you.

**Comment by namnam0610** [comment]
Hi @Meghana-MSFT ,

Is there any updates with this?

**Comment by namnam0610** [comment]
Hi @Meghana-MSFT 
Thank you for your response.

I tried to use the settings that you suggested but the bot still could not create the call as expected.
In my case, instead of using Ngrok, I published the bot directly to Azure App Service.
Is there any restrictions in Azure App Service could cause the issue?

Here is my configuration:
1. App Registration:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/be110a2d-01ca-4576-83bc-fea182ab9bc7)
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/a2a1b089-4ebd-48e3-b620-68ad4e945a4f)
2. Azure Bot Service:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/d749a2ac-087f-4558-936f-894f78fd001f)
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/0eef9272-1722-40d4-9c3d-bd987aacd453)
3. Teams Policy:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/48c56e0e-9806-4558-b9c1-07c445c37d68)
4. appconfig.json
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/6df5b68b-611b-490b-b7d5-eeb3d765c2c2)
5. manifest.json 
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/428dec36-178d-4159-9701-4717f0dad8bd)
6. Teams App Catalog:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/095a055f-49fe-4420-a22f-42d6e7fe53ec)
7. Test in Teams Client:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/b1f18d85-0402-4f37-8d6d-6f192babcea8)

**Comment by Meghana-MSFT** [comment]
You have not added the CatalogAppId in appsettings.json.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/09cdf9cf-fce8-449b-9622-320c3537a11d)

Could you please add App ID value for CatalogAppId. You can get it form Teams admin center once you have uplaoded the app

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/1b06e95f-0798-4920-aec9-8cebf621698c)

**Comment by namnam0610** [comment]
@Meghana-MSFT I've added the App CatalogID to the config but still no luck, the call still was not created.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/d1f5108a-d02e-4830-95db-cd86918c1c66)

Do you have any other ideas?

**Comment by namnam0610** [comment]
Today I tried to use Ngrok for comparing with App Service, but the error "502 Bad Gateway" appeared when sending the welcome message.
Is the command in the document correct? As when I run the code in VS, the browser opened https://localhost:44346
So should it be 44346, not 3978?

ngrok http 3978 --host-header="localhost:3978"

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/bb0d104e-c840-46d0-94f2-8689aeb700f0)

**Comment by Meghana-MSFT** [comment]
If you are running the ngrok at port 3978 then please use CallingBotSample instead of IISExpress.

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/a6bceffd-9bb0-4bee-8e81-7267751f93cd)

**Comment by namnam0610** [comment]
@Meghana-MSFT Thanks for your clarification.
I think I've found the cause for the issue.
When I changed the "DisplayName" in the bot configuration to an English name (orginal is Japanese), the call was successfully created.

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/7308955/5b4edbf9-6d6d-4af0-8eb4-f64a2ef2c837)

**Comment by Meghana-MSFT** [comment]
Glad your issue has been resolved. We are closing this issue, please feel free to reach out to us if you have any issues? Thank you

**Comment by namnam0610** [comment]
Now I'm having issue with the PlayPrompt action.
Can the PlayPrompt action apply with outgoing calls (call from bot to user) when the user answers the call?
I've checked this article https://learn.microsoft.com/en-us/graph/api/call-playprompt?view=graph-rest-1.0&tabs=http
but I do no understand two points:
- What is the "clientContext" in the request? How to get it?
- What is the "ResouceId" of the wav file?

**Comment by ChetanSharma-msft** [comment]
Hello @namnam0610 - Could you please raise another issue on that page?
New issue link: https://github.com/microsoftgraph/microsoft-graph-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20learn.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%208d6d1637-f96b-f0ac-0ddc-8de0e47eafd6%0A*%20Version%20Independent%20ID%3A%2072708a82-f575-65c8-ee70-cd3bbe6606bf%0A*%20Content%3A%20%5Bcall%3A%20playPrompt%20-%20Microsoft%20Graph%20v1.0%5D(https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fgraph%2Fapi%2Fcall-playprompt%3Fview%3Dgraph-rest-1.0%26tabs%3Dhttp)%0A*%20Content%20Source%3A%20%5Bapi-reference%2Fv1.0%2Fapi%2Fcall-playprompt.md%5D(https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fblob%2Fmain%2Fapi-reference%2Fv1.0%2Fapi%2Fcall-playprompt.md)%0A*%20Product%3A%20**cloud-communications**%0A*%20Technology%3A%20**microsoft-graph**%0A*%20GitHub%20Login%3A%20%40rahulva-msft%0A*%20Microsoft%20Alias%3A%20**MSGraphDocsVteam**

**Comment by namnam0610** [comment]
@ChetanSharma-msft Yes I will raise a new request.
Thank you so much for all of your supports!
