### ISSUE TITLE
Geolocation throw error on android

### ISSUE THREAD

**Issue by SebastianAviles** [OfficeDev/Microsoft-Teams-Samples#846]
In android, using this code
```
let x = await geoLocation.getCurrentLocation()
    return x.longitude+","+x.longitude;
```
Throw NOT_SUPPORTED_ON_PLATFORM  error, or error 100.

In desktop and in Web works, but not on android.

How I can fix that?

**Comment by Prasad-MSFT** [comment]
@SebastianAviles - Could you please check this sample and let us know if you are able to find the location or not in Android device?
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-device-permissions/nodejs

**Comment by SebastianAviles** [comment]
Not work, in android not show the GeoLocation module.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/20979159/581b29b6-f8fe-4b62-a52d-c27ab8ea6065)
In code, the NonWebVersion has comented the lines of GeoLocation Module.

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/20979159/eba8c139-2ee1-4777-9834-5f5c2785be29)

**Comment by SebastianAviles** [comment]
I enabled by hand the modules, but still throw error 100.

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/20979159/f0bf3b1a-f788-4713-931e-b7570f76533a)

**Comment by Prasad-MSFT** [comment]
@SebastianAviles - Okay, we will check this with concerned team and will get back to you.

**Comment by Prasad-MSFT** [comment]
@SebastianAviles - Could you please let us know if you are using "geoLocation" component
`const x = await geoLocation.getCurrentLocation();`
Refer the below code ,
[microsoft-teams-library-js/apps/teamsjs-cc-app/tabs/src/components/capabilities/GeoLocation.tsx at vikramtha/teamsjs-cc-app · vikramtha/microsoft-teams-library-js · GitHub](https://github.com/vikramtha/microsoft-teams-library-js/blob/vikramtha/teamsjs-cc-app/apps/teamsjs-cc-app/tabs/src/components/capabilities/GeoLocation.tsx)

Please note that below are the supported platforms as mentioned here:
https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/teamsjs-support-m365#geolocation
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/c5ecd054-a830-443a-ae29-45930194ba6d)

**Comment by SebastianAviles** [comment]
Yes, I using geoLocation component.

But location is deprecated.

**Comment by Prasad-MSFT** [comment]
Hi @SebastianAviles - We got update from engineering team that, "Currently geoLocation is not supported in Android."
Please note that below are the supported platforms as mentioned here:
https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/teamsjs-support-m365#geolocation
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/2266fd4c-478c-4baf-86a8-992c5199c75f)

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
