### ISSUE TITLE
Need clarification on /authorize endpoint

### ISSUE THREAD

**Issue by elegault** [OfficeDev/Microsoft-Teams-Samples#85]
The sample is using the following in the script for [Start.cshtml](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-personal-sso-quickstart/csharp_dotnetcore/Views/Auth/Start.cshtml):

`let authorizeEndpoint = "https://login.microsoftonline.com/common/oauth2/authorize?" +                         toQueryString(queryParams);`

However the documentation [here](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad) says:

> To get the correct token for Microsoft Teams Free and guest users, it is important that the apps use tenant specific endpoint https://login.microsoftonline.com/**{tenantId}**. You can get tenantId from the bot message or tab context. If the apps use https://login.microsoftonline.com/common, the users will get incorrect tokens and will log on to the "home" tenant instead of the tenant that they are currently signed into.

Can you clarify the scenarios for /common and /tenantID?  Also, for multi-tenant apps the endpoints listed in the Application Registration page point to the /organization endpoint.  When should that endpoint be used?

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
