### ISSUE TITLE
Duplicate links for Personal Tab in readme file.

### ISSUE THREAD

**Issue by moirf** [OfficeDev/Microsoft-Teams-Samples#851]
Personal Tab with Nav-Bar menu added twice, see 21 and 23.  

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/8555189/88214510-872e-4eac-a758-3db9c1904fce)

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check and get back to you.

**Comment by Meghana-MSFT** [comment]
[PR](https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/848/files) has been raised to remove the duplicate entry. Readme file will be updated once the PR is merged. Thank you.

**Comment by ChetanSharma-msft** [comment]
PR link: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/852

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
