### ISSUE TITLE
is it possible to mute a meeting participant with the JS sdk?

### ISSUE THREAD

**Issue by kmulvey-frameable** [OfficeDev/Microsoft-Teams-Samples#854]

**Comment by ChetanSharma-msft** [comment]
Hello @kmulvey-frameable - We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@kmulvey-frameable - Please check the [Toggle incoming audio API](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-apps-apis?tabs=dotnet#toggle-incoming-audio) which allows an app to toggle the incoming audio state setting for the meeting user from mute to unmute or vice-versa.  

Please check this https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-audio-state/nodejs sample tab (side panel) application which shows how to mute/unmute Teams meeting audio using toggle Incoming Client Audio API.

**Comment by kmulvey** [comment]
i think i want outgoing, i.e. i'd be muting myself

**Comment by Meghana-MSFT** [comment]
We currently have an API only to toggle the incoming audio state.

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you have any further questions. Thank you.

**Comment by ChetanSharma-msft** [comment]
> i think i want outgoing, i.e. i'd be muting myself

@kmulvey - Kindly raise the feature request here: https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472
