### ISSUE TITLE
ASP.NET Core Server Side Sample

### ISSUE THREAD

**Issue by stefanodelpero** [OfficeDev/Microsoft-Teams-Samples#86]
I cannot find a server-side only sample.
What's the correct way to configure ASP.NET Core Identity for a Razor Page application used in a Teams Tab?
In other words: how do I know who the logged in user is (server side)?

**Comment by Trinetra-MSFT** [comment]
@stefanodelpero ,  Thanks for raising your concern. Could you please tell us what you are actually looking for? Does SSO or Silent Auth helps you check the current logged in user? We have samples available for [SSO in teams tab](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/csharp), [Config Tab authentication](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-config-page-auth/csharp) to see the logged in user

**Comment by stefanodelpero** [comment]
Our product is an intranet web application in ASP.NET Core.
We would like to develop some web pages to show in Teams as a Tab (for example a summary of user "things").
So the best thing would be to authenticate user at server side (ASP.NET Core Identity) so we can use our already developed server side services instead of re build everything as a API + client side.
