### ISSUE TITLE
can not run install https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-ui-templates/ts

### ISSUE THREAD

**Issue by Enghouse-CCSP-PS** [OfficeDev/Microsoft-Teams-Samples#862]
Hello
after run yarn install received error;
Syntax Error: Expected ":" or blank space but "\n" found.

**Comment by Meghana-MSFT** [comment]
Thanks for reporting this issue, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@Enghouse-CCSP-PS - We checked the [tab-ui-templates sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-ui-templates/ts).

We got this error 
 ![MicrosoftTeams-image (28)](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/f9c9d1e9-630c-40c8-832a-059e085f1e6d)

We deleted the yarn.lock file and re-ran the yarn install command. It started working again.

![MicrosoftTeams-image (29)](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/7bc321a0-04e9-47ab-90e0-223a7eec4aee)

It looks like you are getting a different error, could you please let us know if you have all the prerequisites.

**Comment by Enghouse-CCSP-PS** [comment]
Indeed after deleting yarn.lock , yarn install completed successfully, But then I got below error when 
started yarn start:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/30227436/6b3c72a3-48d0-422e-be2c-f44449f395b3)
Please also pay attention that it opened on port 3000 and not on http://localhost:3978 as documentation said.

**Comment by Meghana-MSFT** [comment]
@Enghouse-CCSP-PS - Please continue using the app in Teams, it will work in Teams app. And the sample runs on 3000 port only, we will inform respective team to update the port number to 3000 in the doc.

**Comment by rohanprasadofficial** [comment]
[script.ScriptExecutionError]: Script ('npm install --no-audit') execution error: npm WARN ERESOLVE overriding peer dependency npm WARN While resolving: @fluentui/react-compose@0.12.8 npm WARN Found: @types/react@17.0.0 npm WARN

I get this error when i try to launch with teams toolkit
