### ISSUE TITLE
cannot run meeting live caption sample

### ISSUE THREAD

**Issue by 42694647426** [OfficeDev/Microsoft-Teams-Samples#864]
Hi,

When I tried to run the meeting live caption sample, I followed the instructions, and run 
```
ngrok http 3978 --host-header="localhost:3978"
npm start
```
it gives error:
```
> meetings-live-caption@1.0.0 start
> node ./index.js


app listening to undefined
```
and when I go to http://localhost:3978
it is showing:

Cannot GET /

Can anyone helps please?

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@42694647426 - We checked this at our end and we are also seeing the same output as you. However, the sample is still working fine. We have informed the respective team regarding this, they will look into it and make changes to sample if necessary.

Please note that manually going to http://localhost:3978/Home/Configure gives below page
![MicrosoftTeams-image (30)](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/81138249/727266cb-7f91-433f-a321-6f0d405a43eb)

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
