### ISSUE TITLE
Teams Tab SSO Authentication sample - incorrect SSO resource URL

### ISSUE THREAD

**Issue by elegault** [OfficeDev/Microsoft-Teams-Samples#87]
The sample [here](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/csharp) does not include the /access_as_user path in the value for the "Single-Sign-On" section of the teams manifest:

`api://%ngrokDomain%.ngrok.io/00000000-0000-0000-0000-000000000000`

However, if /access_as_user is not set, when the tab loads the browser DevTools console with show this error:

> 0.2-angular-jquery.min-eee9041.js:114 2021-05-09T21:28:16.067Z AUTHMSAL: Attempting to handle auth response: error:invalid_resource|AADSTS500011: The resource principal named api://%ngrokdomain%.ngrok.io/00000000-0000-0000-0000-000000000000 was not found in the tenant named 00000000-0000-0000-0000-000000000000. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant., resource:api://%ngrokdomain%.ngrok.io/00000000-0000-0000-0000-000000000000, error mapped to action:resourceDisabled

0.2-angular-jquery.min-eee9041.js:114 2021-05-09T21:28:16.067Z ExtensionTabService: getAuthTokenForApp: Failed with error - resourceDisabled

This [page](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso) certainly says to NOT use /access_as_user.  Otherwise, can you explain why the above error occurs if it is not set?

**Comment by Trinetra-MSFT** [comment]
@elegault , Did you set this resource URL in Expose API section for your app also could you please confirm if you have added token.botframework.com/.auth/redirect to your Authentication redirect URL?

**Comment by elegault** [comment]
@Trinetra-MSFT Yes, the same /access_as_user path was set in the Resource URL.  Note that I'm not using Bot auth - this is a tab that's driving the authentication. Does a separate redirect for bots have to be added?? I haven't seen that documented anywhere

**Comment by Trinetra-MSFT** [comment]
@elegault, Okay, the resource URL You need to set should be in this format `api://contoso.ngrok.io/{appId}`, the page you are referring talks about SSO in Tab, This sample app is not developed for SSO in Tabs, it uses Simple Azure AD login and Silent login. i think for that you need to set the scope as access_as_user

**Comment by elegault-inventive** [comment]
@Trinetra-MSFT My resource URL is in the correct format, as per my first post that shows its format. 

This sample is titled "Teams Tab SSO Authentication", and the README.md for the repo states "This sample illustrates how to implement SSO authentication for Teams Tab".  If it's not supposed to deal with SSO authentication, then it should be stated as such!

**Comment by Trinetra-MSFT** [comment]
Apologies I misunderstood with other sample [config tab auth](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-config-page-auth/csharp), @elegault,  sorry for that. Yes SSO for Tabs document says we need to set access_as_user while setting up App in Azure. but we don't use access_as_user in resource URL of webApplicationInfo. Let me setup this sample and check it once, i will get back to you tomorrow for sure. I hope while adding the scope in Expose an API section you have followed the [SSO](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#1-create-your-aad-application) documentation and also added the authorized client applications.

**Comment by elegault** [comment]
@Trinetra-MSFT Okay, thanks. Yes, I have added the two necessary client app IDs. Regardless, my main confusion with this sample (apart from my two other open issues - #85 and #80) is that it continually relies on the invalid_grant failure when first trying to get minimal consent. It doesn't properly demonstrate a proper flow of:

_ask for consent -> ask for consent for additional Graph scopes -> get a Graph access token -> call Graph -> repeat -> do NOT ask for consent -> get a Graph access token -> call Graph._

The differences between doing the same for single tenant AND multi-tenant apps should also be highlighted.

Also: @elegault-inventive is another GitHub account of mine but not my primary - apologies for any confusion, as I didn't realize I was signed into my secondary account.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
