### ISSUE TITLE
Teams personal chat More settings button in the application

### ISSUE THREAD

**Issue by deviluncle** [OfficeDev/Microsoft-Teams-Samples#871]
I would like to know how I can make my application also appear the Settings button as shown in the picture below when it is right-clicked, and the default is only unins
tall and pin​​
![bc948b54-ace6-4db4-a98e-b24d0b65447e](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29850196/e04114c7-964b-4756-b81c-3482ffcc2b6a)

**Comment by deviluncle** [comment]
I have been looking for a long time in the official document, but I can’t find where to set this in the manifest.json, please tell me, thank you

**Comment by Meghana-MSFT** [comment]
You can get the settings option only for Messaging extensions. You need to set [canUpdateConfiguration](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#:~:text=message%20extension%20supports.-,canUpdateConfiguration,-Boolean) to true which will enable Settings menu item. `canUpdateConfiguration` value indicates whether the configuration of a message extension can be updated by the user.

You can refer below sample, configuration is handled using `OnTeamsMessagingExtensionConfigurationQuerySettingUrlAsync`. 
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/03dae3d9e7fe34ca968abdc530ebef95132f490b/samples/msgext-search-auth-config/csharp/Bots/TeamsMessagingExtensionsSearchAuthConfigBot.cs#L114

**Comment by deviluncle** [comment]
Thank you very much for your reply. I have tried and displayed the settings button

**Comment by deviluncle** [comment]
I have another question to ask. My client asked whether the width of the iframe module in the picture below can be customized. I replied that it cannot be customized, but the client wants to hear Microsoft's official answer, so please answer by the way.
![9c7d5188-713a-457b-93dd-51339bc2d220](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29850196/ae67d43a-85bc-44db-a6e9-66907601083e)

**Comment by Meghana-MSFT** [comment]
We will check and get back to you.
