### ISSUE TITLE
Meeting Side Panel app not working

### ISSUE THREAD

**Issue by Prasad-MSFT** [OfficeDev/Microsoft-Teams-Samples#877]
While running the C# sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-sidepanel/csharp

In README it is mentioned to run ngrok in 3978 ports. However, the app runs in 3001 ports.
Also gives below error on running:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/7c395124-11ce-431a-9c28-dafc6dc09fa3)
Also, in README it is mentioned
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/77362fd4-f464-47d7-afde-0ff39526fa1b)
and on running 
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/94fc7272-3341-4197-907f-f815f36c24b8)

Similarly, in NodeJS sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-sidepanel/nodejs
On running server:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/40a3aad9-aa4c-4529-8c99-41d4e5771928)
On running client:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/4c86e627-0e8c-4de8-899e-047d89a30195)

The steps are really confusing. Please make it clear.

**Comment by sayali-MSFT** [comment]
We will redirect to appropriate team to have a look at this issue and update the sample accordingly.

**Comment by Prasad-MSFT** [comment]
The issue is fixed. So, closing this instance
