### ISSUE TITLE
'Something went wrong' error while using meeting token app

### ISSUE THREAD

**Issue by Prasad-MSFT** [OfficeDev/Microsoft-Teams-Samples#878]
While using this sample, https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-token-app/csharp
its asking for authentication and on entering credentials its giving below error and the sign in pop up stays there going on a loop.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/62237649/7f059942-b4b2-4b1e-ab5b-4a4c1f01c388)

and also, the NodeJS sample is giving error and guidance not clear
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-token-app/nodejs

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will redirect this to appropriate team.

**Comment by Prasad-MSFT** [comment]
The issue has been fixed via this [PR](https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1099). So, closing it.
