### ISSUE TITLE
Use Microsoft teams meeting invite link as a Task module in Bot on click of the Button.

### ISSUE THREAD

**Issue by ambuj74** [OfficeDev/Microsoft-Teams-Samples#89]
I have a Microsoft teams bot and I wanted to use Microsoft meeting invite link i.e ["https://teams.microsoft.com/l/meeting/new?subject="] to open it as a task module inside the teams bot on click of a button.

I have tried putting inside iframe as follow but it is not loading: 

`<iframe width="1000" height="700" src="https://teams.microsoft.com/l/meeting/new?subject=" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>

Below is the screenshot of teams behaviour  

`
![image](https://user-images.githubusercontent.com/57623400/118115622-d28a1400-b406-11eb-9505-9d463a29db87.png)

can you please tell the fix for the issue.

**Comment by Wajeed-msft** [comment]
@ambuj74 - you can not embed the meeting experience in iFrame directly. Instead you could [Generate a deep link to the scheduling dialog](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generate-a-deep-link-to-the-scheduling-dialog) which will lauch new meeting dialog. Please let us know if that helps.

**Comment by ambuj74** [comment]
Hi @Wajeed-msft  Thanks for the response, I have already used the deep link  as you have suggested but that is launching the meeting dialog in fullscreen , below is the screenshot
![image](https://user-images.githubusercontent.com/57623400/118806386-9eaa6500-b8c4-11eb-98ad-14811cb7cb16.png)


Is there any possibilities to open the meeting dialog in small size screen.

**Comment by Wajeed-msft** [comment]
Unfortunately, it does not support customization for size. Do you see any problem due to full screen design?

**Comment by ambuj74** [comment]
Hi @Wajeed-msft  Thanks for the response, But I have requirement where on click the button the meeting dialog should open as given in the below screenshot

![image](https://user-images.githubusercontent.com/57623400/119799756-03377680-befa-11eb-9ee0-cf2cb3ab82d7.png)

**Comment by Wajeed-msft** [comment]
The UI for scheduling dialog has been changed to full screen. Same is show when you deep link to scheduling dialog. This is by design.
