### ISSUE TITLE
Teams app does not send composeExtension/anonymousQueryLink  invoke request

### ISSUE THREAD

**Issue by kostinams** [OfficeDev/Microsoft-Teams-Samples#895]
I am running the [sample "msgext-link-unfurling" for C#](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-link-unfurling/csharp) and trying to call anonymousQueryLink method. 

I followed the instruction from Microsoft Docs https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=desktop%2Cdotnet%2Cadvantages#enable-zero-install-link-unfurling 
and changed in my manifest the value `supportsAnonymizedPayloads `, and added an implementation of the 
` OnTeamsAnonymousAppBasedLinkQueryAsync(ITurnContext<IInvokeActivity> turnContext, AppBasedLinkQuery query, CancellationToken cancellationToken)` method in my LinkUnfurlingBot class. 

However, this new method is never called, because I can see in the profiler that the Teams app still sends requests with the type "composeExtension/queryLink" . It seems like supportsAnonymizedPayloads setting in manifest did not change the type of invoke to "composeExtension/anonymousQueryLink" (that's what I expect according to the Docs page). 

What is the correct way to configure manifest or Teams app to send composeExtension/anonymousQueryLink ? 

here's my manifest:
```
      "messageHandlers": [
        {
          "type": "link",
          "value": {
            "domains": [
              "*.botframework.com",
            ],
            "supportsAnonymizedPayloads": true,
            "suggestedActions": {
              "actions": [
                {
                  "type": "setCachePolicy",
                  "value": "{\"type\":\"no-cache\"}"
                }
              ]
            }
          }
        }
      ]
```

**Comment by sayali-MSFT** [comment]
@kostinams -Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@kostinams -Could you please check the below sample-
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/af593fbf2a87b81cff39e5c054b98017908ca448/samples/msgext-search-sso-config/nodejs/bots/teamsMessagingExtensionsSearchAuthConfigBot.js#L360



` if(context.activity.name === "composeExtension/anonymousQueryLink") {
            const card = CardFactory.adaptiveCard({
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.5",
                "body": [
                    {
                    "type": "TextBlock",
                    "text": "Zero Link unfurling card",
                    "weight": "bolder",
                    "size": "extraLarge"
                    },
                    {
                    "type": "TextBlock",
                    "text": "Install the app to view full content of the card.",
                    "size": "large"
                    }
                ]
            })`

**Comment by sayali-MSFT** [comment]
@kostinams - Thank you for sharing the findings. We will review them on our end and keep you updated.

**Comment by sayali-MSFT** [comment]
@kostinams -If you install the app and then add the unfurl link, it is displaying the composeExtension/queryLink. 
Additionally, zero-install link unfurling assists in previewing your shared links before users discover or install your app in Teams. You can anonymously unfurl cards using a new invoke request or create pre-authenticated Adaptive Card previews for users prior to them installing or authenticating your app.
also check the payload of the activity you're receiving. Verify that the 'anonymousQueryLink' information is being sent correctly in the activity's payload.

Reference document-https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=desktop%2Cjson%2Climitations#enable-zero-install-link-unfurling

**Comment by sayali-MSFT** [comment]
@kostinams -Yes, you can just upload the app; there's no need to install it.

**Comment by sayali-MSFT** [comment]
@kostinams - First, you should add the app to the app store. Do not install the app. Then, you can try link unfurling and add the debugger to that method, as you mentioned above, and check the activity name."

> @sayali-MSFT ,
> 
> I've just tried the Node.js sample you suggested - I am still receiving activity as 'queryLink' and not 'anonymousQueryLink' , attached a screenshot from debugger , you can see what's recieved from Teams app:
> 
> ![image](https://user-images.githubusercontent.com/50990049/258812985-685f429d-1c70-425c-bcc5-5e137d010603.png)

**Comment by neelapeela** [comment]
@kostinams Hey, did you ever end up figuring this out? Running into the same issue.
