### ISSUE TITLE
How to control the pop-up form of the settings page of the Teams application in the message extension

### ISSUE THREAD

**Issue by deviluncle** [OfficeDev/Microsoft-Teams-Samples#907]
Taking the example of the "Azure Boards" application, when right-clicking and selecting "settings" in the "Posts" section of "Teams," a small new browser window opens.
![8ed791d0-4bd2-4fd0-a761-206a911935c7](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29850196/65b0706b-0be4-46e7-a900-ee348ea35dee)
![060a745e-6064-4fac-a8c6-58ba438bfc25](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29850196/9221388e-8cc0-4ac8-bf87-9bac9e32f319)

However, in the "Chat" section, it opens a new browser tab.
![c16b8c49-8a14-4318-b3d3-df3ef88ea9c9](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29850196/8562293b-e741-41fb-bc25-5d96ac05d044)
![6ce5470a-3e07-4f93-8b63-4545c5ceec6d](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29850196/66f14b0d-c0c2-4ae9-9c7f-c926f4dca93e)
I've reviewed the interface at 【https://apac.ng.msg.teams.microsoft.com/v1/agents/28:7299542a-1697-4ec1-812b-6b70065c0795/invoke】 and haven't found any differences in the returned values.
![082c1628-21e5-40f1-90c5-3220824568e8](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29850196/4ef5dea0-2043-4ad9-97c3-f6c629533f21)

And other add-in programs will have different ways to open the settings screen.
May I ask if I want to control the setting screen of my add-in program, whether in [Teams] or [Chat], I want to open a small browser window instead of a tab page, how to achieve it?

**Comment by Prasad-MSFT** [comment]
@deviluncle - We verified that if you try to open the settings page of the Teams application in the message extension from chat via web browser, then it opens a new browser tab. However, if you perform the same action via Teams desktop app, pop-up appears. Could you please verify that?

**Comment by deviluncle** [comment]
> @deviluncle - We verified that if you try to open the settings page of the Teams application in the message extension from chat via web browser, then it opens a new browser tab. However, if you perform the same action via Teams desktop app, pop-up appears. Could you please verify that?

Thank you for your reply
I know the difference between the web end and the desktop end. What I want to ask is why the setting page of the same program appears as a new browser tab in [Teams] conversation, but pop-up in [Chat] (as shown in the figure below) , and how I configure my own Teams app's settings page popup.
![1](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29850196/d1c3103a-8dc1-4081-9348-354df343569b)
![2](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29850196/bb1d0801-f28d-408b-86ad-f64600c0b989)
![3](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29850196/93a8cfe7-fcb1-4963-83ed-e51b60bd3f17)
![4](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29850196/437ba8cb-8c13-4685-b155-d30cf99e2919)
![5](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/29850196/673a8eea-653d-42b6-ac67-ba814277fe19)

**Comment by Prasad-MSFT** [comment]
@deviluncle - Got it. We will check this with engineering team why there is discrepancy in behaviour and will update you once we hear from them. Thanks!

**Comment by ChetanSharma-msft** [comment]
@deviluncle - Sorry for delay in response. We are checking this with engineering team why there is discrepancy in behavior and will update you once we hear from them. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @deviluncle, we got update from engineering team that, "the behavior of desktop vs web is expected behavior".

**Comment by deviluncle** [comment]
Thank you for your reply. 
This issue is not about desktop and web, but rather concerning the [Teams] and [Chat] tabs.

**Comment by Prasad-MSFT** [comment]
Hi @deviluncle, what i mean to say here is that the opening of popup within desktop [Teams] and opening in web ["Chat"] is expected as informed by engineering team.

I hope this is clear. Thanks

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
