### ISSUE TITLE
How can we integrate the user-assigned managed identity bot in Teams?

### ISSUE THREAD

**Issue by nithin-viswanathan** [OfficeDev/Microsoft-Teams-Samples#909]
I am trying to hook my user-assigned bot into teams. But User authentication is not happening. It is showing "Login was not successful; please try again." 

I am using the below URL for reference. [Code](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/csharp_dotnetcore/BotConversationSsoQuickstart)

**Comment by Prasad-MSFT** [comment]
@nithin-viswanathan - Could you please provide more details on the issue you are facing? Do you mean when you are trying to login after setting up the application you are getting above mentioned error in Microsoft Teams?

**Comment by nithin-viswanathan** [comment]
> @nithin-viswanathan - Could you please provide more details on the issue you are facing? Do you mean when you are trying to login after setting up the application you are getting above mentioned error in Microsoft Teams?

Yes. I have created two Azure Bots, One is MultiTenant and other is User Assigned Manged Identity. First Bot is working fine in Teams. But the second Bot's user authentication is not working.

**Comment by nithin-viswanathan** [comment]
> > @nithin-viswanathan - Could you please provide more details on the issue you are facing? Do you mean when you are trying to login after setting up the application you are getting above mentioned error in Microsoft Teams?
> 
> Yes. I have created two Azure Bots, One is MultiTenant and other is User Assigned Manged Identity. First Bot is working fine in Teams. But the second Bot's user authentication is not working.

After clearing the cache the Bot itself is not working in teams. Both Bots are working when hooked to a website.

**Comment by Prasad-MSFT** [comment]
@nithin-viswanathan - For User Assigned Manged Identity Bot the `MicrosoftAppType`   property value should be `UserAssignedMSI`. Could you please reverify if you have configured the same in appSettings?

**Comment by nithin-viswanathan** [comment]
> @nithin-viswanathan - For User Assigned Manged Identity Bot the `MicrosoftAppType` property value should be `UserAssignedMSI`. Could you please reverify if you have configured the same in appSettings?

Yes. It is UserAssignedMSI. Do we need both teams and managed identity resource in same tenant?

**Comment by Prasad-MSFT** [comment]
If the MicrosoftAppType is MultiTenant then it will work across different tenants only.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
