### ISSUE TITLE
`handleTeamsMessagingExtensionFetchTask` show "unsupported" in sso flow

### ISSUE THREAD

**Issue by wenytang-ms** [OfficeDev/Microsoft-Teams-Samples#928]
hi, i'm trying this sample [msgext-search-sso-config](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/msgext-search-sso-config/nodejs/bots/teamsMessagingExtensionsSearchAuthConfigBot.js)
according to the sso flow in [`handleTeamsMessagingExtensionFetchTask`](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/e45ae5631b991ce29ad5892e42a2392a402722e7/samples/msgext-search-sso-config/nodejs/bots/teamsMessagingExtensionsSearchAuthConfigBot.js#L230C11-L230C49)
I tried the app command `compose` without login before, but the app show unsupported in the card as follow.
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/75360946/a02695e4-f792-4aa4-a1d1-85af163f4ddc)
but the sign in flow is success in [`handleTeamsMessagingExtensionQuery`](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/e45ae5631b991ce29ad5892e42a2392a402722e7/samples/msgext-search-sso-config/nodejs/bots/teamsMessagingExtensionsSearchAuthConfigBot.js#L138)
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/75360946/33b098fc-8dab-4472-89b7-cccd2e324915)

According to [this doc](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-code?tabs=cs1%2Ccs2%2Ccs3%2Ccs4%2Ccs5&pivots=mex-app), the second notification says message extension does not support sso except query and linkunfurling, I don't know if there is some misunderstanding.

**Comment by Nivedipa-MSFT** [comment]
@wenytang-ms - Thanks for reporting your issue. We will test this and update you soon.

**Comment by wenytang-ms** [comment]
@Nivedipa-MSFT what's more, this sample use `BotFrameworkAdapter` which is already [deprecated](https://github.com/microsoft/botbuilder-js/blob/cbb187dec6ccfe096bf6df70dad898a41a90ae49/libraries/botbuilder/src/botFrameworkAdapter.ts#L92). so do you have any plan to upgrade this sample?

**Comment by Nivedipa-MSFT** [comment]
@wenytang-ms - We will discuss this with the concerned team and will take necessary action.

**Comment by wenytang-ms** [comment]
it seems that this sample already upgrade to `cloudAdapter` but still has some problems, so do you have any connect?

**Comment by ChetanSharma-msft** [comment]
Hello @wenytang-ms - Could you please share the details about error/problems, so that we can look into those?
