### ISSUE TITLE
Reference link broken

### ISSUE THREAD

**Issue by MuyangAmigo** [OfficeDev/Microsoft-Teams-Samples#936]
`https://aka.ms/sample-ref-teams-vids-from-community` this link used in the `assets\sample.json` was broken.

**Comment by Meghana-MSFT** [comment]
@MuyangAmigo - Thank you for reporting this issue, could you please let me know which sample.json you are referring to?

**Comment by MuyangAmigo** [comment]
@Meghana-MSFT Here: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-task-module/csharp/assets/sample.json

**Comment by Meghana-MSFT** [comment]
Thank you for additional info, we will inform this to the concerned team and get it updated.

**Comment by ChetanSharma-msft** [comment]
Raised the PR for it: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/975

**Comment by ChetanSharma-msft** [comment]
PR is merged. Closing this issue.
