### ISSUE TITLE
End of life Python SDK

### ISSUE THREAD

**Issue by zurferr** [OfficeDev/Microsoft-Teams-Samples#939]
There are more than 10M Python developers in the world.
I am one of them and would like to use the Python SDK to build a Teams bot.

Could you please reassess the decision to stop support for the Python SDK by Nov 2023?

**Comment by Meghana-MSFT** [comment]
Thank you for your feedback, we will share the feedback internally.

**Comment by Meghana-MSFT** [comment]
@zurferr - We have the following update from the engineering team - "Bot Framework SDK is not currently reconsidering the Python SDK deprecation".

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
