### ISSUE TITLE
SidePanel Sample ClientApp Loads with Wrong Port on non-Windows OS

### ISSUE THREAD

**Issue by ryankmcintyre** [OfficeDev/Microsoft-Teams-Samples#952]
The `start` and `start:client` scripts in [ClientApp/package.json](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/meetings-sidepanel/nodejs/ClientApp/package.json) are using `set` to set environment variables for PORT and HTTP/HTTPS. The `set` command only works on Windows, AFAIK. When running in non-Windows, this results in the variables not being set and the ClientApp running on the default port of 3000, which causes other things to fail. To get this working on non-Windows (e.g. I'm using Ubuntu with WSL), `set` needs to change to `export`.

Maybe consider using a .env file for these values and updating them appropriately. Or use something like [cross-env](https://www.npmjs.com/package/cross-env).

**Comment by Prasad-MSFT** [comment]
@ryankmcintyre - Thanks for raising this issue. We will verify this at our end and will take necessary action/ make changes.

**Comment by Prasad-MSFT** [comment]
@ryankmcintyre - Team has updated the changes. Please do verify.

**Comment by ChetanSharma-msft** [comment]
Hello @ryankmcintyre - We have merged the as a part of this PR: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/980

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
