### ISSUE TITLE
SidePanel Sample ClientApp Incorrect Port Protocol

### ISSUE THREAD

**Issue by ryankmcintyre** [OfficeDev/Microsoft-Teams-Samples#954]
The ClientApp is currently configured to run locally with https. However, the "Start local tunnel" task in [tasks.json](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/57c87fc7e371e722d5a13018ed61b7c81b02dbdf/samples/meetings-sidepanel/nodejs/.vscode/tasks.json#L47C32-L47C32) is set to use http. The result is a 502 bad gateway error.

Changing from `"protocol": "http"` to `"protocol": "https"` in tasks.json fixes that error.

**Comment by Prasad-MSFT** [comment]
@ryankmcintyre - Thanks for raising your issue. We will check this and after discussing with concerned team will make necessary changes.

**Comment by ChetanSharma-msft** [comment]
Hello @ryankmcintyre - Sorry for delay in response.
We are checking on it and let you know the updates.

**Comment by Prasad-MSFT** [comment]
The sample works fine with "protocol": "http" & "protocol": "https". 

We are closing this issue for now. Please feel free to reopen if required. Thanks!
