### ISSUE TITLE
How to handle SharePoint online site alert in Microsoft teams using Microsoft graph

### ISSUE THREAD

**Issue by Haider-cloud-creater** [OfficeDev/Microsoft-Teams-Samples#956]
I am trying to look for a Sharepoint online site to create an event, List, and update saved in the list to notify in the Microsoft Teams activity icon. Can you guide me about this issue, How to pass data from the Sharepoint site through Microsoft Graph API to send notifications on the Microsoft Teams activity feed?
How can we implement those features try the possibilities

**Comment by sayali-MSFT** [comment]
@Haider-cloud-creater - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@Haider-cloud-creater - To achieve this scenario, you can integrate Microsoft Teams activity feed notifications with your SharePoint Intranet portal site. This will allow you to update the list on the notification in the Teams activity feed. Here's how you can do it:

**Implement Activity Feed Notifications**:

Follow the [step-by-step guide](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-graphactivity-feedbroadcast) to implement activity feed notifications in Teams.
This guide will help you understand how to send notifications to the Teams activity feed using the Microsoft Graph API.

**Create a SharePoint List**:

In your SharePoint Intranet portal site, create a custom list to store the notifications from the Teams activity feed.
You can create columns in the list to capture relevant information from the notifications, such as the notification message, sender, timestamp, etc.

**Handle Activity Feed Notifications**:

When a notification is sent to the Teams activity feed, you need to handle it in your SharePoint Intranet portal site.
You can create a webhook or use the Microsoft Graph API to receive the notifications in your SharePoint site.
Once you receive the notification, you can parse the data and update the SharePoint list accordingly.

**Display Notifications in SharePoint**:

Use SharePoint web parts or custom development to display the notifications from the SharePoint list on your Intranet portal site.
You can create a custom web part or use the out-of-the-box web parts like the List web part or Highlighted Content web part to display the notifications.
Customize the web part to show the relevant information from the SharePoint list, such as the notification message, sender, timestamp, etc.

By integrating Teams activity feed notifications with your SharePoint Intranet portal site, you can keep your users updated with the latest notifications and display them in a centralized location. This allows for better collaboration and communication within your organization.

You can learn more about activity feed notifications in Teams from the [official documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/design/activity-feed-notifications).

Also look into this sample-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-activity-feed-broadcast/csharp
