### ISSUE TITLE
Duplicated 'entities' are reported in the 'activity' whenever mentioned on Teams.

### ISSUE THREAD

**Issue by ramfattah** [OfficeDev/Microsoft-Teams-Samples#969]
Transferred from [botbuilder-js](https://github.com/microsoft/botbuilder-js/issues/4379) to Microsoft-Teams-Samples repository. 

We've identified this is a Teams Issue and waiting on Teams for updates. 

Please see original issue here:
https://github.com/microsoft/botbuilder-js/issues/4379

#

## Versions
What package version of the SDK are you using.
 **botbuilder": "4.18.0",
 botframework-directlinejs": "0.15.1"**

What nodejs version are you using
**v16.6.2**

What browser version are you using
**109.0.1518.5 (Official build) dev (64-bit)** 

What os are you using
**Windows 10**

## Describe the bug
In Microsoft teams when someone is mentioned the bot `activity` is reporting back duplicate `entities` (same id but different name) whenever there is a space in the name 

## To Reproduce

On a `Teams` channel:
- Mention two people (plus the bot)
-e.g Hi `@FirstName Lastname` and `@Firstname2 Lastname2`

In this example assume "@FirstName Lastname" is a single person and "@Firstname2 Lastname2" is another one.

## Expected behavior
Some weeks ago the behavior was to return 1 entity per mention (on the `entities` array). In the previous example it would a similar JSON to:

contents of `activity.entities`
```
[
    {
        "mentioned": {
            "id": "FAKEID1",
            "name": "FirstName LastName"
        },
        "text": "<at>FirstName LastName</at>",
        "type": "mention"
    },
    {  
        "mentioned": {
            "id": "FAKEID2",
            "name": "FirstName2 LastName2"
        },
        "text": "<at>FirstName2 LastName2</at>",
        "type": "mention"
    },
    {
        "locale": "en-US",
        "country": "US",
        "timezone": "America/Los_Angeles",
        "type": "clientInfo"
    }
]

```
## Actual behavior
It currently returns 4 entities 2 pairs with the same id but different name:
contents of `activity.entities` (please note the id)

```
[
    {
        "mentioned": {
            "id": "FAKEID1",
            "name": "FirstName"
        },
        "text": "<at>FirstName</at>",
        "type": "mention"
    },
    {
        "mentioned": {
            "id": "FAKEID1",
            "name": "LastName"
        },
        "text": "<at>LastName</at>",
        "type": "mention"
    },
    {
        "mentioned": {
            "id": "FAKEID2",
            "name": "FirstName2"
        },
        "text": "<at>FirstName2</at>",
        "type": "mention"
    },
    {
        "mentioned": {
            "id": "FAKEID2",
            "name": "LastName2"
        },
        "text": "<at>LastName2</at>",
        "type": "mention"
    },
    {
        "locale": "en-US",
        "country": "US",
        "timezone": "America/Los_Angeles",
        "type": "clientInfo"
    }
]

```

**Comment by ramfattah** [comment]
CC Original Author @mkm-dz

**Comment by ramfattah** [comment]
Hi Teams, any status update on this issue?

**Comment by Prasad-MSFT** [comment]
Hi @ramfattah - Thanks for reporting this issue. We will check this now from our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
Hi @ramfattah - We tried to repro this issue using below sample and it is working fine at our end. 
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/nodejs
Duplicate `entities` are not being reported.

```
    "entities": [
        {
            "mentioned": {
                "id": "28:4acdc558-04cc-49d2-a0c1-4c0f4138a9e9",
                "name": "Action Messaging Extension"
            },
            "text": "<at>Action Messaging Extension</at>",
            "type": "mention"
        },
        {
            "mentioned": {
                "id": "29:1eUpDed1o99pzmlc0XckNhcat-0q_7GED-_O6jGKw1GBVIw4urNk0NN225FXq-1vIk6bAtqw5jVklQ1cREE9wNg",
                "name": "Allan Deyoung"
            },
            "text": "<at>Allan Deyoung</at>",
            "type": "mention"
        },
        {
            "mentioned": {
                "id": "29:1Cv--PflibXhi1hK_C_XQ8V0ZtZgyUO_QQFBtzAyw8n7ktEeUwQpGf9p6hyK7seqCrwAfb7YKN0O1xB6T6Ns2kw",
                "name": "Megan Bowen"
            },
            "text": "<at>Megan Bowen</at>",
            "type": "mention"
        },
        {
            "locale": "en-GB",
            "country": "GB",
            "platform": "Web",
            "timezone": "Asia/Calcutta",
            "type": "clientInfo"
        }
    ],
```

Tested in `Microsoft Teams Version 1.6.00.25871`
`"botbuilder": "^4.20.0"`
`Windows 10`

Could you please try to upgrade and check if it helps?

**Comment by ramfattah** [comment]
CC @mkm-dz. It appears this issue has been fixed.

**Comment by ramfattah** [comment]
Thank you @Prasad-MSFT for you effort in verifying.
