### ISSUE TITLE
Refresh Adaptive Card Content

### ISSUE THREAD

**Issue by ki12312** [OfficeDev/Microsoft-Teams-Samples#984]
I have a business requirement in which I want to send an adaptive card to the user in Personal chat & Group chat. I am able to send that adaptive card using teams messaging extension. Now I want to refresh the adaptive card to show the latest data. I am doing something like this when user clicks on the refresh button to get the latest data:

    var resposne = await context.updateActivity({
      id: context.activity.replyToId,
      type: "message",
      attachments: [card],
    });
but I am getting this Error: The bot is not part of the conversation roster.

Is it possible or am I missing something?
TIA.

**Comment by sayali-MSFT** [comment]
@ki12312 - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@ki12312 -Did you get chance to check the above sample?

**Comment by ki12312** [comment]
Yes, But it is giving me error "The bot is not part of conversation Roster"

**Comment by sayali-MSFT** [comment]
@ki12312 -Here is deployed manifest. Could you please try it once and confirm the same?
[bot-conversation (1).zip](https://github.com/OfficeDev/Microsoft-Teams-Samples/files/12868809/bot-conversation.1.zip)
