### ISSUE TITLE
Files.Read SSO in Teams channel conversation

### ISSUE THREAD

**Issue by christopher5106** [OfficeDev/Microsoft-Teams-Samples#986]
Hi,
I would like my bot to access the Teams channel files when necessary from the conversation with the users in the channel, with an  SSO delegated permission.  Please tell me find which sample is the closest to my need. 
Best,

**Comment by sayali-MSFT** [comment]
@christopher5106 - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@christopher5106 -You can refer the Tab SSO sample-
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/csharp
But you need to integrate the custom code to get channel List in the above sample-

```
var graphClient = new GraphServiceClient(requestAdapter);

var result = await graphClient.Teams["{team-id}"].Channels.GetAsync();
```
Reference document-https://learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=csharp#example-1-list-all-channels

**Comment by christopher5106** [comment]
I was wondering more about bot, not tab. Thanks

**Comment by sayali-MSFT** [comment]
@christopher5106 -You can refer this sample as well-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/csharp_dotnetcore

**Comment by ChetanSharma-msft** [comment]
Hello @christopher5106 - Hope your issue has resolved now?
Please share your valuable feedback via [Microsoft Teams Developer](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
