### ISSUE TITLE
Many of the samples do not properly wait for the initialize() function in teams-js to complete

### ISSUE THREAD

**Issue by AE-MS** [OfficeDev/Microsoft-Teams-Samples#988]
If you look through these search results:
https://github.com/search?q=repo%3AOfficeDev%2FMicrosoft-Teams-Samples+microsoftTeams.app.initialize%28%29%3B&type=code

You will see many places where `microsoftTeams.app.initialize()` is called but either not `await`ed or followed by `.then()`

Per the documentation for [app.initialize()](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app?view=msteams-client-js-latest#@microsoft-teams-js-app-initialize), the call must complete before any other teams-js calls are made to avoid race conditions.

It's hard to know by just looking at the search results how many of them are bugs (theoretically calling `app.initialize()` without waiting for it to finish is only a bug if you aren't calling any other teams-js functions after), but it would appear that many of them are (e.g., [app-in-meeting.jsx](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/e043a8577214c11ee2551e9a8145aa357dfd16c5/samples/meetings-stage-view/nodejs/ClientApp/src/components/app-in-meeting.jsx#L17) calls initialize and then immediately calls `getContext`, and [searchSettings.html](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/msgext-search-sso-config/nodejs/public/searchSettings.html) calls `initialize` and doesn't verify it's complete before potentially calling `authentication.notifySuccess`)

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will share this with sample team and get these updated.

**Comment by ChetanSharma-msft** [comment]
Hello @AE-MS - We have started working on it and let you know the updates once changes are done.

**Comment by Meghana-MSFT** [comment]
https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1008 has been raised for this issue.
